mozilla/neqo

neqo-client/src/main.rs, neqo-common/src/lib.rs, neqo-http3-server/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/hframe.rs, neqo-http3/tests/httpconn.rs, neqo-interop/src/main.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-transport/src/connection.rs, neqo-transport/src/packet.rs, neqo-transport/src/tracking.rs, neqo-transport/tests/conn_vectors.rs
Replace use of u64 as nanoseconds with instances of Instant and
Duration, sometimes wrapped by Option as needed. This eliminates any
confusion about time units for calculations, and also between values
that are absolute time (Instant) or some delta, possibly in the future
(Duration). Resolves at least 2 bugs.
Modify tests as needed. Some values in test_loss_recovery2() needed
to be modified in order to account for the new notion that things are
calculated based on the current "time" as represented by start + some
Duration for how much time has passed.
Make largest_acked and loss_time in LossRecoverySpace options, since
they may not exist (and 0 is a valid value for largest_acked). This
also affects LossRecoverySpace::largest_acknowledged() and
PacketNumberDecoder::new().
Rename deadline …
=> Use Instant and Duration instead of u64(nanos) for time calcs

hooks/pre-commit
I encourage everyone to enable this.  It's fast enough to run on every commit, which saves a bunch of mucking around with formatting.  It's also accurate - it only checks staged changes, so it won't be fooled by stuff that you don't plan to commit.
=> Add pre-commit hook for format

neqo-crypto/build.rs
This reverts commit 59c94cfc31dc6fd259c793259bcff9e6da4b6aae.
Closes #62.
=> Revert "Use the hacked version of NSS"

neqo-transport/src/recovery.rs
Note that this results in better calculations for these durations, so
the tests need to account for different rounding.
Next step is to remove those clunky constants.
=> Use cleaner code for calculating RTT

neqo-transport/Cargo.toml, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
Smallvec allocates space for some number of entries on the stack
and then can alloc from the heap if more space is needed. This
prevents a heap allocation for small temporary vecs.
Because of the borrow-checker, we use vecs in a number of places
to gather results and then act upon them in a later step. Using
smallvec can keep these from allocating most of the time.
Note: Smallvec is already used extensively in Gecko so it will not
increase the number of dependent crates we'll need to review.
=> transport: use smallvec

neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs
The goal is to keep less state, or at least make it more explicit, to make
it easier to diagnose timer-related bugs.
connection.rs:
Move check_loss_detection_timeout to process_input(), I think this lines
up better with idle timeout check that is there.
Match on LossRecoveryMode in check_loss_detection_timeout().
Use map() to avoid match in next_delay()
recovery.rs:
Document why INITIAL_RTT is not what spec says.
Add LossRecoveryMode enum to better describe exclusive nature of the loss
recovery timer.
Remove loss_time from LossRecoverySpace. Instead of using its values to
mean whether the time-based loss detection timer should be active, use
an explicit boolean enable_timed_loss_detection.
Remove LossRecovery::loss_detection_timer. Instead, calculate it when
get_loss_detection_timer() is …
=> transport/lossdetection: Refactor

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet.rs
output_vn() calling obtain_crypto_state(0) is wrong. Instead,
call create_initial_state(). This occasioned some more
code moving from connection.rs to crypto.rs, and Agent is
now part of Crypto struct, but pub(crate).
Add a VN test.
Fix a bug the test exposed in encode_packet_vn().
=> transport: Fix issues with server VN packets

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/frame.rs, neqo-transport/src/recovery.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tracking.rs
Redo timers. More clearly separate the two parts of a)
figuring out the duration and mode of the timer to set and
b) handling when a timer expired. There was some common code
that should not have been common, or at least was confusing,
I thought.
The way it works now is that the timer duration and mode is
set in next_delay() called in process_output(). This may
set a timer but also remembers what loss recovery mode is
active (if any) in loss_detection_state.
Then some time later, process_input() will be called, either
because a timer expired or because new packets have arrived.
check_loss_detection_timeout() handles this, and knows that
if a timer was the cause what to do without further steps, by
looking at loss_detection_state. There are still TODOs in
check_loss_detection_timeout for …
=> Make timers make more sense, and de-traitize recovery tokens

hooks/pre-commit
I wasn't successful in testing this, but `--check` really doesn't help.
=> Remove --check from rustfmt invocation

neqo-client/src/main.rs, neqo-http3-server/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/hframe.rs, neqo-http3/tests/httpconn.rs, neqo-interop/src/main.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-server/src/main.rs, neqo-transport/src/connection.rs, neqo-transport/src/lib.rs, neqo-transport/src/server.rs, neqo-transport/tests/conn_vectors.rs, test-fixture/src/lib.rs
When trying to add Retry for a server, I found that the API that handles
multiple packets was inconvenient.  There is no real need to have the
loop inside Connection anyway, so I externalized it.  This simplifies
the API and implementation a decent amount and should help avoid
problems.
This isn't complete at the moment because we don't set any timeout when
there is more data to send.  As a result, if we have more to say than
fits in a single packet, we won't say it until given the opportunity.
For the moment, that means either hitting the loss recovery timer or
getting a new packet inbound.  The way that the generators are
structured makes it very difficult to do that right now because we have
a single generator squatting on the queue always.
As part of fixing process_input and …
=> Operate on one datagram at a time

neqo-common/src/log.rs
We cannot use builder.init because it will panic when it is used with gecko. Other rust components may already initialized logging.
=> Gecko inits log as well, so we cannot hard fail.

neqo-http3/src/connection.rs, neqo-http3/src/request_stream_client.rs
Testing against F5 revealed http3 doesn't generate an event if a 0-length stream frame with fin set is received.
Hat tip: Martin Duke
=> Fix h3 stream fin

neqo-transport/src/connection.rs
We don't yet actually retry (#15), but it's good to be
clear why the connection is stuck, so it's not just a
mystery.
=> Add info message if we get a valid retry packet

README.md
As seen [here](https://github.com/mozilla/neqo/blob/master/neqo-http3-server/src/main.rs#L32) the host:ports to listen to have changed lately.
The readme was unfortunately not up to date anymore.
=> Updated the run test http 3 programs example to match the new args.

neqo-http3/src/connection.rs
The previous code handled later data frames by adding to a
list that would cause process_http3() to eventually call
cs.receive() to parse frame header etc. The problem was that
relying on more incoming packets to process already-received
data could stall when the client had received all the data
but there was another data frame header that needed parsing:
read_data() would return up to the end of one data frame, but
the next data header and data remained unparsed on the
stream.
Instead, try to read/parse the next h3 header if the app has
read any data and fin is not set.
=> Fix stall parsing data frames if no new packets arrive

neqo-http3/src/connection.rs, neqo-http3/src/request_stream_client.rs, neqo-transport/src/connection.rs, neqo-transport/src/events.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
This should fix #111 
One super cool aspect is that methods now require &self instead of &mut self.
I don't know the codebase at all yet, but I feel like TransportParameters and FlowMgr could follow the same path. 
Also I don't know if will make sense someday but from what I understand making these structs threadsafe will be pretty easy if need be :D
=> Make events contain their Rc

neqo-transport/src/connection.rs
In doing retry, I found that we weren't padding coalesced Initial+0-RTT packets.
=> Pad 0-RTT packets too

.circleci/config.yml, neqo-common/src/codec.rs, neqo-common/src/incrdecoder.rs, neqo-crypto/src/prio.rs, neqo-crypto/src/result.rs, neqo-crypto/src/ssl.rs, neqo-crypto/src/time.rs, neqo-crypto/tests/agent.rs, neqo-crypto/tests/handshake.rs, neqo-http3/src/connection.rs, neqo-http3/src/hframe.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/huffman.rs, neqo-transport/src/connection.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet.rs, neqo-transport/src/recovery.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tracking.rs
VS Code runs clippy on tests.  I don't know how to do that from the command line (or else I would change our CI setup as well), but these are the problems I found and fixed.
The only thing I didn't fix were a couple of functions that were past the cognitive complexity limit.
=> Clippy tests

neqo-http3-server/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/request_stream_client.rs, neqo-http3/src/request_stream_server.rs, neqo-http3/tests/httpconn.rs
WIP to fix #41 .
There's a couple of uses of &[Header] and Vec<Header>.
@martinthomson would it be worth considering switching every use to a Vec and having a Headers type? 
I'm not really sure of the performance implications, but it might make the code easier to read ?
=> Splitted the request handler function into a RequestHandler type.

neqo-http3/src/connection.rs, neqo-http3/src/hframe.rs
We do not need to exit the loop in HFrameReader's receive() when alll data of an known frame has been discharged.
=> Continue reading when a unkown frame has been discharged.

neqo-client/src/main.rs, neqo-http3-server/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/lib.rs, neqo-transport/src/connection.rs, neqo-transport/src/lib.rs, neqo-transport/src/recovery.rs
Previous PR was #100.
Use enum IdleTimeout to track state of idle timeout.
Set idle timeout in transport parameters.
API CHANGE: Connection now exposes both a process_input() and
process_timer() method, instead of process_input() handling
both incoming packets and timer expiry.
Arbitrarily pick 60 seconds as idle timeout value.
fixes #38
=> Implement idle timeout (API CHANGE) (take 2)

neqo-transport/src/send_stream.rs
I couldn't fix mark_as_acked here because that falls squarely in
borrow-checker territory (I'm surprised that it doesn't complain as-is,
but whatever).
=> Use ref mut less

neqo-client/src/main.rs
This uses the args parser so that we don't have to have a janky parser for header field options.  The usage is '-h <name> <value>' with this whole construct repeated as needed.
The thing I noticed when doing this is that I was forced to create a copy every time we send a request.  That's not ideal, but I didn't want to refactor neqo-client more than is needed.  This process could be done just once if we cared about that sort of refinement.
=> Use the args parser more for -h

.mergify.yml
GitHub provides this capability now.  And the rule was causing all of our PRs to report an orange dot (in progress) rather than a tick (CI passed), which was annoying.
=> Remove "delete head" rule for mergify

neqo-client/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/lib.rs, neqo-http3/src/transaction_client.rs, neqo-interop/src/main.rs
- change get_headers/read_data names into something more descriptive,
- make read_response_headers return fin flag as well,
- make read_response_headers and read_response_data a bit nicer,
- add new error InvalidStreamId so that we do not use a transport error,
- add ResponseHeadersState to be easier to decide if we need to add HeadersREady or Data Ready event, also we do not need struct Response,
- the TransactionClient::receive code was not handling fin bit correctly in all cases, I moved setting state to TransactionRecvState::ClosePending in functions actually handling new data and new frames
- make separate functions for some parts of TransactionClient::receive,
- add test for cases wher fin was handled wrong.
=> Refactor receiving part of the transaction_client:

neqo-client/src/main.rs, neqo-crypto/Cargo.toml, neqo-crypto/bindings/bindings.toml, neqo-crypto/bindings/mozpkix.hpp, neqo-crypto/build.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/agentio.rs, neqo-crypto/src/auth.rs, neqo-crypto/src/err.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/result.rs, neqo-crypto/tests/agent.rs, neqo-crypto/tests/handshake.rs, neqo-http3/src/connection.rs, neqo-http3/src/hframe.rs, neqo-http3/tests/httpconn.rs, neqo-interop/src/main.rs, neqo-transport/src/connection.rs, test-fixture/src/lib.rs
Note that the From<PRErrorCode> here is for convenience.  Ideally, that
doesn't exist in this code, because users of the API won't have a
PRErrorCode to pass in.  But I suspect that gecko will, and mapping into
the enum is busy-work that you might not want to do right away.
Closes #142.
=> Define an enum for authentication status

neqo-transport/src/connection.rs, neqo-transport/src/events.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/send_stream.rs
We should only send the writable event if there's both room in
the tx buffer and also stream send credits. SendStream::avail()
checks both of these, whereas the existing code just checked
tx buffer room.
Note: The event still does not guarantee the app can send,
because connection flow control credits may not be available
if consumed first by other streams.
fixes #175
=> Check SendStream::avail() before sending writable event

neqo-client/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/lib.rs, neqo-http3/src/transaction_client.rs, neqo-http3/src/transaction_server.rs, neqo-interop/src/main.rs
- make sending a request body possible,
- add events DataWritable and StopSending,
- StopSending will be only posted for the EarlyResponse error code,
- fix reset/stop_sending handling (reset will reset sending side as well, stop_sending with EarlyResponse will only close sending side, stop_sending with another error will close both sides of a stream)
=> Refactor request sending part and reset handling:

neqo-client/src/main.rs, neqo-http3/Cargo.toml, neqo-http3/src/connection.rs, neqo-http3/tests/httpconn.rs
Instead of "create a new http3events with undesired events
filtered out" strategy, remove events more directly.
Change authentication_needed() to take &self for consistency.
We're using runtime checks instead of compile-time ownership
checks.
Have events() return Iterator instead of collections, as
previously done for transport layer.
Rename test called fetch() to fetch_basic(), to make it
easier to run by itself (its entire name is not the prefix
for other tests).
Further test changes to handle events() returning Iterator.
fixes #195
=> Rework Http3Events a little

neqo-http3-server/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/transaction_server.rs, neqo-http3/tests/httpconn.rs
This is just extending server functionality a bit. A proper fix will need http3 refactoring (issue #20). Until that is done this change makes possible at least a bit of automatic testing for mozilla-central.
With this change we can cancel request.
=> The http3 server should be able to cancel a stream as well

neqo-transport/src/connection.rs
If we get a packet that doesn't encrypt, we will advance the connection
state.  This is bad, because we crash later when we try to access the
idle timeout, which we don't set.
=> Don't make connections from bad packets

neqo-common/src/codec.rs, neqo-crypto/bindings/bindings.toml, neqo-crypto/src/aead.rs, neqo-crypto/src/err.rs, neqo-crypto/src/hkdf.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/p11.rs, neqo-crypto/src/selfencrypt.rs, neqo-crypto/tests/selfencrypt.rs, neqo-transport/src/crypto.rs
This self-encryption capability enables the generation of tokens that can only be processed by the same instance of the class.  It has basic key rotation capabilities built in so that keys can be swapped out over time.
There isn't any provision for synchronizing these between instances (which is what you would need for a real server), but this is probably enough for our immediate purposes.
This builds on #220, #219, and #215, so you might want to look at those first.
=> Basic self encryption

neqo-http3/src/lib.rs, neqo-transport/src/lib.rs
Our error codes are a little unwieldy, but keeping the non-numbered ones
in some order might help with finding them.
=> Sort internal errors

neqo-transport/src/lib.rs
The code is more specific now (it used to be TypeError), but the overly specific message that was
logged is removed.
This depends on #223 and #219 somewhat depends on this.
=> Integer overflow error

neqo-transport/src/server.rs, neqo-transport/tests/server.rs
This looks like a lot of code, but it's the last commit as a delta to #226.  This adds proper retry tokens to the server code and some new tests for those.
There's a really big test that simulates an attacker spoofing a retry, so that we can test that the client checks for the original connection ID transport parameter.  That was hard to write, so I'll bet that it's hard to read.  I stared at it for a bit trying to work out how to factor it down, but it's all interlinked in awkward ways.  I do want to factor out the ability to decrypt and re-encrypt initial packets, but would prefer not to build all the supporting machinery for that capability today.  I'd prefer to open an issue to track that, so that we can dedicate the right amount of time to the task.
=> Retry with self-encrypt

neqo-client/src/main.rs, neqo-http3/src/connection.rs, neqo-interop/src/main.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-server/src/main.rs, neqo-transport/src/connection.rs, neqo-transport/src/events.rs
A small refactoring commit, and then:
Change transport event interface and implementation
Add a next_event() method and prefer it over events(). Using it allows event loops to receive additional events added as previous events are processed, as well as not receiving events that have been obsoleted.
Use VecDeque to chronologically order events. Change some events to removeother events that are no longer relevant or correct.
Add Connection::has_events() for use by Server::process_connection().
fixes #200
=> Change transport event interface and implementation

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet.rs, neqo-transport/src/recovery.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tracking.rs, neqo-transport/tests/server.rs
In our tests with real servers, we identified a problem with our Retry
code.  We were sending two Initial packets with CRYPTO data in it with
a direct marking of that data as lost in between.  However, when the
second packet is acknowledged, the first will be marked as lost and the
loss recovery tokens associated with that packet will be sent twice.
But those should not be.
This change lifts the level at which retry operates.  The packets are
marked as lost and the regular "lost packet" processing invoked.  There
is a TODO there with respect to congestion control; we don't currently
have a congestion controller, but when we do that will need to be
scrubbed when a Retry comes in.
=> Redo Retry implementation for the client

neqo-transport/tests/connection.rs
This would be a serious security bug if it weren't for the status of
this project and the nice properties of Rust.
=> Check for overflow on long header packets

neqo-transport/src/connection.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
After calling stream_stop_sending on a stream, we should not accept anymore data from the peer on that stream.
=> Calling stream_stop_sending should do something

neqo-transport/src/crypto.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/recovery.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tracking.rs
Separate the idea of when a packet should be declared lost (and thus
retransmitted) from when we should actually forget about what the packet
contained. Hold on to SentPackets for at least 2*RTT beyond when they are
declared lost.
This will make it possible for things to go directly from "lost" to "acked"
state. Crypto and Stream tokens should already handle this because they're
based on TxBuffer, which already handles ranges going from unmarked (as
would be the case if lost) directly to acked, and has tests to check this.
Ack tokens do nothing when lost, so no issue. Flow tokens don't care about
being acked except for ResetStream: remove requeued ResetStream if present.
Requires SentPacket and members be clone()able, since detect_lost_packets()
must return a Vec of these, and also now …
=> Track lost packets for a while after they are declared lost

neqo-transport/src/connection.rs
Remove redundant semicolons in neqo-transport connection
tests. These are okay on stable, but cause compilation failure
in nightly.
=> Redundant ; in neqo-transport connection tests

neqo-http3/src/connection.rs, neqo-http3/src/transaction_server.rs, neqo-transport/src/frame.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
For boolean functions implemented with a match, use
the matches! macro for implementation, where possible.
=> Use matches! where possible

neqo-common/src/log.rs, neqo-common/tests/log.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/agentio.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/control_stream_local.rs, neqo-http3/src/control_stream_remote.rs, neqo-http3/src/hframe.rs, neqo-http3/src/stream_type_reader.rs, neqo-http3/src/transaction_client.rs, neqo-http3/src/transaction_server.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/dump.rs, neqo-transport/src/recovery.rs, neqo-transport/src/server.rs, neqo-transport/src/tracking.rs
rustfmt likes this better.
Remove non-comma layout option from log macros.
=> Put comma after use of [self] in log messages

neqo-crypto/build.rs
This change is necessary to ensure that the files we create with bindgen
still compile when we get to 1.39.
This is necessary before we bump the docker image.
=> Prepare for Rust 1.39

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/frame.rs, neqo-transport/src/recovery.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tracking.rs
*Should cut down #280's size as it's worked-on and clear out the "easy" stuff first.*
Probe Timeout:
* SendStream: Add support for TxMode::Pto
Output:
* Rename Connection::output_path() to output_pkt_for_path() for clarity.
* Do not replace path in Connection::output() with None before calling
output_pkt_for_path(). We can't do this or Path::pmtu() will be wrong.
Instead, handle it inside the called function. This will work until we
support more than one path.
Crypto:
* Change Crypto::create_initial_state() to set state internally rather than
returning the state to the caller to set.
Sent packet tracking (tracking.rs):
* Ask for an ack immediately if received packed is out of order.
* Add test
FlowMgr:
* Remove pending DataBlocked frame if max credit is increased.
* Support max_data frame …
=> Pull out unrelated things from #280

docker/Dockerfile
If we're going to start using rust 1.39, then we probably should make sure that the CI image is up to date.
=> Bump the version of rustup in the CI image

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/frame.rs, neqo-transport/src/send_stream.rs
This should save a few bytes.
(BTW, I still don't like the way we make unnecessary copies here, but fixing that would require that we restructure frame and packet parsing in a big way.)
Fixes #283.
=> Better fit CRYPTO/STREAM to packets

neqo-transport/Cargo.toml, neqo-transport/src/packet.rs
I need to update this dependency to get rid of old syn and quote in
mozilla-central.
But it seems like in this case it's easier to get rid of it, it saves like five
lines of code, and brings in a ton of dependencies.
Let me know if you want to keep it and update the dependency instead, but I
think it's not worth it in this case.
=> transport: Remove derive_more dependency.

neqo-transport/src/connection.rs, neqo-transport/src/lib.rs, neqo-transport/src/tparams.rs
Right now, `neqo_transport::Connection::set_local_tparam` is public but cannot actually be used  because there is no way to publicly `create a neqo_transport::Connection::TransportParameter`. Refactor to correct for this.
=> Issue #316: Make neqo_transport::Connection::set_local_tparam publicly usable

neqo-transport/src/connection.rs
One issue I've seen with tests is verifying certain things are in a packet
when we can't actually see what was IN the packet. test_process_input()
is the same as process_input() but returns a Vec of the frames just
processed, so unit tests can assert they are as expected. This could be
used by #323 as well as #311 and maybe also #303, and more in the future.
Details:
Change return values of internal functions input() and process_packet()
to return the vec. input_packet() is refactored into process_packet().
If cfg(test), we clone decoded frames and return them, as well as
passing them into input_frame(). In the non-test case, we do not
clone frames and push to the vec, so the vec remains empty, so not much
added overhead in the non-test case.
This also moves duplicate packet check above …
=> Add test_process_input() that returns frames processed

neqo-common/src/timer.rs
If the timer-to-be-removed is more than `Timer::span()` in the future,
there's no way that it can be in the timer wheel. With this patch,
the function will immediately return `None` and won't even search for it.
=> Issue #319: Do not try to remove a timer outside a timer wheel's span

neqo-transport/Cargo.toml, neqo-transport/src/send_stream.rs
It doesn't work on FreeBSD.
The cool feature of SliceDeque was it could represent the collection as a slice, using vmm magic. Not having this capability means that data that wraps across the end of the buffer will need to be presented twice in `next_bytes` (since non-contiguous) rather than as a single range that could be put into a stream frame.
fixes #60
=> Remove usage of slice-deque crate

neqo-crypto/build.rs
Upstream NSS no longer includes dbm support by default, so neqo-crypto
should not include it in static libs list.
=> Fix neqo-crypto build issue

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
First two commits are trivial.
Last commit is broken out from #280 (pretty much everything but congestion control):
Output:
* Handle TxMode::Normal and also TxMode::Pto in packet output.
* Move construction of PacketHdr before frame sources are polled. This
is needed so the frame sources can have accurate bytes-remaining
values passed to them.
* packet.rs: For ^^, add overhead(), to learn how many bytes the header
will take when encoded.
* Change LossRecovery::next_pn() to return but not increment PN, since we
now construct headers that may not be used in a sent packet. Add inc_pn()
to call once we know a PN will be used.
* Add PTO tests.
Crypto refactorings (needed for output changes):
* Refactor crypto to enable a stream and a state to be independently
borrowed.
fixes #289
=> Implement PTO probe and also honor PMTU

neqo-http3/src/client_events.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/lib.rs, neqo-http3/src/server.rs, neqo-http3/src/server_connection_events.rs, neqo-http3/src/server_events.rs, neqo-http3/src/transaction_client.rs, neqo-http3/src/transaction_server.rs, neqo-interop/src/main.rs
Http3Connection only handles common elements:
- holds control and qpack streams,
- holds a HashMap of active transactions,
- holds the Http3State of a http3 connection,
- performs sending data for control, qpack and transaction streams,
- handles decoding of new unidi streams(the client/server handlers differ in how they handle a  Push streams, therefore handle_new_unidi_stream returns if a stream was a push stream and the client/server handler consume them appropriately),
- handles streams reading (this function may return that a stream is a push stream or a list of control frames to be handle by the client/server handler)
The client/server handlers:
- holds a base_handler(Http3Connection)
- http3 events
- neqo_transport::Connection (this is only for the client)
- process_htttp3 has been …
=> Http3conn rework

neqo-transport/src/connection.rs, neqo-transport/tests/server.rs
> When sending CONNECTION_CLOSE, the goal is to ensure that the peer will process the frame. Generally, this means sending the frame in a packet with the highest level of packet protection to avoid the packet being discarded. However, during the handshake, it is possible that more advanced packet protection keys are not available to the peer, so the frame MAY be replicated in a packet that uses a lower packet protection level.
> After the handshake is confirmed, an endpoint MUST send any CONNECTION_CLOSE frames in a 1-RTT packet. Prior to handshake confirmation, the peer might not have 1-RTT keys, so the endpoint SHOULD send CONNECTION_CLOSE frames in a Handshake packet. If the endpoint does not have Handshake keys, it SHOULD send CONNECTION_CLOSE frames in an Initial packet.
fixes #265 …
=> Send connection close in all keyed epochs

neqo-crypto/build.rs, neqo-crypto/src/aead.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/agentio.rs, neqo-crypto/src/auth.rs, neqo-crypto/src/err.rs, neqo-crypto/src/ext.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/p11.rs, neqo-crypto/src/secrets.rs, neqo-crypto/src/selfencrypt.rs, neqo-crypto/src/ssl.rs, neqo-crypto/src/time.rs
Part of #150, I was struggling trying to disable the default features (which doesn't do too well with build.rs) but given the number of warnings, we might as well clear them all instead :)
I don't know enough about the internals to be 100% confident Aead::expansion() will remain static, so please let me know if I should revert the change and allow unused self instead :)
=> Toggle clippy::pedantic on neqo-crypto.

neqo-transport/src/send_stream.rs
It is not true that highest_offset >= offset+len, because we unmark ranges
that were sent but need to be retransmitted (b/c lost.) If this happens and
then an ack comes in for the range, that is ok.
fixes #352
=> Remove bad assert in TxBuffer::mark_as_acked()

neqo-qpack/src/decoder.rs
The duplicated entry is 50 bytes. This means that the table's capacity
has to be 100 bytes.
=> Issue #372: Properly set decoder capacity in decoder::test_duplicate

neqo-common/src/codec.rs, neqo-common/src/datagram.rs, neqo-common/src/incrdecoder.rs, neqo-common/src/lib.rs, neqo-common/src/once.rs, neqo-common/src/timer.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/agentio.rs, neqo-crypto/src/auth.rs, neqo-crypto/src/err.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/p11.rs, neqo-crypto/src/secrets.rs, neqo-http3/src/hframe.rs, neqo-server/src/main.rs, neqo-transport/src/connection.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/tests/server.rs
- Fixed new clippy (default) lints
- Fixed new pedantic lints in neqo-crypto
- Toggled pedantic in neqo-common
Please let me know if you would like me to squash the commits, and if there's anything I can do to improve the PR :)
=> Toggle pedantic on neqo common

README.md
Add more details on BKMs for testing and debugging Neqo, both on its own and as part of Gecko.
=> Update README.md with more info on debugging

neqo-common/src/datagram.rs
The existing debug statement drops an array, which is ugly and hard to
use.  This uses hex().
=> Better debug for Datagram

neqo-crypto/src/agent.rs, neqo-crypto/tests/agent.rs
The current code doesn't ever close the socket, which means that the TLS
code leaks a LOT.  That's bad.  Implement Drop and add a function that
closes the socket.
=> Implement Drop for SecretAgent

neqo-crypto/src/hkdf.rs, neqo-crypto/src/selfencrypt.rs
We don't need the flexibility implied by passing a size parameter to
generate_key().  Worse, this could be abused to create bad keys.  So
just call key_size() internally, and stop exporting it.
=> Let HKDF work out the size of its own keys

neqo-crypto/src/aead.rs
Merge this once everyone is on rust 1.40 and the unused_self warning is
understood.
Closes #402.
=> Remove unknown lint allow

neqo-crypto/src/agent.rs, neqo-crypto/src/secrets.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/frame.rs, neqo-transport/src/lib.rs, neqo-transport/src/packet.rs, neqo-transport/src/recovery.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/server.rs, neqo-transport/src/stats.rs, neqo-transport/src/tracking.rs
This changes the code to operate on packet number spaces instead of
epochs.  That makes it slightly easier to manage in some places.
The major shift here is in how keys are made.  The current code just
tries to make every key when it is sending packets, iterating through
the epochs as it goes.  This code attempts to only create keys at the
right points in the state machine.  This is only really perfect for
application read keys, which are generated when the handshake is
complete.  Other keys it creates after processing CRYPTO frames.
A later change that might help is to propagate events from the TLS layer
about key availability, which would make this more precise, but this was
already getting big.
This doesn't do key discard, but it should be much easier to implement
now that keys won't …
=> Key updates

neqo-crypto/bindings/bindings.toml, neqo-crypto/src/lib.rs
It turns out that NSS doesn't always do this and it is a little
distracting if you want to use SSLTRACE to debug certain functions.
=> Enable SSLTRACE for debugging

neqo-transport/src/connection.rs, neqo-transport/src/lib.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
This patch fix a couple of problems with PTO (fixes #308 and #385):
This patch fix a couple of problems with PTO:
- Implement a separate PTO timer for each packet number space,
- Move loss_recovery_state: LossRecoveryState into loss_recovery,
- Keep track of a number of ack_eliciting_outstanding packets,
- If a PTO expires send packets in its pn space and above. For example, if the PTO timer in the Handshake pn space expires we will try to send a datagram with a Handshake packet and a packet in the app pn space if we have keys for app space (this will increase chances that the server can decrypt them and send an ack),
- Fix #385 by adding LossRecoveryState::PtoExpired.
=> Fix PTO and implement a separate PTO for each PN

neqo-client/src/main.rs, neqo-http3-server/src/main.rs, neqo-interop/src/main.rs, neqo-transport/src/lib.rs, neqo-transport/tests/conn_vectors.rs
This doesn't do any of the concrete things we need for compatibility,
but it changes the version numbers.
I have three things that we need to do at the transport layer (aside from stuff we already don't do):
* HANDSHAKE_DONE (I have a start with #407)
* Retry integrity
* Symmetric idle timeout
=> Update version to draft-25

neqo-crypto/Cargo.toml, neqo-crypto/build.rs
Unfortunately Gecko is not cool with bindgen 52.
=> Revert move to bindgen 52

neqo-crypto/src/agent.rs
Occasionally handy but also noisy. Let's drop it to trace level.
=> Reduce trace level of "Got ALPN: None" message

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet.rs, neqo-transport/src/tparams.rs
Coalesce log output for consecutive padding frames.
Use qtrace whenever hex() is used on a large buffer.
Only log when disallowed frames are seen in is_allowed().
=> Further reduce debug spew

neqo-transport/src/connection.rs
Slightly messy because we build headers sometimes and we don't use them, but still useful I think.
=> Add logging around packet header we're building

neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/lib.rs, neqo-qpack/src/table.rs
- fix unused_variables and dead_code
- fix use of Vec<u8>
- header ack should also ack the instructions on the encoder side
- properly use max_block_streams and improve how the references to the dynamic entries are stored. Also make sure this works if a stream has multiple header blocks.
- some tests refactoring
- add test for max_block_streams and reference countting for entries.
=> Fix some part of qpack code

neqo-transport/src/flow_mgr.rs, neqo-transport/src/recv_stream.rs
Previously, we would no longer enqueue MAX_STREAM_DATA frames but we
did not remove an already enqueued frame. This fixes that by adding
a clear_max_stream_data method to FlowMgr, which is called when a
RecvStream transitions out of Recv state.
Refactor SendStream: Move RecvStreamState::transition() to
RecvStream::set_state().
fixes #435
=> Do not send MAX_STREAM_DATA if stream is no longer in Recv state

neqo-transport/src/recovery.rs
`map(|x| { do_something(&x); x })` can be replaced with
`inspect(|x| do_something(&x)`.  There is probably a lint for that, but
we don't have all the lints on yet.
=> Use inspect rather than map

neqo-crypto/src/aead.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/ext.rs, neqo-crypto/src/hkdf.rs, neqo-crypto/src/hp.rs, neqo-crypto/src/p11.rs, neqo-crypto/src/replay.rs, neqo-crypto/src/selfencrypt.rs
Clippy in 1.41 has a new lint.
=> Add error documentation to crypto functions.

neqo-transport/src/crypto.rs
This was first available in Rust 1.40, which unfortunately is not yet
used for Firefox builds, so we need to avoid for the moment.
=> Avoid usage of mem::take()

docker/Dockerfile
In order to use this as a base image for the neqo-qns image, we need to
execute commands as root, both to install additional software as well as
altering the network configuration. Install sudo and add 'neqo' user
to sudoers.
=> Dockerfile: enable sudo

neqo-transport/src/connection.rs
Add another check here so that we don't accept a state transition we don't want.
=> Reject HANDSHAKE_DONE before handshake completion

neqo-transport/src/cc.rs, neqo-transport/src/connection.rs, neqo-transport/src/lib.rs, neqo-transport/src/path.rs
Change the default path MTU
Factor path code into its own file
Include Initial padding in accounting for the Inital packet bytes
Refactor tests
This will interact with the 2 packet PTO change in #448, but I can sort that out fairly easily.
=> Path MTU fixes

neqo-http3/src/connection_client.rs, neqo-http3/src/hframe.rs, neqo-http3/src/lib.rs, neqo-http3/src/response_stream.rs, neqo-http3/src/transaction_client.rs, neqo-http3/src/transaction_server.rs
Fixes #344     
Furthermore:
- Move response part of the client transaction into a separate file
- do not return an error if trailers are received (Fixes #437 #264 ).
=> HFrame::Header should contain header_block and make the receive side of transaction simpler

neqo-transport/src/cc.rs
This is basically the same bug as #365.
We keep SentPackets that were deemed lost around for a bit longer, just
in case they get acked then we win. But, they're subtracted from BIF when
deemed lost. When they are actually removed from sent_packets they
should not be subtracted again.
see https://bugzilla.mozilla.org/show_bug.cgi?id=1616009
=> Don't subtract discarded pkts from BIF if previously deemed lost

docker/Dockerfile
see https://bugzilla.mozilla.org/show_bug.cgi?id=1615003
It's ok if we don't exactly track Gecko's rust version, but we shouldn't
get ahead of it. I think we want 1.41 to use the new lockfile format.
=> Use rustc version matching minimum Gecko version

neqo-transport/src/cid.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet.rs
Check in packet parsing and NEW_CONNECTION_ID.
Note that we ignore server preferred address, so this doesn't check
that.
With tests!
=> Checks for connection ID length

neqo-transport/src/send_stream.rs
Fix bug in setting fin on retransmitted packets
Previously, we would set fin on retransmitted packets if the final size was known. This is incorrect, we should only set fin on packets that are retransmitting the last byte.
This issue was reported by CloudFlare. Thanks to @junhochoi for the report and analysis.
=> Fix FIN retransmit issue

neqo-transport/src/crypto.rs
This reverts commit e2b1faac522f74ca2e1d484a8faadd66786a1f1b.
We had to do this because Firefox was still on an older Rust compiler version, but now they've moved up so we can use the more natural mem::take method.
=> Revert "Avoid usage of mem::take()"

neqo-common/Cargo.toml, neqo-crypto/Cargo.toml, neqo-http3-server/Cargo.toml, neqo-http3/Cargo.toml, neqo-qpack/Cargo.toml, neqo-transport/Cargo.toml, test-fixture/Cargo.toml
This should cut down on total code size as well.
=> Disable default-features for the log crate to reduce binary size

neqo-client/Cargo.toml, neqo-crypto/Cargo.toml, neqo-http3-server/Cargo.toml, neqo-http3/Cargo.toml, neqo-interop/Cargo.toml, neqo-qpack/Cargo.toml, neqo-server/Cargo.toml, neqo-transport/Cargo.toml, test-fixture/Cargo.toml
I have no idea how to enforce this on an ongoing basis, but having consistency now might help ensure that we keep consistency.
=> Use consistent spacing in toml files

neqo-transport/src/send_stream.rs
Added a test to reproduce the issue reported in:
https://bugzilla.mozilla.org/show_bug.cgi?id=1622237 .
Also another test for a different issue. The conversion to using VecDeque was making some bad assumptions that resulted in bugs when the first slice returned from VecDeque::as_slices() was empty but the second had some data.
=> transport: Fix issues in TxBuffer::next_bytes()

neqo-client/src/main.rs
These let neqo-client be used for the quic-network-sim (QNS) "http3" test.
=> More neqo-client fixes for QNS

neqo-qpack/src/decoder.rs, neqo-qpack/src/table.rs
This is a fix for https://github.com/mozilla/neqo/issues/533
=> Allow base used in header block to be larger than number of inserts in the dynamic table.

neqo-crypto/build.rs
Checking out the tip of these, NSS especially, can cause mysterious
breakage that's not our fault. Instead of the tip, check out recent RTM
tags.
=> Checkout specific tags of NSS and NSPR

neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs
We have a fixed idle timeout, but we aren't using the value from the
peer to set our actual timeout.
This does that.  It chooses the minimum value from both endpoints.  But
it also is careful not to go lower than 3x the current PTO, which might
otherwise cause things to go pear-shaped.
=> Use the minimum idle_timeout value from both peers

neqo-client/src/main.rs, neqo-http3/src/connection_client.rs, neqo-interop/src/main.rs
Instead of making users of this code know that they need to call
process_http3() before or after calling other process_() methods,
call it from within those.
Make process_http3() no longer a public method.
NOTE: This will require changes to glue code when/if merged into Gecko.
=> http3 client: Fold calls to process_http3 into other process_ methods

neqo-crypto/src/agent.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/ssl.rs
This makes the setting of options available to other crates.  That will
make it possible to run some tests later.
=> Factor SSL option handling

neqo-crypto/src/agentio.rs, neqo-crypto/src/constants.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/tracking.rs
This moves the handshake stuff into crypto.rs.
I also added a proper constant for the content type, which we had fixed
to a literal 22 in a few places.
I removed the generic implementation of `Into<Epoch>` from PNSpace as that was very specific to the way that we are using this.  That is now part of the handshake method in crypto.rs.
=> Factor more of the crypto handshake

neqo-http3/src/client_events.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/response_stream.rs, neqo-http3/src/transaction_client.rs
=> A transaction should try to read the next frame when it is done reading a data frame

neqo-transport/src/recovery.rs
This changes the code to use filter_map and map in a different order to
reduce the amount of line noise.  It's slightly less clear, but a lot
less weird.
=> Invert map and filter_map usage

neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/lib.rs, neqo-transport/src/lib.rs
Ensure GOAWAY frame stream_id is not increasing
the stream_id must be a bidi client-initiated stream
=> Enforce a correct stream id in a GOAWAY frame

neqo-crypto/src/secrets.rs, neqo-transport/src/server.rs, neqo-transport/tests/server.rs
At the server we would previously create multiple connections as new packets that were maybe Initial packets arrive.
Closes #540.
=> Only make one connection at a time

neqo-transport/src/connection.rs, neqo-transport/src/tracking.rs
This maintains the spec-defined "ACK every 2 packets" behavior but
changes the code so that waiting longer is more easily done, by changing
a const rather than code changes.
Updated some tests to allow for MAX_UNACKED_PKTS > 1 but still some
spots remaining. Since this commit doesn't actually break these other spots
then it's premature to fix those.
Remove pub from ACK_DELAY, doesn't seem to be needed.
=> Prepare for sending less frequent ACKs

neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/transaction_client.rs, neqo-http3/src/transaction_server.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/encoder_instructions.rs, neqo-qpack/src/lib.rs, neqo-qpack/src/table.rs, neqo-transport/src/connection.rs
Do not add new elemwnts to the dynamic table if instructions cannot be written into the encoder stream.
=> Write encoder instruction directly into a transport stream

neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs
In testing with Google's implementation, I found that they were not
sending any of the usual frames that allow us to clear the PTO timer.
Mostly this was ACK, but it also included HANDSHAKE_DONE.  We still got
packets though and those cause us to get into a bind.
What happened was that we set the delayed ACK timer, which eventually
expired.  But we would not send any packets when that expired because we
had exhausted our budget of PTO packets.  The result was that we were
not sending an ACK and clearing the delayed ACK timer, so that timer
remained set in the past.
We would subsequently report a negative delay, which was clamped to
zero.  The calling code then crashed trying to set a zero-delay timeout
on the socket.
Allowing ACKs to be sent after a PTO has fired avoids the problem.
This …
=> Allow ACK after PTO

neqo-common/src/codec.rs, neqo-transport/src/frame.rs, neqo-transport/src/tparams.rs
Enforce maximum values for stream offsets and stream ID limits
As requested in #546, to make the implementation better comply with the protocol.
=> Enforce maximum values for stream offsets and stream ID limits

neqo-http3/src/connection_client.rs, neqo-transport/src/connection.rs
This turns the close() function into a template so that we can accept
owned strings.  This doesn't change usage at all.
From #558.
=> Allow passing of String to close()

neqo-client/src/main.rs, neqo-server/src/main.rs
* neqo-client: Fix logic in HandlerOld::handle() 
* neqo-server: Update ALPN for 0.9 server
=> HTTP 0.9 fixes

neqo-transport/src/cc.rs, neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
When we are dropping keys, we don't need to keep tracking ACKs for the
same packet number space, so drop all state entirely.
I don't know, but I think that this pattern works reasonably well.  We
might be able to use this pattern more broadly.
I need to test this, but it would be good to get feedback.
Closes #513.
This is incremental on #583, so it will appear to have all those changes.
=> Drop ack ranges

neqo-qpack/src/decoder.rs, neqo-qpack/src/decoder_instructions.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/encoder_instructions.rs, neqo-qpack/src/header_block.rs, neqo-qpack/src/huffman.rs, neqo-qpack/src/lib.rs, neqo-qpack/src/reader.rs
- make more desctriptive errors
- Encoder and Decoder will map internal errors to appropriate spec errors
- other structures, e.g. encoder_instruction, decoder_instruction, header_block will return internal, more descriptive errors,
- return Error::NeedMoreData instead of None in some cases to make the code easier
=> Refactor qpack errors:

neqo-client/Cargo.toml, neqo-client/src/main.rs, neqo-http3-server/Cargo.toml, neqo-http3-server/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/server.rs, neqo-interop/Cargo.toml, neqo-interop/src/main.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/lib.rs, test-fixture/Cargo.toml, test-fixture/src/lib.rs
Currently we were using the any size a peer was returning in the SETTINGS_QPACK_MAX_TABLE_CAPACITY.
=> Add an encoder's max_table_size.

neqo-transport/src/send_stream.rs
Sorry I should've noticed this in the review but I didn't.
=> trivial: SendStream::send_internal() does not need to be pub

neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs
This should fix the problems that we are seeing in interop testing.
Getting this test right was quite difficult, but I think that this is robust.
Fixes #621.
=> Ignore kept lost packets

neqo-transport/src/connection.rs, neqo-transport/src/tracking.rs
There are cases where we set ACK delays for higher packet number spaces,
but we are unable to send ACKs when that time passes.  This hack ensures
that we never report an ACK time in the past when that happens.
This is limited to when we have more than one PN space as that is the
only time where we might encounter this issue.
This should remove one more case of where our timeout is clamped to zero (or now: where we end up with a time in the past).
Closes #620.
=> Ignore negative ack delay

neqo-transport/src/recovery.rs
It turns out that it is easier not having this.
In testing this, I realized that the test was busted, so I un-busted it.  So this isn't entirely red.  Sorry.  At least we don't have a no-op test case any more.
=> Remove enable_loss_detection_timer boolean

neqo-crypto/tests/agent.rs
Not sure why this didn't happen before now.
See https://app.circleci.com/pipelines/github/mozilla/neqo/1711/workflows/881ef5cc-8e15-47a9-8ce0-510d6246d7e7/jobs/1705/steps
=> Make sure to initialize the fixture

neqo-http3/src/connection.rs, neqo-http3/src/connection_server.rs
... and use it more consistently.
This should avoid problems where something happens and the state is
wrong.
I also removed a bunch of assertions that were wrong for the server when
it accepts 0-RTT.  A server is "Initializing" when it receives new
streams.  We can rely on the transport enforcing the rules for this.
If we were building a fully-fledged server, we might be more concerned
about the potential to serve content prior to handshake completion
(doing the whole idempotency check and whatnot) but I will just create
an issue for that rather than try to fix it here.
=> Create an active method on Http3State

neqo-transport/src/cc.rs
Instead of tracking largest acked sent time, track oldest lost packet
time. Compare against most recent lost packet
fixes #585
=> Proposed fix to #585

neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
In #647 I discovered that we generate probes when probes go missing.
The problem was that we were setting a PTO timer if there were
ack-eliciting packets outstanding.  What we should have been doing was
sending probes only if the congestion controller considers them to be in
flight.  The difference is subtle, but it means that PTO packets don't
count as being in flight.
This changes a few names.  I'm happier with the names, because they are
much less of a mouthful, but I think that they could be improved
further.  Suggestions for improvements are very welcome.
Closes #647.
=> Probes don't cause more probes

neqo-client/src/main.rs, neqo-common/src/log.rs, neqo-common/src/qlog.rs, neqo-crypto/src/agent.rs, neqo-http3-server/src/main.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/lib.rs, neqo-http3/src/response_stream.rs, neqo-http3/src/transaction_client.rs, neqo-http3/src/transaction_server.rs, neqo-interop/src/main.rs, neqo-server/src/main.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/lib.rs, neqo-transport/src/recv_stream.rs
I've been looking into bug [1611990](https://bugzilla.mozilla.org/show_bug.cgi?id=1611990) but there doesn't seem to be an easy way to make all logging happen regardless if `release_max_level_info` is set.
Instead, it seems we can replace the [log!](https://github.com/rust-lang/log/blob/4fb398b68ea43f5317e6e0f04b5eacaa9e679218/src/macros.rs#L34) logging macro with do_log! that does pretty much the same but does not respect `STATIC_MAX_LEVEL`
=> Add new macro that logs in all circumstances

neqo-crypto/src/agent.rs
The 'as' operator should be outlawed for anything but imports.
=> Use 'as' less often

neqo-transport/src/connection.rs
This patches over the assertion, essentially allowing us to mark something as closing.  I don't know if this is the best strategy, but it does stop a crash that is fairly reproducible from the server end.
The alternative is to try to find why things are attempting to set a closing state after going to closed.  If you think that is better, then I'm OK with deferring this and doing the analysis.  I'm just recording what I did to remove a road block.
=> Reduce strictness of assertions while closing

neqo-crypto/build.rs
Using `#[serde(default)]` avoids some of the extra unwrapping and
simplifies the code considerably.
=> Use less wrapping in build.rs

neqo-transport/src/cid.rs
as_ref implies AsRef, which was not really the case.
=> Implement AsRef for ConnectionId properly

neqo-transport/src/connection.rs, neqo-transport/src/stats.rs
Add a method to `Stats` that increments dropped_rx and prints a message, instead of
incrementing at each drop site.
We really need this to be a method on Stats rather than Connection to
avoid borrowck hell, but we also really want Connection's Display in the
log message. Can't pass it in b/c borrowck. Instead, capture it in
Connection::new().
=> Centralize logging of dropped received packets

neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/recovery.rs, neqo-transport/src/stream_id.rs, neqo-transport/src/tracking.rs
We clone these enough times to make sharing the memory worth the
overhead of the reference count.
Closes #622.
=> Use a reference-counted store of recovery tokens

neqo-transport/src/flow_mgr.rs, neqo-transport/src/recv_stream.rs
If a packet is lost, always requeue the flow control update for sending.
fixes #720
=> Fix issue with packet containing MAX_STREAM_DATA being lost

neqo-transport/src/server.rs
This uses `Weak` rather than `Rc` because the loop was holding
connections open.
In other news, Rust doesn't fix memory leaks arising from thoughtless
use of Rc.
Closes #523.
=> Remove reference cycle in server

neqo-client/src/main.rs, neqo-common/src/lib.rs, neqo-crypto/src/agent.rs, neqo-http3/src/client_events.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-http3/src/server_connection_events.rs, neqo-http3/tests/httpconn.rs, neqo-interop/src/main.rs, neqo-qpack/src/encoder_instructions.rs, neqo-transport/src/cid.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/events.rs, neqo-transport/src/frame.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/server.rs, neqo-transport/src/tparams.rs, neqo-transport/tests/server.rs, test-fixture/src/lib.rs
Well I need to place a paper bag on my head in shame over this, but moving Neqo to 1.43 was based on Firefox moving to at least that version, and they have not. Firefox's minimum rustc version is still 1.41.
Note to self: A commit in mozilla-central that the builders have updated to 1.43 does not mean the minimum rustc version has been changed. For this the authoritative value is `rustc_min_version` in build/moz.configure/rust.configure.
Clearly I'm enthusiastic about using `std::matches`, so once Firefox ACTUALLY moves to 1.42+ then we can rebase and apply #728. Hopefully it won't be too long from now, but who can say.
Reverts mozilla/neqo#728
=> Revert "use std::matches"

neqo-transport/src/connection.rs, neqo-transport/src/packet/mod.rs, neqo-transport/tests/server.rs
fixes #675
This also add test server_receive_unknow_first_packet which was crashing when trying to get timers (I have accidentally made a wrong test that revealed the issue)
=> Ignore VersionNegotiation containing reserved values and the value of the used QUIC version

neqo-client/src/main.rs
This will fix http3 test on interop runner
=> neqo-client: Use h3-29 by default

neqo-http3/src/connection_client.rs, neqo-http3/src/hframe.rs, neqo-http3/src/server.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-transport/src/connection.rs
Added must_use annotation to process.
Issue : #721
=> Added must_use annotation to process

neqo-transport/src/flow_mgr.rs, neqo-transport/src/recv_stream.rs
When invoked from FlowMgr::lost(), we can't borrow FlowMgr in RecvStream
because FlowMgr is already borrowed, and doing so causes a panic.
=> Avoid borrowing FlowMgr twice when handling lost MaxStreamData token

neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/server.rs, neqo-transport/src/connection.rs, neqo-transport/src/events.rs
ConnectionEvent::NewStream should use StreamId
Issue : #717
=> ConnectionEvent::NewStream now using StreamId

neqo-transport/src/connection.rs
I think that the original reason that the lint suppression was added was for a different reason, but it was since replaced by a new violation of the lint.  It wasn't so hard to remove it completely.
=> Remove useless let-if sequence

neqo-transport/src/connection.rs
Generate a MaxStreamData frame if we receive a StreamDataBlocked frame.
We should now send MaxStreamData when either a packet with MaxStreamData is lost (#726) or if we receive StreamDataBlocked (this PR).
=> Properly handle receipt of StreamDataBlocked frame

neqo-client/src/main.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet/mod.rs
Mainly this was so that I could construct a sample ChaCha20 header
protection example for the spec, but I think that this is cleaner
overall, and more usable.
There are some improvements to the neqo-client interface as well.
=> Factor some of the ChaCha20 stuff

neqo-http3/src/connection_client.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/events.rs, neqo-transport/src/lib.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/stream_id.rs
In order to test this, I had to add support for the server sending prior
to the handshake completing.  The nice thing is that we can use
availability of transport parameters to drive this.  If we have them,
then the server will be able to send.
There is a change in the HTTP code that bothers me a little.  There is a
new event being generated.  I don't understand why that event wasn't
being produced before.
Closes #714.
=> Save packets for which we don't have keys for later

neqo-qpack/src/header_block.rs, neqo-transport/src/recovery.rs
The use of .deref() is subject to a new lint in 1.44.  So I tweaked the
tests here.  Using slices rather than arrays seems better for
maintenance.
The and_then is also a new lint.
=> Fix some more lints

neqo-client/src/main.rs
When QNS image is checked for compliance no URL is passed to the binary.
=> neqo-client: fix QNS compliance check

neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/send_message.rs
- Set Http3Connection to the ZeroRtt state only after the initialization is done, because the initialization may fail.
- Ignore InvalidStreamId error from the transport when trying to close a stream.
- If decoding settings in set_resumption_token fails map error to InvalidResumptionToken
=> Small changes:

neqo-common/src/qlog.rs, neqo-http3/Cargo.toml, neqo-http3/src/lib.rs, neqo-http3/src/qlog.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/qlog.rs, neqo-transport/src/cc.rs, neqo-transport/src/connection.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/qlog.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
More interesting values, such as from congestion control and recovery.
The early commits in this PR stick with allowing qlog tracing functions to return `Res`, but this is converted later to handling qlog errors internally (response: emit a logmessage and close the log) rather than imposing error-handling on calling functions.
One burden calling functions *do* have to bear is ensuring the `NeqoQlog` is in scope. It's refcounted so that helps, but it does require a couple additional `set_qlog` methods.
=> Implement more qlog traces: CC and Recovery state

neqo-client/src/main.rs, neqo-transport/src/server.rs
For client, append dcid to qlog filename for uniqueness.
For server, open qlog file ensuing it does not overwrite an existing log file.
=> Qlog filenames

neqo-client/src/main.rs, neqo-common/src/qlog.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/qlog.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/qlog.rs, neqo-transport/src/cc.rs, neqo-transport/src/connection.rs, neqo-transport/src/qlog.rs, neqo-transport/src/recovery.rs, neqo-transport/src/server.rs
Move handling of refcounting and enabled/disabled inside NeqoQlog struct.
Add add_event() and add_event_with_stream() methods to NeqoQlog that
handles enabled/disabled check, as well as disabling logging if an error
occurs.
add_event() is simpler and more commonly used. If enabled, the closure
is called, and may add 0 or 1 events. add_event_with_stream() is used when
a probe may need to add more than one event, or add frames to the event.
fixes #771
=> qlog: Refactor

neqo-http3/src/connection.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/lib.rs, neqo-qpack/src/table.rs
Probably this is all that is needed for #655
=> The qpack encoder should write all instructions directly into a transport stream

neqo-http3/src/connection_client.rs, neqo-transport/src/connection.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
Increase transport send & recv bufs from 64K to 1M. Most of this PR is updating tests in http3 and transport to not depend on buffers being a certain size.
=> Large transport bufs

neqo-http3/src/hframe.rs, neqo-http3/src/lib.rs, neqo-http3/src/recv_message.rs
Executing read_response_data may return errors that are fatal and will terminate a HTTP3 connection and errors that only mean that the stream has been closed and the application is still not aware of the situation or the application has used a wrong stream id.
An application read HTTP3 connection events to find out if a stream has been closed, therefore if the application has not read all events it may happen that a stream is closed, but the application is not aware of it.
Also HTTP3  connection needs to read transport events to find out that transport streams are closed. This is done in the function process_output, therefore it may happen that an application calls read_response_data and gets a TransportStreamDoesNotExist if process_output has not called when it has needed to be called. …
=> Fix error handling in read_response_data

neqo-http3-server/src/main.rs, neqo-qns/Dockerfile, neqo-qns/run_endpoint.sh
server qns-mode hardcodes /www as the directory to serve files from.
Also, change neqo-http3-server alpn default to h3-29.
This doesn't quite fix #676 because it's not the right test, but it's s start. To get other transfer tests working we will probably want to do what we did with client -- merge H/0.9 and H/3 into one program -- rather than maintaining them separately. `neqo-http3-server` is in a lot better shape than `neqo-server`, which is "World's dumbest HTTP 0.9 server".
=> QNS: Support server for http3 test

neqo-http3/src/connection_client.rs, neqo-transport/src/connection.rs, neqo-transport/src/lib.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
Followup to #806, this is simpler than const methods on Connection.
Note that while we can change these constants now, setting them to
different values will cause some tests to fail. Spending time to fix
tests for different const values is not justified yet.
=> Export constants for send and recv buffer sizes

neqo-http3-server/Cargo.toml, neqo-http3-server/src/main.rs, neqo-http3-server/src/old_https.rs
For qns mode, we need to support HTTP/0.9. Instead of adding qns mode to
http server, I added H/0.9 to http3-server, since it already supports
transport::Server, and has a more developed event loop.
Add a 'HttpServer' trait that is implemented by Http3Server and
Http09Server.
Implement Http09Server. Add a DenyZeroRttChecker since Server requires one
be passed in.
=> QNS server: Support test cases requiring HTTP 0.9

neqo-crypto/src/agent.rs, neqo-transport/src/connection.rs, neqo-transport/src/crypto.rs, neqo-transport/src/recovery.rs, neqo-transport/src/send_stream.rs
There are two main changes here:
1. Keep the PTO timer armed for the Initial and Handshake packet number spaces.
This is based on the spec, which says that clients need to keep these armed, even if they haven't sent anything that is "in flight".  Doing this avoids a handshake deadlock when the server hasn't got its own PTO timer armed.  The server can't arm the PTO timer when it hasn't validated the client's address.
Note that we don't implement the anti-amplification limit, so our server doesn't really do this.  It arms the PTO timer when it shouldn't and ignores limits.  This is something we might need to fix eventually.
The other limitation here is that the PTO is armed past the point where it should be.  The spec says that the client can stop after the server has acknowledged …
=> Handshake recovery fixes

neqo-http3-server/src/old_https.rs
Remember number of bytes already sent to the client.
=> http3-server: Fix transfer test

neqo-transport/src/cc.rs, neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
This improves tracking of in-flight packets.  Most importantly, it
removes the distinction we were using for PTO packets that was flat-out
incorrect (my bad).
In addition to that, there are several other tweaks.
1. Remove SentPacket::cc_in_flight()
2. Allow in flight bytes to exceed the congestion window.  The only
change here is to remove a debug assertion; once we started counting PTO
packets properly, this was the only other thing that was standing in the
way of this accounting being better.
3. Change the way we probe so that we don't probe spaces that don't
require a PTO.  Part of the reason we had infinite loops in the past is
that we were sending a PING in ApplicationData without needing to.  This
is achieved by recording which spaces have an active PTO timer when
processing the PTO …
=> Better tracking

hooks/pre-commit
This has been bugging me for a while now.  This is much nicer...
```
$ git commit -m test neqo-crypto/tests/ext.rs
Formatting errors found.
Run `cargo fmt` to fix the following files:
/home/martin/code/neqo/neqo-crypto/tests/ext.rs
$ echo $?
1
```
=> Improve the feedback from the pre-commit hook

neqo-transport/src/connection.rs, neqo-transport/src/qlog.rs
qlog-defined connection states don't line up perfectly with Neqo's states,
but this is still useful information to log.
=> Add qlog::connection_state_updated

neqo-transport/src/recovery.rs
See recovery 6.2.2.1, the client needs to keep sending packets until it
receives HandshakeDone, even if all previous PTOs are acked and
in_flight_outstanding drops to zero.
=> Do not disable PTO when packets outstanding == 0 for initial/handshake

neqo-transport/src/recv_stream.rs
I discovered a bug in testing that was hard to reproduce otherwise.
The existing tests that would have caught this used a buffer of the same
length as the one that it overlapped with, hiding the error.
Rather than try to fix just that test case, I added a bunch of new
tests.  This probably overdoes it by quite a bit, but I would rather
have that than miss an error.
Closes #866.
=> More complete testing of RxStreamOrderer

neqo-transport/src/connection.rs, neqo-transport/src/frame.rs, neqo-transport/src/qlog.rs, neqo-transport/src/recovery.rs
This improves performance by an absurd amount.  Transferring 100M with this implementation of ACK processing takes 2.3s (approximately) of wall clock time on my old machine.  Before the change it took 15.7s.
The flamegraphs show this clearly as well.
Before:
After:
Clearly we have a way to go before our performance is *good*, but this should help a lot.
=> Faster ACK processing

neqo-transport/Cargo.toml, neqo-transport/src/send_stream.rs
Iteration order of streams is stable, in order added. Since we iterate
streams to find unsent data ranges, this will result in older streams
being queried for data before newer ones.
fixes #860
=> Use indexmap instead of HashMap for send streams

neqo-http3-server/src/main.rs
The default granularity is 100ms.
=> Set granularity of the server timer to 1ms.

neqo-client/src/main.rs, neqo-http3/src/connection_client.rs, neqo-transport/src/connection.rs
It's useful to have a tag that lets connections to the same host be
told apart. ODCID seems good for this purpose.
Make this available from Connection (as Option, because may not be set
for Role::Server) and Http3Client, where we know it must be set.
Change neqo-client to use new API rather than reaching into Connection
to get Path.
=> Add APIs to get odcid to Connection and Http3Client

neqo-transport/src/connection.rs
builder.len() includes any previous packets' lengths as well. Instead,
just record the length from the start of the header.
=> qlog: Fix packet length calculation

neqo-qns/run_endpoint.sh
This might help with simulation setup.  ngtcp2 in particular fails
consistently, and the main difference I can see is that those that don't
fail include wait-for-it in their endpoint script.
This also cleans up quoting for arguments.
=> Use wait-for-it

neqo-http3-server/src/old_https.rs
* A struct was named ConnState when it really should be named StreamState
* Look at result of `stream_recv` to handle reads that return no data
=> Fix server-0.9 issues

neqo-qns/run_endpoint.sh
We're seeing "connection refused" errors. wait-for-it doesn't seem to ever
be waiting.
We need to re-add the sleep for now.
=> QNS client: Re-add sleep to client runs

neqo-transport/src/tracking.rs
We attempt to merge ACK ranges in one case that was unnecessary.
Remove that by extending the interface.
When merging, remove the largest ACK range rather than the next one.  On
the assumption that most cases where we fill gaps are near the most
recent packet, this will result in dropping the head of the list rather
than a range in the middle of the list.
Finally, simplify the logic that determines whether this is the largest
acknowledged.
=> Factoring of ACK tracking

neqo-http3-server/src/old_https.rs
We are queueing up data to send but it's not being sent because the
connection has fallen off the active connection queue in Server, and so
never gets polled for packets.
Testing locally, this gets us passing QNS M as server for all except 2
clients (ngtcp2 and mvfst), so is a step towards resolving #911.
=> Add connection to active connection list when data sent

neqo-http3-server/src/main.rs
We set the poll timoeut to 0ms if there are active connection that needs to be processed. In such a case when poll returns back we may not have any socket or timer events, but we should still call process_active_conns. process_active_conss was accidentally put in a wrong place, it should be outside the for loop.
Fixes #912
=> Call process_active_conns even if there is no socket or timer events

neqo-http3/src/connection_client.rs, neqo-qpack/src/decoder.rs
We should not enter the same stream multiple times into the the block list. The check was wrong it should have checked whether the stream is in the list and not whether streams with id <= streamId are in the list.
=> Wrong check, we should check if a stream is already in he blocked list not if any stream <= streamId is in he list

neqo-transport/src/cc.rs, neqo-transport/src/connection.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
This avoids starting persistent congestion prior to having an RTT
sample and adds more tests.
Closes #831.
=> More fixes for persistent congestion

neqo-transport/src/connection.rs
Using the pointer seems to result in the same value from being used multiple times as the same memory location appears to be reused for holding different connections, so let's avoid doing that for connections at least.
=> Display the connection ID in logs

neqo-transport/src/recv_stream.rs
I originally just did this so that #944 could have a test case, but I then saw the inefficient code and decided to take a swing at that too.
This cleans up the code a little and makes the removal of ranges more efficient (using `BTreeMap::split_off` rather than iterative `BTreeMap::remove`).
It turns out that the extra break added in #944 isn't necessary for correctness, but it saves on doing a zero-length copy, so I've left it in (but moved it).  New tests ensure that this code path is exercised in tests.
Closes #944.
=> Read buffer

neqo-http3/src/connection_client.rs, neqo-qpack/src/encoder.rs
Currently it may happen that a capacity change is executed during encoding of a header block. The capacity will be changed by calling send(). If capacity changes some parameters like max_entries change as well and Encoder and HeaderEncoder are out of sync. Therefore call send() before starting to encode a header.
=> Change capacity if possible before starting to encode a header block.

neqo-client/src/main.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/recv_message.rs
...when reading from the stream.  We suppress these otherwise, but not
if the DATA frame ends up being the last one.  Normally, this isn't an
issue as more data usually can't be read into the buffer when we don't
know how much we need, but this doesn't always happen and that leads to
extra events being left around after we told the calling code that the
stream was done.
Closes #968.
=> Suppress DataReadable events from end of stream

neqo-common/src/codec.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/hframe.rs
This isn't something I'm using right now, but I thought that I needed it
at one point.  It is fairly simple to add and doesn't cost that much.
It might help innoculate implementations against being too rigid.  Note
that I specifically did not add any parsing capability to HFrame::Grease
so that we use the usual extension handling to deal with what will
appear to be an unknown frame.
=> Add grease frame type

neqo-server/src/main.rs, neqo-server/src/old_https.rs
This might help with passing a few more QNS tests.
Haven't tested this, but it seems useful enough to just try it out.
=> Send a session ticket when doing HTTP/0.9

neqo-transport/src/cc.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/cc.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/qlog.rs, neqo-transport/src/recovery.rs, neqo-transport/src/tracking.rs
This uses the PTO send profile and probes in every active packet number space immediately after entering recovery.  This is intended to ensure that we exit recovery as quickly as possible as an acknowledgment for this packet will cause an exit to recovery.
This factors some of the recovery code to add an explicit state rather than add another flag.  I realized that the recovery start time couldn't be eliminated after running some tests, but I tried to clean that up to.
I exploited the extra flag to remove an argument from a function.
In debugging this, I realized that some of our existing tests were unrealistic.  So I tweaked those a little, mostly just to add an RTT. Those changes can be considered separately.
In terms of performance, in the worst case, this might improve things a bit. …
=> Send a packet on entering recovery

neqo-transport/src/crypto.rs
This was nasty.  Each set of application data read/write keys holds a
secret.  This is not the secret that is currently in use (secret N,
which is thrown away), but the next one (secret N+1).  When we update,
we should use that secret (N+1) and then create the next one after that
(secret N+2).
We were using secret N+2 and keeping it too.  That meant that we were
effectively skipping the second set of secrets (those for the first
switch to key phase 1) entirely.
Simple fix, but impossible to test without interoperating with other
implementations.  Which I have now done.
Closes #979.
=> Don't skip secrets on key update

neqo-client/src/main.rs, neqo-transport/src/addr_valid.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/resumption.rs, neqo-transport/src/crypto.rs
This makes two changes:
1. NEW_TOKEN is deduplicated better.  A few old tokens are remembered even after they are used so that we don't take two by accident.
2. A take_resumption_token method is added to Connection so that we fail
our resumption tests less often.  Right now, we don't even get
self-interop on resumption or 0-RTT because we don't give ourselves a
chance to exchange NEW_TOKEN.  This way, at least we use the session
ticket even if NEW_TOKEN doesn't get through.
Closes #984.
=> Resumption improvements

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/send_stream.rs
Andy's original comment:
Currently, the client can have open streams exceeding MAX_STREAMS
because we give them more streams credit when the recv stream is
complete rather than when both the send and recv stream are complete.
Clear up terminal send streams first. Then, only remove bidi recv
streams if send stream is not present.
This keeps the recv stream hanging around longer than strictly necessary
but I think this is more straightforward than logic to remove it, and
then increase max_stream_bidi when the send stream is cleaned up.
My additions:
I wrote a different test for this, and I'm really glad that I did.  It
turned up a different bug.  If SendStream received an ACK for the end of
a stream before it received an ACK for all the data, it would not
consider the stream to be …
=> Cleanup streams before granting stream credit

neqo-http3/src/server.rs, neqo-server/src/main.rs, neqo-server/src/old_https.rs, neqo-transport/src/server.rs
Right now, we support chacha20, but the QNS tests don't know that.  They
assumed that every server would support it.  But mvfst spoiled it for
everyone by not supporting it.  So we need to have explicit support for
this test on the server side.
Is it worth moving the duplicated code to neqo-crypto?  A `TryFrom<AsRef<str>>` implementation on Cipher isn't crazy.  That could be integrated into the macro definition.  That might be a tiny bit more work than is ideal though.  Maybe a separate issue once this lands.
=> Support the new chacha20 test for the server

neqo-client/src/main.rs, neqo-common/src/event.rs, neqo-common/src/lib.rs, neqo-http3/src/client_events.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/server.rs, neqo-http3/tests/httpconn.rs, neqo-interop/src/main.rs, neqo-server/src/old_https.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/connection/tests/zerortt.rs, neqo-transport/src/events.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/server.rs, neqo-transport/tests/server.rs, neqo-transport/tests/sim/connection.rs, test-fixture/src/lib.rs
This doesn't really reduce code size much, but it unifies the interface
somewhat.  It also makes the iterator cleaner for those cases where it
is used.  As it now takes a mutable borrow, it is also safer to use.
Previously, the events that were retrieved could be out of date.
I did run into #973 when working on this.  `Iterator::any` stops when it
hits the first success and there were multiple DataReadable events
queued.  I've flagged that in the code.  It should be easy to fix up
when it comes time (what is hard is getting the function signatures
right; `Iterator::any` takes a value, `Iterator::filter` takes a
reference.
Closes #934.
=> Use a generic event provider

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/vn.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/qlog.rs, neqo-transport/tests/server.rs
Right now, we accept a version negotiation if the destination connection
ID doesn't match or after receiving a Retry packet.  That isn't good.
This is built on top of #991 because I touched the same code (I only noticed the bug because I touched the code).  Just look at the last commit to understand this one.  I can backport it, but it shouldn't make a difference.
=> Better version negotiation filtering 

neqo-http3/src/hframe.rs
The code has been refactor so the clippy instruction is not needed anymore.
Fixes #564
=> Remove unnecessary clippy instruction

neqo-common/src/codec.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/tracking.rs
Rather than return `Frame::Ack` give the received packet tracker access to the write buffer and have it write directly.
This is step 1 of my plan to ensure that we send a PING occasionally alongside ACK.
It is also step 1 of a possible plan to avoid copying buffers when sending STREAM and CRYPTO frames.  A good potential alternative there is to change `Frame` so that it borrows rather than owns data, though that has the drawback that we can't represent the potentially fractured data we hold in our stream buffers (`VecDeque` can return two slices as data rolls around its circular buffer).
I don't know which of those follows on from this next.
=> Write ACK frames directly

neqo-transport/src/frame.rs
The original implementation of this had more complicated logic, but the
spec has since gotten cleaner.  So the code can be too.
=> Use match for `Frame::is_allowed`

neqo-common/Cargo.toml
This way, we have one fewer version to deal with.  This is the later of
the two versions we already have to pull in.  It won't fix gecko (which
has lots of use of 0.6.2), but we can help out.
=> Update env_logger dependency

neqo-transport/src/cid.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs
This also means that we save padding less often, which is a good thing.
=> Enforce same DCID rule

neqo-common/src/codec.rs, neqo-common/src/lib.rs, neqo-transport/src/addr_valid.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/state.rs, neqo-transport/src/connection/tests/cc.rs, neqo-transport/src/connection/tests/close.rs, neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/crypto.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/stats.rs, neqo-transport/src/tracking.rs
This is built on #1010....  It's just one commit extra, albeit a big one.  Look at the last one.
Mostly.  I've kept the CONNECTION_CLOSE reason phrase owned.  Changing
this would mean hitting a whole different piece of code and this is
already too large.
The main effect here is on receive streams, which have to deal with
receiving slices rather than `Vec<u8>`.
There is another casualty of this change, which is
`Connection::test_process_input`.  I never liked that solution and this
validates that choice.  There was no way to preserve this as the frames
that would have been returned refer to the contents of the temporary
buffer we decrypt into.
To replace `Connection::test_process_input`, new stats have been added.
These record the number of frames that are sent, both in total and for
each …
=> Make Frame borrow for its buffers

neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs, neqo-transport/src/recv_stream.rs
This is two commits on top of #1011.
The first refactors `RxStreamReorderer::inbound_frame`.  When I touched that for #1011, I found it was too complicated.  It also had a couple of interesting flaws.
1. [This line](https://github.com/mozilla/neqo/blob/077a3b246d2fa6eb942d80ac9228be9478153b79/neqo-transport/src/recv_stream.rs#L148) should have been `>=`.  The effect was that we would save overlapping data.
2. [This double check](https://github.com/mozilla/neqo/blob/077a3b246d2fa6eb942d80ac9228be9478153b79/neqo-transport/src/recv_stream.rs#L74) only needed the comparison of the ends.  The comparison of starts just added lots of code.
3. [This removal](https://github.com/mozilla/neqo/blob/077a3b246d2fa6eb942d80ac9228be9478153b79/neqo-transport/src/recv_stream.rs#L135) never did anything …
=> Refactor RxStreamReorderer::inbound_frame

neqo-transport/src/send_stream.rs
Our current usage allocates a whole megabyte for every stream.  This
avoids additional allocations as new data is written to the stream, but
it is a grossly inefficient use of memory.  Most times we write much
less to streams.
VecDeque will start at 7 bytes and double its size as needed as new data
is read out.  If we manage to send in a single write, then it will
resize based on the size of new data.  Thus, the number of extra
allocations is likely to be small in most cases.  Lots of little writes
will cause this to allocate a few times, but we don't have many of
those, except where we really don't want to send very much.
This is intended to help with #923, but we should leave it open.  The true
cause of the OOM needs to be better understood.
=> Use a default VecDeque for SendStream

neqo-common/src/codec.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/packet/mod.rs
Padding server Initial packets turns out to be tricky.  This fixes that
problem by adding PADDING frames if padding is needed.
This partly retains the odd padding scheme that has caused so many
problems in other implementations.  It turns out that it is convenient
to only add PADDING frames to ApplicationData packets.  This means that
we will use PADDING frames for 0-RTT and 1-RTT packets if we have
determined that padding is needed.  We'll keep the quirky padding when
neither of those packets is being coalesced.
(This should also for padding PATH_CHALLENGE and PATH_RESPONSE when
those come along.)
Closes #1020.
=> Fix server Initial padding

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/saved.rs
This ensures that we don't jump into handling Handshake packets before
we have finished processing the current datagram.
This doesn't do much, but the moved assertion in start_handshake()
should highlight why this was not great.  Without the changes, that
assertion fails.
=> Defer processing of saved datagrams

neqo-crypto/build.rs
This always seems to evade detection.
=> Fix some clippy lints in build.rs

neqo-crypto/src/hp.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/recovery.rs
As we were debating the implementation of this in the spec, I decided
that it was worth doing in our implementation too.  In a lot of cases we
will waste fewer bytes this way.
This isn't ideal as it doesn't yet account for the potential for the
send rate to increase, but it's a pretty good algorithm, I think.
I've been extra cautious and I've adjusted for the header protection
sample size and the AEAD expansion, even though those are both 16
currently and this is in effect a no-op.
=> Encode packet numbers shorter

neqo-transport/src/connection/mod.rs, neqo-transport/tests/server.rs
When I started changing the connection ID generator for testing, it
caused this test to fail.  By breaking the datagram up, the test can be
better.
=> Enforce tighter bounds on CONNECTION_CLOSE packets

neqo-client/src/main.rs, neqo-server/src/main.rs, neqo-server/src/old_https.rs
These changes are what I found necessary to have the server and client
work with migration.  I've separated them out because they are largely
not dependent on the migration changes.
1. The client uses send_to and recv_from.  The client used to connect to
the server address, which meant that it couldn't migrate.  Now it
respects the destination address from the Datagram that is returned.
2. The same for the server.  The server is a little trickier in that it
has multiple sockets from which to send.
3. The server used to make an instance for each listening port.  This
was completely unnecessary and it complicated things considerably.
Now there is just a single server instance that manages all listening
ports.
4. The old HTTP server now buffers partial requests.  This was causing
0-RTT …
=> Fixes for neqo-client and neqo-server

neqo-http3/src/connection_client.rs, neqo-http3/src/lib.rs, neqo-http3/src/recv_message.rs
Fix #753 
Implement some checks against response headers.
1. Pseudo header fields shoud not after fields.
2. Contains no uppercase characters in field names.
3. Have undefined or excluded header.
=> Check header fields

neqo-http3/src/connection_client.rs, neqo-transport/src/connection/tests/close.rs
As Martin mentioned here [1], move this test to the proper place.
[1] https://github.com/mozilla/neqo/pull/1054#commitcomment-44961858
=> Move client_close_with_long_reason_string to neqo-transport tests

neqo-transport/src/tparams.rs
Add a test that checks for decoding failure when the ACTIVE_CONNECTION_ID_LIMIT is less than two.
=> Test tparam parsing to prevent bugs like #705 (#706)

neqo-common/src/codec.rs, neqo-crypto/src/prio.rs
I don't why I saw this, but we should be more rigorous with stuff that might be used in multiple places.  We already assert in encode_vvec_with.
=> Assert if encode_vec_with overflows

neqo-crypto/src/prio.rs, neqo-crypto/src/time.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/lib.rs, neqo-http3/src/push_controller.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/header_block.rs, neqo-qpack/src/lib.rs, neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/state.rs, neqo-transport/src/recovery.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tracking.rs
There was one here that was genuinely useful, but some of the others were just annoying.  The insistence on using `Option::map_or` made some of the code worse, so I suppressed it.  Also, qpack usage deliberately overwrites specific error codes with `Result::map_err`, which now generates warnings that - rather than suppressing directly - I created a wrapper function for.
=> Rust 1.48 clippy changes

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/params.rs, neqo-transport/src/lib.rs
I think that when you have connection_params and connection, that indicates that what you really want is connection::params.  This does that.  I also noticed that our type alias for TransportError isn't public, so I made it so.
=> Move connection parameters a little

neqo-transport/src/server.rs, neqo-transport/tests/server.rs
This is why our 0-RTT tests are failing in the interop runner.
Not critical, but it was bugging me that we were dropping most 0-RTT
packets.
=> Route 0-RTT based on AttemptKey

.circleci/config.yml, check_internal_errors, hooks/pre-commit, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/lib.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/lib.rs, neqo-transport/src/crypto.rs, neqo-transport/src/lib.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/packet/retry.rs
neqo-http3 events should use ConnectionError not Close error. This will give us more information in necko.
=> Split internal errors for debugging purposes.

neqo-http3/src/lib.rs, neqo-http3/src/server.rs, neqo-http3/src/server_events.rs
A server needs to remember streams between events.
=> ClientRequestStream needs to implemenat Hash

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/priority.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/crypto.rs, neqo-transport/src/send_stream.rs
This adds the ability to prioritize streams.
The most important aspect of this is that the default behaviour here
prioritizes retransmission over transmission.
This comes at a small cost: we iterate through all the active streams 5
times rather than just once.  I've tried to mitigate that by adding an
early exit: if we fill up the packet, we stop looking to add frames.
This isn't complete as it doesn't include any tests that verify that
prioritization works as expected.  And the HTTP fetch API needs priority
hooks too.
=> Sketch of priority API

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/fc.rs, neqo-transport/src/flow_mgr.rs, neqo-transport/src/frame.rs, neqo-transport/src/lib.rs, neqo-transport/src/recovery.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
This is the first step of my attempt to eliminate `FlowMgr`.  This creates a new flow control object for sending, which is used for `SendStream` and connection-level flow control.  That object sends `*_BLOCKED` frames more precisely, avoiding unnecessary retransmissions.  Previously, we would send these on multiple occasions especially when `send_atomic` was used; now we just send them when we hit a limit and only retransmit if that frame is lost *and the limit hasn't increased*.
I haven't used this new object for sending `STREAMS_BLOCKED` yet as that requires touching a different piece of code.  That change can come later.  This change is limited to the sending code.
The effect is that `STREAM_DATA_BLOCKED` is sent at the same priority as data on that stream.  
I've moved `RESET_STREAM` …
=> Move sending flow control tracking to send streams

check_internal_errors, neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet/mod.rs
This turns out to be fiddly.  What we really want to do is just abort if
you can't create the header.  But the packet builder takes ownership of
the underlying buffer, and those places where it doesn't have enough
space is where we want that buffer back again.  So, rather than use a
`Res` return and have the buffer lost, set the limit to 0 if there isn't
enough space.  This causes the `remaining()` function to return 0 also
(after tweaking it), so that the packet can't be built.
I've collapsed some of the internal errors here as well.  Now that we
have better confidence that these are not causing problems, we should be
able to rely on less precise targeting of those errors.  So this walks back
some of the changes in #1070.
Closes #1100.
Closes #1098.
Closes #1097.
=> Deal with failure to fit a packet header better

neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/push_controller.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/state.rs, neqo-transport/src/connection/tests/keys.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/crypto.rs, neqo-transport/src/frame.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/tests/server.rs, test-fixture/src/lib.rs
Rust 1.50 adds the ability to format the `matches!()` macro.  We should
take advantage of that.
=> Format `matches!()`

neqo-common/src/codec.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/hframe.rs, neqo-http3/src/push_controller.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-interop/src/main.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/header_block.rs, neqo-qpack/src/reader.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/state.rs, neqo-transport/src/connection/tests/cc.rs, neqo-transport/src/connection/tests/keys.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/priority.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/crypto.rs, neqo-transport/src/frame.rs, neqo-transport/src/path.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/tests/server.rs, test-fixture/src/lib.rs
These are one of three things:
1. Unnecessary else (after return/break on the main arm)
2. Unnecessary Result (when all returned values are Ok(T)
3. Non-binding assignment when the value implements Drop
None of these were tricky, just keeping new versions of Rust usable.
Note: built on #1104.
=> Clippy 1.50

neqo-common/src/codec.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/hframe.rs, neqo-http3/src/push_controller.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-interop/src/main.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/header_block.rs, neqo-qpack/src/reader.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/state.rs, neqo-transport/src/connection/tests/cc.rs, neqo-transport/src/connection/tests/keys.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/priority.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/crypto.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/tests/server.rs, test-fixture/src/lib.rs
The interfaces in Connection were starting to get a little wide and it
seemed like this was a good opportunity to narrow them a little.
This is part of a multi-step process.  I want to move the logic for
adding a PING frame to the class as well.  I'd like to track when we
last sent an ack-eliciting frame so that we can send a probe
occasionally when we are only acknowledging incoming data.
This changes logic slightly.  We will now pad *outside* 0-RTT packets
instead of inside.
Builds on the rust 1.50 cleanups in #1106.
=> Factor padding

neqo-common/Cargo.toml, neqo-common/build.rs, neqo-common/src/hrtime.rs, neqo-common/src/lib.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/recovery.rs, neqo-transport/src/server.rs
This is done automatically, with a little hysteresis to ensure that the
updates aren't performed too often.  Each connection updates its timer
resolution independently based on the timer values it reports
(currently, this is a quarter of the delay we determine) and that is
propagated to the thread level, where the relevant API for setting
timers are called.
I did a fair bit of digging here to learn how to do this.  There is some
contention about the value of the different APIs here, but the general
sense I get is that some people would prefer that timer resolution not
be increased unnecessarily.  This tries to avoid that, but in doing so
it might hit the various APIs more often than is ideal.
To reduce the number of potential system calls, there is a tiny amount
of hysteresis here: the …
=> Dynamic timer resolution increase

neqo-transport/src/connection/mod.rs, neqo-transport/src/tracking.rs
After cleaning up the way we track whether an ACK has been sent, now we
don't need to save the token that the ACK writer generates.  That
simplifies things quite a bit.
=> Cleanup ACK token stuff properly

neqo-common/src/hrtime.rs
- call to this function may fail if a system is busy and we do not want to assert on that
- computation and constraint parameter of thread_time_constraint_policy should be a fraction of time se for the period
=> Fix thread_time_constraint_policy:

neqo-qpack/src/encoder.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/params.rs, neqo-transport/src/connection/tests/zerortt.rs, neqo-transport/src/send_stream.rs
After accepting 0-RTT, the server might increase flow control limits on
streams.  We need to ensure that these limits are applied to open
streams.
As part of this, I had to change the API for setting initial flow
control limits as we only had controls for bidirectional streams in the
wrong direction for the test (a server could only limit the streams it
created).  The API is more complex as a result, but it now works.  Note
that the qpack encoder test is now more general as a result, though I
think that the bidirectional limits aren't really relevant to that test.
Closes #1119.
=> Update 0-RTT flow control limits

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/recovery.rs
I decided to make this marginally more complex, sending slightly earlier
if we have lots of outstanding packets.  The logic is now that we send a
PING after 1 PTO if there are either 200 packets outstanding or after 2
PTOs with at least 16 packets outstanding, otherwise no PING.
These numbers are arbitrary, except for the minimum of 1 PTO.  The goal
is to make the larger high enough to encourage good ACK sending from
even the fastest peers; and to make the smaller enough that bad ACK
sending from a very slow sender doesn't lead to us asking for ACK when
we don't really need it.  Either threshold could be much larger or
smaller as you like, though the smaller probably shouldn't be lower than
a reasonable ACK threshold.
Closes #830.
=> Send a PING with ACK occasionally

neqo-common/Cargo.toml, neqo-common/src/hrtime.rs
See https://bugzilla.mozilla.org/show_bug.cgi?id=1698438#c6.
The linker failed to link `timeBeginPeriod` and `timeEndPeriod` in win32 platforms. Switching to use `winapi` seems to fix this issue.
=> Use winapi for high resolution timer when using gecko

neqo-transport/src/fc.rs, neqo-transport/src/streams.rs
Rename max_data in ReceiverFlowControl to reflect other use-cases.
Remote limits do not need o be reinitialise after ZeroRtt has been rejected.
=> Small fixes

neqo-transport/src/ackrate.rs, neqo-transport/src/cid.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/test_internal.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/fc.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs
This is the implementation part.  I'm fairly sure that it's good, but I
haven't tested it.  And testing this promises to be tricky as there are
interactions with paths.  And we don't use Retire Prior To for our own
purposes.  It might be possible to do something invasive; I'll see what
I can come up with.
=> Implement NEW_CONNECTION_ID::retire_prior_to

neqo-transport/src/cc/cubic.rs, neqo-transport/src/cc/tests/cubic.rs
Saved packets are process with a timestamp that correspond to time they have been received. This may overflow the calculation of the time spent in ca.
=> Processing saved packet may overflow cubic cc

neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cc/cubic.rs
Now, this is papering over what might be a real issue in the code, but
it should at least stop the crashing.
Why anyone would have a congestion window that large is hard to imagine.
That is 8Pb of memory to just hold the outstanding data.
That points to a genuine bug somewhere in our calculations.  I took a
look and I haven't seen any case that is obvious.  Cubic will increase
the congestion window by up to 1300 times the base rate, but at most
2700 bytes of increase per new acknowledgment.  To reach 8Pb, we would
need to send trillions of bytes and receive trillions of fresh
acknowledgments.
=> Clamp cwnd values to 1<<53

neqo-transport/src/connection/saved.rs, neqo-transport/src/connection/tests/handshake.rs
Issue #1152
As per the issue I reduced the saved datagrams to 4. Also updated the reorder_1rrt() test accordingly.
=> Updated MAX_SAVED_DATAGRAMS from 32 to 4 #1152

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs
A simple check that I noticed when reviewing the ack-frequency doc.
=> Cross-validate min_ack_delay and max_ack_delay

neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/fc.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/stream_id.rs, neqo-transport/src/streams.rs
We set the flow control limit to the max possible and therefore we have not implemented actually calculating retired data.
This is fine with the limit set to max possible, but this is needed if we set it to something smaller.
This changes adds calculation of retired bytes.
Ensuring that the other side does not exceed the limit will be added in the follow up commit.
=> Use session flow control

neqo-crypto/src/agent.rs
Cargo doc previously failed with:
```rust
Checking neqo-transport v0.4.29 (/home/user/dev/neqo/neqo-transport)
error: unresolved link to `RFC7301`
--> neqo-crypto/src/agent.rs:489:22
|
489 |     /// Though ALPN [RFC7301] permits octet sequences, this only allows for UTF-8-encoded
|                      ^^^^^^^ no item named `RFC7301` in scope
|
note: the lint level is defined here
--> neqo-crypto/src/lib.rs:7:45
|
7   | #![cfg_attr(feature = "deny-warnings", deny(warnings))]
|                                             ^^^^^^^^
= note: `#[deny(rustdoc::broken_intra_doc_links)]` implied by `#[deny(warnings)]`
= help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
error: aborting due to previous error
error: could not document `neqo-crypto`
```
=> Fix missing link in documentation causing `cargo doc` to fail

neqo-transport/src/connection/mod.rs, neqo-transport/src/fc.rs, neqo-transport/src/recovery.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/streams.rs
In part, the reason we had issues with the keep-alive patch was that we
had `_ => panic!()` clauses in our `match` statements.  This patch moves
the stream-related pieces of the enum into a new structure.  This might
add an extra discriminator to the layout, but the overall effect is
otherwise minimal.  And we no longer have catch-all clauses in our match
statements.
=> Split stream-related recovery tokens out

neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs
If we get data on the decoder that unblocks some header decoding and one of the stream headers is malformed, neqo will reset a wrong stream(the decoder stream)
=> Resetting a wrong stream

docs/linux_build.md
When I followed Linux build document, I faced same problem as #1156.
The cause of this problem was `-u c7a1c91cd9be` which means to use `NSS_3_53_BETA1`.
=> Fixed Build NSS command on Linux build document

neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/control_stream_local.rs, neqo-http3/src/lib.rs, neqo-http3/src/push_stream.rs, neqo-http3/src/stream_type_reader.rs
This is extracted from my work on WebTransport and simplifies PushStream implementation. PushStream is not any more responsible for reading PushId and therefore it is transformed into a very simple wrapper around RecvMessage.
This PR also changes the behavior regarding closing a stream too early, e.g. if a stream is closed before the stream id is read it will return HttpStreamCreation.
=> Move decoding of PushId into NewStreamTypeReader

neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/push_stream.rs, neqo-http3/src/recv_message.rs
PR #1202 made PushStream a simpler wrapper around RecvMessage and that made possible to remove PropertyHandler rom PushStream
=> PushStream does not need to hold a PriorityHandler

neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/params.rs, neqo-transport/src/connection/tests/datagram.rs, neqo-transport/src/events.rs, neqo-transport/src/quic_datagrams.rs, neqo-transport/src/recovery.rs
Additional changes:
- The IncomingQuicDatagramDropped event is queued when a queued QuicDatagram event gets dropped due to the number of queued datagrams exceeding the limit. The limit is controlled by a connection parameter.
- The OutgoingQuicDatagramOutcome event is queued when the outcome of the outgoing of a QuicDatagram is known. It can be: lost, asked, dropped because the outgoing queue of datagrams is full(The limit is controlled by a connection parameter) or it can be dropped because it does not fit into a quic packet.
- Change name of some parameters and events from datagram/Datagram to quic_datagram/QuicDatagram for consistency. This does not apply to the QuicDatagram structure because the structure is about QuicDatagrams.
- Fix a bug: multiple Datagrams containing the same data …
=> Queue multiple outgoing Quic datagrams

neqo-transport/src/connection/tests/datagram.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/quic_datagrams.rs, neqo-transport/src/send_stream.rs
I started out just looking at the DATAGRAM frame, for which we need to
be careful in two ways: we need to ensure that the entire payload is
sent in one piece, and we need to ensure that when we using the packet
filling frame type, we don't follow the frame with other frames.
Then I looked at the STREAM frame and what we are doing was wasteful.
We were adding a length field just to fill the packet, even when we
could have used the packet filling option.  That was wasteful, because
the extra length field meant that we sent a larger packet than was
necessary.
This logic turns out to be a whole lot simpler.  And we save a byte or
two here and there.
The negative side of this is that those byte savings might make our
packets ever-so-slightly more vulnerable to traffic analysis.  And the
way …
=> Rework frames that fill packets

docker/Dockerfile
I've already pushed this for use in CI, but I wanted to get the code in place.  This is necessary to build NSS.
=> Add python3 to the docker image

neqo-client/src/main.rs, neqo-http3/Cargo.toml, neqo-http3/src/connection_client.rs, neqo-http3/src/lib.rs, neqo-http3/src/request_target.rs, neqo-http3/tests/httpconn.rs, neqo-http3/tests/priority.rs, neqo-interop/src/main.rs
This does a little generic magic in order to allow for three basic forms
of request target natively:
* A simple string (this is the most costly, because we have to parse the
URL)
* A Url (in case one exists, as is the case with neqo-client)
* A three-tuple of things that turn into `str`
More of these can be implemented if that turns out to be convenient for
the caller.  Monomorphism ensures that only those forms that are used
are paid for.
This was a little fiddly to implement.  I would have liked to make the
string form more generic, ideally `AsRef<str>` but because we take
`&Url` and because `Url` implements `AsRef<str>` that causes rust to get
confused.  I tried fixing it, but you end up needing extra type
parameters on every invocation, which is less friendly than just having
people …
=> Define and use RequestTarget for fetch

neqo-client/Cargo.toml, neqo-client/src/main.rs, neqo-http3/Cargo.toml
We do not need to have 2 versions of url crate in Firefox.
=> Use url version 2.0, that is what Firefox is already using.

neqo-http3/src/client_events.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/control_stream_remote.rs, neqo-http3/src/lib.rs, neqo-http3/src/push_controller.rs, neqo-http3/src/qpack_decoder_receiver.rs, neqo-http3/src/qpack_encoder_receiver.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-http3/src/server_connection_events.rs, neqo-http3/src/server_events.rs, neqo-http3/src/stream_type_reader.rs, neqo-http3/tests/priority.rs, neqo-server/src/main.rs
The stream closing events, e.g. application close, RESET frame, etc., will be used by WebTransport. This patch tries to cleanup that code so that it would be easier to extend it for WebTransport. ServerPush already uses the events trait, RecvStreamEvents, for the bookkeeping. For example, when a push stream is canceled or finished, the push stream listener that implements RecvStreamEvents, calls appropriate PushController functions to remove the information about the stream, etc. WebTransport will use the events in a similar way.
RecvStream’s function reset() and SendStream’s function stop_sending() now use CloseType. The two functions will be used to inform a stream that it is abruptly closed, either by application(CloseType::AppError), stream error (e.g. unallowed request …
=> Refactor stream closing events

neqo-crypto/src/cert.rs
Sometime  `sct_ptr` is not null, but `sct_ptr.data` is null. In this case, use `slice::from_raw_parts` is UB and violate [safety guarantee](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety) (In debug build, this will hit a `debug_assert` failure).
=> fix panic from slice::from_raw_parts

neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/lib.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-http3/src/server_events.rs, neqo-qpack/src/encoder.rs
There are to change sets.
1) encode_header_block does not need to return an error:
This will simplify SendMessage code. Any error during the encode_header_block call will be ignored and they will be picked up by the main loop, i.e. process() calls.
2) Encode headers when they are set:
The function encode_header_block does not produce any errors that need to be picked up by the main processing loop. This was change in the previous change set. Therefore the encoding can be performed immediately.
This PR will change current behavior regarding the order in which the encoder instructions and header blocks are sent.
=> SendMessage refactor

neqo-common/src/headers.rs, neqo-common/src/lib.rs, neqo-http3/Cargo.toml, neqo-http3/src/buffered_send_stream.rs, neqo-http3/src/client_events.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/lib.rs, neqo-http3/src/push_controller.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-http3/src/server_connection_events.rs, neqo-http3/src/server_events.rs, neqo-http3/tests/httpconn.rs, neqo-http3/tests/priority.rs, neqo-http3/tests/send_message.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/header_block.rs, neqo-server/src/main.rs
The biggest change is that SendMessage uses BufferedStream and does not need states. The header blocks are added using send_headers and they are buffered into the BufferedStream. There may be multiple header blocks, but the code does not enforce or check that only server can send multiple headers blocks or that the multiple 1xx header blocks are followed by a non-1xx header block. This is left for the application to enforce.
The server and client API are unified, both sides use send_header, send_data  and close_send functions.
=> Implement sending of 1xx responses and refactor SendMessage

neqo-common/src/headers.rs, neqo-http3/src/client_events.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/features/extended_connect/mod.rs, neqo-http3/src/features/extended_connect/session.rs, neqo-http3/src/features/mod.rs, neqo-http3/src/lib.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-http3/src/server_connection_events.rs, neqo-http3/src/server_events.rs, neqo-http3/tests/httpconn.rs, neqo-http3/tests/mod.rs, neqo-http3/tests/send_message.rs, neqo-http3/tests/webtransport/mod.rs, neqo-http3/tests/webtransport/negotiation.rs, neqo-http3/tests/webtransport/sessions.rs, neqo-server/src/main.rs
This PR creates a generic ExtendedConnectFeature structure that is responsible for a feature negotiation and keeps a HashMap of the extended connect requests. The HashMap will be used for finding active sessions.
An extended connect request will be created as a regular fetch request only the listener for the events will be different.  A generic ExtendedConnectSession structure is created for each extended connect request and is responsible for listening to request events and following the state of the request/session, e.g. the session is being negotiated, a stream is closed, etc..This structure will be responsible for bookkeeping, i.e. it will hold information about active streams open on a session and it will make sure to close all streams if the session request is closed.
Currently …
=> WebTransport session

neqo-client/src/main.rs, neqo-http3/src/client_events.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/features/extended_connect/mod.rs, neqo-http3/src/features/extended_connect/session.rs, neqo-http3/src/features/extended_connect/webtransport.rs, neqo-http3/src/lib.rs, neqo-http3/src/push_controller.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-http3/src/server_connection_events.rs, neqo-http3/src/server_events.rs, neqo-http3/tests/httpconn.rs, neqo-http3/tests/priority.rs, neqo-http3/tests/send_message.rs, neqo-http3/tests/webtransport/mod.rs, neqo-http3/tests/webtransport/streams.rs, neqo-interop/src/main.rs, neqo-server/src/main.rs
This implements WebTransport streams. A stream is a very thin layer that is responsible for posting RecvStreamEvents and SendStreamEvents and removing itself from the ExtendedConnectSession.
The WebTransport streams reuse a lot of API that was used for HTTP requests, e.g. reading data, stream_close_send, stream_reset. Also all events are reused. The only difference between a HTTP request and WebTransport is that WebTransport starts with a new event “NewStream”(if they are peer initiated) and the HTTP request starts with HeadersReady. The events now use Http3StreamInfo that contains the type and the stream number.
Parts that are not so nice is that Http3Connection cannot create streams directly because it need Box<dyn Send/RecvStreamEvents>, so the WebTransport streams are partially handle …
=> Wt streams

neqo-http3/src/client_events.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/features/extended_connect/mod.rs, neqo-http3/src/features/extended_connect/session.rs, neqo-http3/src/lib.rs, neqo-http3/src/send_message.rs, neqo-http3/tests/webtransport/mod.rs, neqo-http3/tests/webtransport/streams.rs
The most important part of the patch is that the function take_sub_streams takes the 2 list of WebTransport streams that are associated with an extended connect session. Http3Connection will remove and close the streams.
=> Implement closing of WebTransport streams if sessions are closed or cancelled.

neqo-http3/src/conn_params.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/server.rs, neqo-http3/src/server_connection_events.rs, neqo-http3/src/server_events.rs, neqo-http3/tests/httpconn.rs, neqo-http3/tests/priority.rs, neqo-http3/tests/webtransport/mod.rs, neqo-interop/src/main.rs, neqo-transport/src/connection/params.rs, neqo-transport/src/server.rs, neqo-transport/src/tparams.rs, test-fixture/src/lib.rs
PR #1270 refactored the server side API. Instead of set_response that used to accept all data supply, now there are 3 functions: send_headers, send_data and stream_close_send. Important change is also that send_data does not accept more data than the flow control allows. To be able to write larger responses DataWritable events are needed to to trigger writes when more flow control credit is available.
Additional changes:
To write a test for the event it was necessary to change transport level parameters when creating a Http3Server. To avoid hitting the limit of the number of parameters in a function, ConnectionParameters are added to Http3Parameters. This will fix #1251.
=> Add the DataWritable event to the server side

neqo-transport/src/cid.rs
This changes the logic so that sequence numbers from the server don't
start at 2, which has caused some interoperability issues.
=> Don't skip sequence number 1 for NEW_CONNECTION_ID

.github/workflows/check.yml, neqo-common/src/incrdecoder.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/control_stream_remote.rs, neqo-http3/src/frames/hframe.rs, neqo-http3/src/frames/reader.rs, neqo-http3/tests/priority.rs
Don't try to read the payload of empty frames, it doesn't work.
The real fix is in neqo-http3/src/frames/reader.rs
This includes a few other changes:
* I made the incremental ignoring decoder not work for zero-length
things.  This is the source of the problem.  Fixing this doesn't help in
this case, but it should block similar mistakes.
* Enable RUST_LOG for running in CI.  The test runner now captures
output, so we are able to get per-test logs when they fail.
* Use || instead of | for a boolean condition.
* Fixed a typo in comments/logs.
* Improved exchange_packets.
* Streamlined the event handling in priority_update.
=> zero-length unknown frame payloads

neqo-client/src/main.rs, neqo-http3/src/connection_client.rs
I'm still having massive problems with getting cloudflare sites to work with this.  Same with Facebook.  Google works fine.  It doesn't seem limited to resumption, but it does seem worth investigating further.
=> Enable resumption for h3 with neqo-client

neqo-http3/src/connection_client.rs
I was going to just commit this and push directly as it is trivial, but
I wanted to share...
Clippy generated an error with this code, suggesting that it use
`.map_or(None, |x| ...)`.  Then it suggested that that
was better replaced with `.and_then(|x| ...)`.  Finally, it suggested
that a simple `.map(|x| foo)` was better than the `.and_then(|x|
Some(foo))` there.
In any case, here we are after three separate clippy lints.
Obvious in retrospect, had I bothered to think at all.
=> Use map for encoding resumption token

neqo-crypto/build.rs
If the NSS_DIR environment variable is absolute the user may be
presented with confusing error messages later in the build
script.
- The NSS_DIR environment variable (if relative) is expected to be relative to `neqo-crypto`
- The path added to the search path will not be correct, so the user will see a failure to find a needed lib
We could throw a warning and rely on the user to set the `LD_LIBRARY_PATH`
correctly, but it seems easier to just expect a absolute path.
=> Minor improvement to neqo-crypto build script

neqo-transport/src/packet/mod.rs, neqo-transport/src/server.rs
Avoid repeating the clients initial version in the supported versions
listed in the Version Negotiation packet.
Fixes: #1331
=> Version Negotiation do not repeat client initial version

neqo-common/src/codec.rs, neqo-common/src/incrdecoder.rs, neqo-crypto/build.rs, neqo-crypto/src/selfencrypt.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/control_stream_local.rs, neqo-http3/src/features/extended_connect/webtransport_session.rs, neqo-http3/src/frames/hframe.rs, neqo-http3/src/frames/tests/mod.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server.rs, neqo-http3/src/stream_type_reader.rs, neqo-http3/tests/webtransport/negotiation.rs, neqo-transport/src/addr_valid.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/quic_datagrams.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tparams.rs, neqo-transport/tests/retry.rs, neqo-transport/tests/server.rs, neqo-transport/tests/sim/mod.rs
Use the `AsRef` and `AsMut` traits instead of `Deref` to access the `Encoder`
and `Decoder` internal buffers.
=> Use AsRef and AsMut instead of Deref

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/vn.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/qlog.rs, neqo-transport/src/server.rs, neqo-transport/src/tparams.rs, neqo-transport/src/version.rs, neqo-transport/tests/server.rs
CI not working really hid a major problem here.  Let's not let this rot
so much again...
The code didn't work here because we weren't saving the wire version
when we parsed the packet header for a packet that had an unsupported
version.  Now we do, so we can correctly generate a VN packet.
I took the liberty of renaming as_u32 to wire_version so that we are
more consistent with the naming of the version functions.
=> Fix changes to VN

neqo-common/src/hrtime.rs, neqo-crypto/src/cert.rs, neqo-crypto/src/ech.rs, neqo-crypto/src/hp.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/p11.rs, neqo-crypto/src/prio.rs, neqo-crypto/src/ssl.rs
bindgen makes a hash of these, but so did we in a few places
=> Suppress borrow_as_ptr warnings

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/keys.rs, neqo-transport/src/lib.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/recovery.rs, neqo-transport/tests/connection.rs, neqo-transport/tests/retry.rs, test-fixture/src/assertions.rs
This turned out to be a little fiddly, but it should also improve
handshake reliability (in rare scenarios, admittedly).
Changes:
1. At the client, discard the Initial packet number space when the
Handshake keys are installed.
2. Because Initial packets from the client are not sent in its second
flight, the server won't get an ACK, which otherwise drives the RTT
estimate.  Rather than disrupt all the tests, when the server discards
its Initial packet number space it will add an implicit RTT sample.
Note: The server will not increase its congestion window as a result of
this.  We might consider doing something about that later.
3. Because the client might only receive Initial packets from the
server, if it discards the Initial packet number space there will be
nothing to send.  No Initial …
=> Don't send small Initial packets

neqo-common/src/lib.rs, neqo-common/src/log.rs, neqo-transport/src/dump.rs, neqo-transport/tests/sim/mod.rs
Use the `write!` macro to extend strings with formatted text.
Allow clippy::module_name_repetitions in the `log` module.
=> Placate clippy.

neqo-crypto/src/aead_fuzzing.rs
The original rationale for this panic was to ensure we never ship users a Firefox with a crypto-disabled version of aead. However, it is common for Firefox fuzzing builds to be optimized: fuzzing is often combined with LLVM's Address Sanitizer, whose docs recommend optimized builds. Such Firefox builds crash the moment anything tries to initialize Aead.
There are other safeguards in place that prevent Mozilla from shipping fuzzing-enabled builds, so this one can be removed.
[edit:] This solution to the problem was discussed in [Bug 1743672](https://bugzilla.mozilla.org/show_bug.cgi?id=1743672#c11).
=> `aead_fuzzing::Aead::new`: Don't panic in release builds.

neqo-transport/src/recovery.rs, neqo-transport/tests/common/mod.rs, neqo-transport/tests/connection.rs, neqo-transport/tests/retry.rs, neqo-transport/tests/server.rs, test-fixture/src/lib.rs
Previously, we would crash if we tried to process the ACK, because the
CRYPTO frame would cause the loss recovery state to be dropped.  Allow
that, but - most importantly - test that we don't do bad things on valid
packets.
=> A server Initial can have an ACK after CRYPTO

neqo-client/src/main.rs
- Delete `println!("Cannot create stream {:?}", e);`.
=> Delete misleading error output by client

neqo-http3/src/features/extended_connect/mod.rs, neqo-http3/src/features/extended_connect/tests/webtransport/datagrams.rs, neqo-http3/src/features/extended_connect/tests/webtransport/mod.rs, neqo-http3/src/features/extended_connect/tests/webtransport/negotiation.rs, neqo-http3/src/features/extended_connect/tests/webtransport/sessions.rs, neqo-http3/src/features/extended_connect/tests/webtransport/streams.rs
The code  under neqo-http3/src/features/extended_connect/tests/ is not compiled at all.
The PR ensures the code under neqo-http3/src/features/extended_connect/tests/ is compiled and  fixes all  the compilation errors when enabling compilation for web transport tests.
=> Fix broken compilation for webtransport tests

neqo-client/src/main.rs, neqo-server/src/main.rs
Based on a request I'm fielding about this, it seems like it would be helpful to add this.
For a later date, we might consider consolidating some of this code.  The duplication is a problem.  We'd probably want to add that to the mainline code, but under a feature flag, so that we don't pull in all the dependencies unless we're building the command-line tools as well.
=> Add idle timeout flag to command-line tools

neqo-common/src/lib.rs, neqo-common/src/log.rs, neqo-transport/tests/network.rs
This is a relic of an older rust edition.  Macros are available to the crate in which they are defined and used like functions otherwise.
=> Eliminate use of `#[macro_use]`

neqo-http3/src/headers_checks.rs
When creating a new webtransport session the CONNECT request must have the scheme, authority, and path set.
Fixes: https://github.com/mozilla/neqo/issues/1365
=> Fix header check for webtransport session creation

README.md
my take is this issue happens often to users installing and using this software. And one get an hint with the info in the next paragraph, but that is not clear it is also for any kind of installation. And it is not easy to do the right command as the solution is finding the temp dir used at build time. Hence the need to specify the information clearly for people.
reference to issue #1045
=> add instructions on how to solve the failure to load dynamic library at run time

neqo-client/src/main.rs, neqo-common/src/codec.rs, neqo-common/src/hrtime.rs, neqo-common/src/incrdecoder.rs, neqo-crypto/src/result.rs, neqo-crypto/src/time.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/headers_checks.rs, neqo-http3/src/server.rs, neqo-http3/tests/priority.rs, neqo-qpack/src/decoder.rs, neqo-server/src/main.rs, neqo-transport/src/cc/tests/cubic.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/ackrate.rs, neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/priority.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/crypto.rs, neqo-transport/src/fc.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/streams.rs, neqo-transport/src/tparams.rs, neqo-transport/src/tracking.rs, neqo-transport/tests/server.rs, neqo-transport/tests/sim/connection.rs, test-fixture/src/lib.rs
This is the preferred way to ignore a return value now, apparently.
The alternative is `let _: ReturnType =`, which is nice in the sense that it ensures that the type remains stable, but that is verbose and mostly these are just in test code.
=> Remove let from _ bindings

.github/workflows/check.yml
Ubuntu version 20.04 -> 22.04
checkout action v2 -> v3
rustup 1.24.3 -> 1.26.0
LLVM 10 -> 14 (comes with the Ubuntu change)
The only one that is urgent is the action update, which will result in builds failing if we don't fix it.  The others are just so that we don't drop too far behind.
Definitely don't commit this until CI passes, which means that I need to fix the `EnumSet` thing.
=> Update CI dependencies

neqo-client/Cargo.toml, neqo-common/Cargo.toml, neqo-crypto/Cargo.toml, neqo-http3/Cargo.toml, neqo-interop/Cargo.toml, neqo-qpack/Cargo.toml, neqo-server/Cargo.toml, neqo-transport/Cargo.toml, test-fixture/Cargo.toml
The new recommendation is to follow the SPDX 2.1 standard. This allows automatic license verification software to work properly. Reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
=> Update license field following SPDX 2.1 license expression standard

neqo-common/Cargo.toml, neqo-common/src/codec.rs, neqo-common/src/header.rs, neqo-common/src/incrdecoder.rs, neqo-common/src/log.rs, neqo-common/src/timer.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/hp.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/p11.rs, neqo-crypto/tests/agent.rs, neqo-http3/src/client_events.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/control_stream_local.rs, neqo-http3/src/frames/wtframe.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/header_block.rs, neqo-qpack/src/lib.rs, neqo-qpack/src/reader.rs, neqo-qpack/src/table.rs, neqo-server/src/main.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, test-fixture/src/lib.rs
Several things:
1. https://github.com/rust-lang/log/commit/9d052b17d3ddf9b5894740c6d82899c531c789ee changed the internal-only APIs used by the `log` crate.  This was always just a roundabout way of doing `module_path!()`, so we're good.
2. The `time` crate moved to a minimum version of rust beyond the one we support, so pin its version.
3. Clippy errors are being generated as a result of new rust versions.  There are a fair number of these:
1. Remove some `clippy::missing_panics_doc` overrides.
2. Some functions were really missing `Panics` docs.
3. Some pointer casts were changed from `as *mut T` to `cast_mut()` or `as *const T` to `cast()`.
4. Some calls to `.iter()` were unnecessary.
5. A new `clippy::single_range_in_vec_init` lint was added, but with a false positive.
6. Clippy …
=> General maintenance

neqo-http3/src/connection_client.rs
The spec added this since the original SendOrder work started
=> Make the external set_sendorder() take an Option<SendOrder>

neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cc/cubic.rs, neqo-transport/src/cc/tests/cubic.rs
The variables were used correctly, so no actual bug was fixed.
Dividend ÷ Divisor = Quotient
7 ÷ 10 = 0.7
https://en.wikipedia.org/w/index.php?title=Quotient&oldid=1175290601#Notation
=> Fix terminology in cubic beta variable

neqo-client/Cargo.toml, neqo-common/Cargo.toml, neqo-crypto/Cargo.toml, neqo-http3/Cargo.toml, neqo-interop/Cargo.toml, neqo-qpack/Cargo.toml, neqo-server/Cargo.toml, neqo-transport/Cargo.toml, test-fixture/Cargo.toml
Denying in the source makes developing neqo a bit cumbersome. It also makes it harder to compile neqo with future versions of Rust. We do have a CI pipeline for clippy denying all warnings. That should be enough to keep all the warnings out.
=> Only warn on warnings and don't deny compiling during development

neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cc/tests/new_reno.rs
Before this patch, the congestion window was reduced multiple times per round trip time (RTT) on multiple packet loss. Not it is capped to one per RTT.
The recovery_start variable is only updated after transitioning from RECOVERY_START to RECOVERY when sending out packets after the recovery event. So if the state is RECOVERY_START (transient), all packets are from before the RECOVERY. Therefore we must only check the recovery_start time after trasitioning to the RECOVERY state.
If we haven't encountered a packet loss, the packets always count as after recovery_start.
This is to fix the congestion algorithm to be [spec aligned][1]:
> The recovery period aims to limit congestion window reduction to once
> per round trip. Therefore, during a recovery period, the congestion
> window does not …
=> Fix detection whether packet was sent after recovery start

neqo-http3/Cargo.toml
This matches the latest in gecko and avoids a clippy warning.
=> Update enumset dependency

neqo-transport/src/cc/classic_cc.rs
print pointer of self instead of debug print internal variables. Used to identify same congestion controller when having multiple concurrent connections. Sorry that I missed this during the initial PR #1484. I tested all other messages now as well and they look fine and I can generate the same graphs out of them.
=> Fix classic_cc debug output

neqo-transport/src/connection/idle.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/ackrate.rs, neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/connection/tests/keys.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/tracking.rs
This should improve loss recovery performance if we haven't been active for a short while.
The actual change is fairly trivial, but the tests needed to be tweaked in several ways to deal with a few places where we generated an immediate acknowledgment.
I also found a test where I couldn't work out why it ever passed before.  One of the migration tests was sending multiple packets without acknowledgment on a new path, which had the default RTT.  It was therefore pacing for the third packet.  I don't know how that ever passed.
=> ACK immediately after an RTT

README.md
Escape IPv6 address with single quotes.
Prevents shells from interpreting IPv6 address as file pattern:
```
zsh: no matches found: [::]:1234
```
Also makes it consistent with `neqo-*` commands in `### QUIC Logging`.
=> docs(README): escape IPv6 address

neqo-client/Cargo.toml, neqo-common/Cargo.toml, neqo-http3/Cargo.toml, neqo-qpack/Cargo.toml, neqo-server/Cargo.toml, neqo-transport/Cargo.toml, neqo-transport/src/qlog.rs
This commit upgrades all `neqo-*` crates to use `qlog` `v0.10.0`.
See also `qlog` `v0.10.0` release pull request https://github.com/cloudflare/quiche/pull/1647
Could as well be defined as a [workspace dependency](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) to reduce duplication.
=> deps(qlog): update to qlog v0.10.0

.github/workflows/check.yml
=> Don't fail CI if Codecov upload fails

neqo-common/src/hrtime.rs
Whatever I did to this file in #1512 made the tests on MacOS fail (because timer accuracy got bad.) Restoring the code and adding clippy ignores fixes this.
=> Fix hrtimer tests on MacOS

neqo-client/src/main.rs, neqo-server/src/main.rs
This PR makes neqo-client support doing upload test.
The command is `./target/release/neqo-client http://127.0.0.1:4433/  --test upload  --upload-size 104857600`.
=> Make neqo-client support upload test

.github/workflows/check.yml
Explicitly install `llvm-tools-preview` via `rustup` instead of indirectly during the coverage run.
=> More CI fixes

neqo-http3/src/push_controller.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/prefix.rs, neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cc/cubic.rs, neqo-transport/src/cc/mod.rs, neqo-transport/src/cc/tests/cubic.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/path.rs
CI is currently failing with `stable` Rust, given a couple of new clippy lints in Rust v1.75. This pull requests fixes the lints.
See https://github.com/mozilla/neqo/actions/runs/7363919275/job/20043828874?pr=1533 for a sample failure.
=> fix(clippy): new lints introduced in Rust v1.75

neqo-transport/src/qlog.rs
Map `State::Closing` to `ConnectionState::Closing` instead of `ConnectionState::Draining`.
Assuming that this is a typo.
CI Clippy failures are unrelated. See https://github.com/mozilla/neqo/pull/1534 for a fix.
=> fix(transport/qlog): map State::Closing onto ConnectionState::Closing

neqo-client/Cargo.toml, neqo-client/src/main.rs, neqo-http3/src/connection_client.rs, neqo-transport/src/connection/mod.rs
Previously, the we only read one packet from the socket at a time. This patch allows to read more than one packet from the socket.
=> Enhance socket read to handle multiple packets

neqo-client/src/main.rs, neqo-interop/src/main.rs, neqo-server/src/main.rs, neqo-server/src/old_https.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/frame.rs, neqo-transport/src/lib.rs, neqo-transport/src/tparams.rs
Inline variables into format strings wherever possible.
https://rust-lang.github.io/rust-clippy/master/index.html#/uninlined_format_args
---
Breaking https://github.com/mozilla/neqo/pull/1532 into smaller pull requests to ease review and reduce merge conflicts.
=> refactor: inline format args

neqo-transport/src/lib.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/server.rs
Replace match wildcard whereever it is matching a single variant only.
https://rust-lang.github.io/rust-clippy/master/index.html#/match_wildcard_for_single_variants
---
Breaking https://github.com/mozilla/neqo/pull/1532 into smaller pull requests to ease review and reduce merge conflicts.
=> refactor: match single variant over wildcard

neqo-common/Cargo.toml
It was done because of time's MSRV, but neqo's MSRV was raised to 1.70.0, which now more recent than what any version of time requires.
=> Undo the restriction on the time dependency.

neqo-client/src/main.rs, neqo-server/src/old_https.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs, neqo-transport/src/dump.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/server.rs, neqo-transport/src/tparams.rs, neqo-transport/tests/connection.rs
Use Rust's (`>= v1.65`) new let-else feature whereever possible.
https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html
https://rust-lang.github.io/rust-clippy/master/index.html#/manual_let_else
---
Breaking https://github.com/mozilla/neqo/pull/1532 into smaller pull requests to ease review and reduce merge conflicts.
=> refactor: use let-else

README.md
There's no `libssl3.so`, so the existing command sets the environment variable to an empty string.
=> README: fix install instructions on macOS

neqo-transport/src/tparams.rs, neqo-transport/src/version.rs
Fixes clippy lint `unreadable-literal`.
https://rust-lang.github.io/rust-clippy/master/#/unreadable_literal
=> refactor: address clippy::unreadable-literal

Cargo.toml, neqo-transport/src/qlog.rs, neqo-transport/src/server.rs
This commit adds support for the qlog [`version_information` QUIC event](https://quicwg.org/qlog/draft-ietf-quic-qlog-quic-events.html#name-version_information) on the server.
See https://github.com/mozilla/neqo/pull/1505 for the client side.
~~Depends on `qlog` patch release with https://github.com/cloudflare/quiche/pull/1684~~ :heavy_check_mark: 
Meta issue: https://github.com/mozilla/neqo/issues/528
Fixes https://github.com/mozilla/neqo/issues/1549
=> feat(qlog): log version_information on server

neqo-common/Cargo.toml, neqo-common/src/qlog.rs, neqo-transport/src/cid.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/qlog.rs, test-fixture/Cargo.toml, test-fixture/src/lib.rs
Fixes include:
* Change `raw.payload_length` to `raw.length`  - the information logged was the raw (total) length already, but the label incorrectly stated it was the _payload_ length.
* Log transport parameters with a valid (in-sequence) timestamp.
* Log `ACTIVE_CONNECTION_ID_LIMIT` and `PREFERRED_ADDRESS` to qlog.
Also:
* Add some tests to `neqo-common::qlog`
=> Fix qlog issues to enable correct qvis rendering

neqo-client/src/main.rs, neqo-interop/src/main.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/qlog.rs
Addresses clippy lint match-same-arms and unnested-or-patterns.
https://rust-lang.github.io/rust-clippy/master/index.html#match_same_arms
https://rust-lang.github.io/rust-clippy/master/index.html#unnested_or_patterns
=> refactor: clippy `match-same-arms` & `unnested-or-patterns`

neqo-client/src/main.rs
Previously `neqo-client` would not close the sending side of a stream after sending a GET request. Corresponding section in RFC 9114:
> After sending a request, a client MUST close the stream for sending.
https://www.rfc-editor.org/rfc/rfc9114.html#name-http-message-framing
---
This surfaces in the Quic Interop Runner `http3` test. Here the client downloads 3 files from the server.
1. The client opens stream `0`, sends a GET for the first file.
2. The client opens stream `4`, sends a GET for the second file.
3. The client opens stream `8`, sends a GET for the third file.
4. ...
5. Eventually the client has read the whole response on stream `0`, [it removes the corresponding `StreamHandler` from
`self.url_handler.stream_handlers`](https://github.com/mozilla/neqo/blob/64fb41f47cbbbb1101484dc …
=> fix(client): call stream_close_send after GET

neqo-server/src/main.rs
The Quic Interop Runner expects the server to use `Version::Version1` in all testcases but `versionnegotiation` and `v2`.
See discussion in [Quic Interop Runner issue](https://github.com/quic-interop/quic-interop-runner/pull/344#issuecomment-1895771528) and corresponding code in the [Quic Interop Runner](https://github.com/quic-interop/quic-interop-runner/blob/ca27dcb5272a82d994337ae3d14533c318d81b76/testcases.py#L188-L195).
While Neqo's default `Version` is `Version1`, the default `VersionConfig` includes all versions (`Version::all()`) and thus the server will currently upgrade the connection to the compatible `Version::Version2`.
With this commit, the server will always choose `Version1` when running a qns testcase. Given that Neqo's qns implementation does not support the …
=> fix(qns): always use Version1 on server

neqo-client/src/main.rs, neqo-server/src/main.rs
Add support for Quic Network Simulator `v2` testcase.
In `v2` testcase, don't restrict the server to `Version::Version1`, thus allowing the server to upgrade incoming `Version::Version1` connection to compatible `Version::Version2` connection.
See also [Quic Network Simulator `v2` testcase implementation]( https://github.com/quic-interop/quic-interop-runner/blob/ca27dcb5272a82d994337ae3d14533c318d81b76/testcases.py#L1460-L1545).
---
//CC @marten-seemann
Follow-up to https://github.com/mozilla/neqo/pull/1563.
Related to https://github.com/quic-interop/quic-interop-runner/pull/344 and https://github.com/mozilla/neqo/issues/1552.
=> feat(qns): implement v2 testcase

neqo-common/src/hrtime.rs
See the crash in this [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1874581).
The crash reason `assertion failed: (left == right) left: 0, right: 97` means that `timeEndPeriod` returns the error `TIMERR_NOCANDO`.
It's unclear to me why we got this error, but I think we should not crash in this case.
=> Don't crash when timeBeginPeriod/timeEndPeriod returns an error

neqo-client/src/main.rs, neqo-common/Cargo.toml, neqo-common/src/datagram.rs, neqo-common/src/lib.rs, neqo-common/src/tos.rs, neqo-interop/src/main.rs, neqo-server/src/main.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/close.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/connection/tests/vn.rs, neqo-transport/src/path.rs, neqo-transport/src/server.rs, neqo-transport/tests/conn_vectors.rs, neqo-transport/tests/connection.rs, neqo-transport/tests/retry.rs, neqo-transport/tests/server.rs, test-fixture/src/lib.rs
This part of the refactor of #1495.
This doesn't include any ECN I/O or other logic, just adds the required fields to the datagram header.
=> Add TOS and TTL information to Datagrams

neqo-client/src/main.rs
The Quic Network Simulator `handshakeloss` testcase instructs the `neqo-client` to download from multiple URLs in series. The client takes one URL after the next and tries to request it:
``` rust
to_request = &remaining[..1];
remaining = &remaining[1..];
```
This will panic on the last URL, trying to access the first element in the empty slice `remaining`.
This commit removes the out-of-range access. Instead of using slice operations which hide potential panics, it uses owned collections (`VecDeque` and `Vec`) and their safe methods (e.g. `pop_front`, `drain`).
---
Needed for https://github.com/quic-interop/quic-interop-runner/pull/344.
Related to https://github.com/mozilla/neqo/issues/1552.
=> fix(client): prevent out-of-range slice access

.github/workflows/check.yml, neqo-http3/src/connection_client.rs, neqo-http3/src/lib.rs, neqo-transport/src/packet/mod.rs, test-fixture/src/lib.rs
- Fix minor typos in Rust intra doc links.
- Add CI check.
---
I find Rust intra doc links helpful, not so much for the links themselves, but for the static check flagging outdated documentation.
=> fix: Rust intra doc links

neqo-client/src/main.rs
QUIC Interop Runner testcases `resumption` and `0-rtt` expect the client to download the first file, close the connection, and then download the remaining files on a second connection.
https://github.com/quic-interop/quic-interop-runner/tree/master#test-cases
Thus `neqo-client`, when `args.resume` is `true` must only take a single URL on the **first** loop iteration. On the second iteration it must take all remaining URLs.
Regression introduced in https://github.com/mozilla/neqo/pull/1569. My bad.
---
With this patch all, but the `amplification` testcase, are green. Note that the `amplification` testcase failed with the previous qns image as well. See https://interop.seemann.io/. 
```
Received a 1337 byte Handshake packet from the server. Total: 5348
Server violated the amplification …
```
=> fix(client): only take single url on (args.resume && first)

neqo-transport/src/ackrate.rs, neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cc/mod.rs, neqo-transport/src/cc/tests/cubic.rs, neqo-transport/src/cc/tests/new_reno.rs, neqo-transport/src/path.rs, neqo-transport/src/rtt.rs, neqo-transport/src/sender.rs
Maybe it's worth to also log RTT.
=> add support to log rtt

neqo-transport/src/connection/mod.rs
I think it should be useful to log the reason why TX is blocked.
As the first step, logging `SendProfile` might be enough.
=> log SendProfile when nothing to send

neqo-crypto/.gitignore, neqo-crypto/TODO, neqo-transport/.gitignore, neqo-transport/TODO
The .gitignore files serve no purpose, and if there is anything in the TODO files left to be done, those things should become GitHub issues.
=> chore: Remove some outdated files

.dockerignore, qns/Dockerfile
Also use `git` to get nss, which is a bit faster.
CC @mxinden
=> chore: Make the qns image multiarch & shrink the build context further

neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/recovery.rs, neqo-transport/tests/retry.rs
This limits the Initial packet number space to sending one packet when a PTO fires (other packet number spaces will continue to send two.) This stops PING-only Initial packets during handshake.
Some tests based in the assumption that those PINGs would be sent. Fix those, too. I'd appreciate if someone could esp. double-check the test modifications, esp. to the `idle_caching` test, which is gnarly.
Fixes #744
=> fix: Don't send superfluous PING-only Initial packets during handshake

neqo-transport/src/recovery.rs
The previous code would overflow and produce a 0ns timeout when the PTO count got large (well over 24).  This is because the `fast_pto` value tends to have trailing zero bits and shift values between 32-(number of zeros) and 31 (inclusive) would still shift left.
This code instead stops increasing the PTO once it hits 24.  That should be enough for most cases.
Closes #1602.
=> Cap the PTO count when working out the period

.github/workflows/check.yml, qns/Dockerfile
Because the latter can be outdated. This is why #1081 is failing CI.
=> ci: Clone NSS from hg and not the GitHub mirror

neqo-crypto/bindings/bindings.toml, neqo-crypto/src/agent.rs, neqo-crypto/src/constants.rs, neqo-crypto/src/lib.rs, neqo-crypto/tests/agent.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs
Currently, neqo clients list all of the key exchange groups supported by NSS in their supported_groups extension, and this is not configurable. They also send only one key share entry.
The first patch in this PR makes it possible to configure both the supported_groups list and the number of key share entries that are sent. The second patch sets defaults for both. 
According to [telemetry](https://glam.telemetry.mozilla.org/firefox/probe/ssl_kea_ecdhe_curve_full/explore), about 82% of TLS 1.3 connections over TCP negotiate X25519 and 16% negotiate P-256. The remainder use P-384 or P-521. My guess is that QUIC is even more heavily skewed towards X25519 but that it still makes sense to send a P-256 share.
Some additional motivation for this change:
I've recently [added …
=> Add key exchange group configuration knobs

.github/semantic.yml, .github/workflows/check.yml, hooks/pre-commit, neqo-server/src/main.rs
And fix the pre-commit hook to check using nightly.
This is because we now rely on rust nightly for some rustfmt configuration options.  This will make our canary builds a little more forward-looking which comes with a little less stability, but I think that's better than adding a specific build just for formatting.
=> ci: Switch to rust nightly for CI canary

neqo-transport/src/connection/dump.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/lib.rs
This commit contains two changes:
The first change. To avoid expensive packet decoding and string encoding, the `neqo-transport` `dump_packet` function first checks the current log level:
``` rust
if ::log::Level::Debug > ::log::max_level() {
return;
}
```
This is problematic when e.g. setting `RUST_LOG=info,neqo_crypto=debug`. While `::log::max_level` will return `::log::Level::Debug`, given the `neqo_crypto=debug`, the log level of the `neqo_transport` crate and `dump` module will be `info`. Thus the packet will be de-/encoded, but never logged, given that the `qdebug!` call calls `log::debug!`, which will check the module log level and not use the maximum log level.
Instead, with this commit, `dump_packet` checks the module log level.
``` rust
if !log::log_enabled!(log::Level::Debug) { …
```
=> fix(transport/dump): check module not max log level and move to conn

neqo-client/Cargo.toml, neqo-common/Cargo.toml, neqo-http3/Cargo.toml, neqo-qpack/Cargo.toml, neqo-server/Cargo.toml, neqo-transport/Cargo.toml, test-fixture/Cargo.toml
Please see https://phabricator.services.mozilla.com/D200303#6878754.
I assume we can use this revision of qlog temporally.
=> Use temp rev for qlog

neqo-transport/Cargo.toml, neqo-transport/benches/range_tracker.rs, neqo-transport/src/lib.rs, neqo-transport/src/send_stream.rs
This is a version of #1592 that I think is better than alternatives.  It creates a single gap in the range tracker, then fills it.
I'm splitting this off #1594 so we can get a good baseline.
<details><summary>Preview of #1594 against main</summary>
There is some amount of variability, but this generally seems good to me.
```
coalesce_acked_from_zero 1+1 entries
time:   [74.649 ns 75.089 ns 75.792 ns]
change: [-51.264% -51.008% -50.698%] (p = 0.00 < 0.05)
Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
1 (1.00%) low mild
7 (7.00%) high mild
5 (5.00%) high severe
coalesce_acked_from_zero 3+1 entries
time:   [103.37 ns 103.61 ns 103.88 ns]
change: [-47.846% -47.326% -46.435%] (p = 0.00 < 0.05)
Performance has improved.
Found 5 outliers among 100 measurements …
```
=> Range tracker benchmark

neqo-client/src/main.rs
* Only allow v1 for most interop runner runs
=> fix: More green for the neqo fields in the interop runner

neqo-transport/src/send_stream.rs
This is very verbose and it pollutes things like interop runner traces too much.
=> Drop the logging level for STREAM frame writing

.codecov.yml, .github/workflows/check.yml
=> ci: Only upload coverage from stable debug builds to Codecov

test/README.md, test/mozlog-neqo-cwnd.py
This script can visualize MOZ_LOGs
* 'HTTP/3 upload speed' in `about:logging`
* log modules: `timestamp,neqo_transport::*:3`
Using the directory `performance-test` from https://github.com/mozilla/neqo/pull/1529
Moving the script from https://github.com/mb/scripts/blob/5a72b00cda615a9ea940f0f93efeacb422807ec0/visualize/mozlog-neqo-cwnd.py
Example output: https://bugzilla.mozilla.org/show_bug.cgi?id=1852924#c36
=> Add script to plot neqo's MOZ_LOG output from the congestion controller

neqo-client/Cargo.toml, neqo-common/Cargo.toml, neqo-crypto/Cargo.toml, neqo-http3/Cargo.toml, neqo-interop/Cargo.toml, neqo-qpack/Cargo.toml, neqo-server/Cargo.toml, neqo-transport/Cargo.toml, test-fixture/Cargo.toml
And more clearly mark those needing to be in sync with Firefox.
=> chore: Drop patch versions from deps

.github/workflows/check.yml, Cargo.toml, neqo-crypto/src/ech.rs, neqo-crypto/src/hkdf.rs, neqo-crypto/src/hp.rs, neqo-crypto/src/p11.rs, neqo-transport/src/connection/mod.rs
This should address the CI build errors with `clap`. Also remove some clippy allows.
=> chore: FF now using Rust 1.74.0

.github/workflows/bench.yml, .github/workflows/check.yml, neqo-common/src/qlog.rs, test-fixture/Cargo.toml, test-fixture/src/lib.rs
To remove those overheads from the profile.
This PR also rolls in some changes to the bencher, i.e., to make it generate flamegraphs and make them and the raw perf/criterion data available as build artifacts.
=> ci: Benchmark without a qlog

.github/workflows/bench.yml
For @jesup, to see if this is better than `dwarf`
=> ci: Use `lbr` to generate a perf call graph

neqo-http3/src/features/extended_connect/webtransport_session.rs, neqo-http3/src/features/extended_connect/webtransport_streams.rs, neqo-http3/src/lib.rs, neqo-http3/src/send_message.rs
Removes `fn` `set_sendorder` and `set_fairness` on `SendStream` trait.
The `SendStream` trait is not publicly exposed. Neither `set_sendorder` nor `set_fairness` is called within `neqo-http3`.
Fixes https://github.com/mozilla/neqo/issues/1651.
=> refactor: remove dead fairness and sendorder fn on SendStream

.github/workflows/check.yml, .github/workflows/qns.yml
If I understand the documentation correctly, using GitHub's Merge Queue requires two steps:
1. Adding the `merge_group` trigger to each workflow. Done via this pull request.
2. Enabling Merge Queue in the settings.
1. Settings/Branches/Branch Protection Rules/main/edit
2. Enable "Require Merge queue"
See [GitHub documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions).
Fixes https://github.com/mozilla/neqo/issues/1673.
=> feat(.github): enable merge queue

neqo-client/src/main.rs
The QUIC Interop testcase `resumption` requires a client to download two files on two consecutive connections, establishing the second connection with the resumption token of the first.
Previously the client would close the first connection once the first file is downloaded. There is a race condition where the first file might be finished downloading before receiving the resumption token from the server.
With this commit, the client will wait for both (1) the file being downloaded and (2) receiving the resumption token from the server.
---
Fixes https://github.com/mozilla/neqo/issues/1628
=> fix(client): wait for resumption token 

Cargo.toml
Avoids this warning during build:
```
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```
=> chore: Set workspace resolver to version 2

neqo-transport/src/connection/tests/cc.rs
The `cc_slow_start_to_cong_avoidance_recovery_period` test sends two flights of data from client to server. In the second flight the first packet is dropped, which is thus not included in the second ACK of the server to the client.
Due to the dropped packet, the client is expected to move into recovery state. But the test only checks the largest acknowledged packet. It does not assert the state change. Making `ClassicCongestionControl::on_congestion_event` a no-op does not fail the test.
With this commit, the test asserts that the congestion window decreases, thus presuming a state change.
---
Hope I am not missing something.
Is comparing `cwnd`s the best way to witness a state change?
=> fix(tests/cc): compare cwnd before and after congestion

neqo-client/src/main.rs, neqo-common/src/udp.rs
Instead of allocating a new receive buffer on each call to `neqo_common::udp::Socket::recv`, preallocate a long-lived buffer in `Socket::bind` and reuse this buffer on each read.
See flamegraphs below. With the patch `neqo_common::udp::Socket::recv` simply delegates to `tokio::net::udp::UdpSocket::try_io` instead of spending significant time in `memset`.
Quick-fix while working on https://github.com/mozilla/neqo/issues/1693.
Addresses first performance issue in https://github.com/mozilla/neqo/issues/1690.
Before:
After:
=> fix(udp): pre-allocate receive buffer

.github/workflows/check.yml, neqo-common/src/datagram.rs
`Datagram::into_data` is used in `neqo_common::udp` only. `neqo_common::udp` is behind the `udp` feature. The feature is not part of the crate's default features. Thus a plain `cargo check` rightly complains with:
```
warning: method `into_data` is never used
--> neqo-common/src/datagram.rs:58:19
|
20 | impl Datagram {
| ------------- method in this implementation
...
58 |     pub(crate) fn into_data(self) -> Vec<u8> {
|                   ^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
This commit hides `into_data` behind the `udp` feature as well.
Introduced in https://github.com/mozilla/neqo/pull/1604. My bad.
=> fix: feature flag Datagram::into_data

neqo-common/src/udp.rs
Follow up to https://github.com/mozilla/neqo/pull/1707#discussion_r1510447571.
Reading multiple datagrams in single `Socket::recv` call will happen with https://github.com/mozilla/neqo/pull/1708.
=> refactor(udp): define const for receive buffer size

neqo-client/src/main.rs, neqo-common/src/udp.rs, neqo-server/src/main.rs
Previously `Socket::recv` would at most return a single `Datagram` (i.e. `-> Result<Option<Datagram>, io::Error>`). When supported by the OS, the underlying `quinn-udp` can use both recvMmsg and GRO, each with the ability to return one or more datagrams.
As of today, `neqo_common::udp` does not make use of recvmmsg effectively, i.e. it only provides a single `IoSliceMut` to write into. That said, that single `IoSliceMut` might contain multiple `Datagram`s through GRO. Previously this would have been provided as a single `Datagram` to the caller of `Socket::recv`.
This commit makes sure to handle the case where many `Datagram`s are retrieved via GRO. I.e. where `meta.stride < meta.len`, indicating that the `IoSliceMut` contains more than one datagram. In addition it updates …
=> fix(udp): handle multiple datagrams on GRO

.github/actions/nss/action.yml, .github/actions/rust/action.yml, .github/workflows/bench.yml, .github/workflows/check.yml, qns/Dockerfile
Since the mercurial ones are often flaky.
Also build NSS as part of the `nss` action, to reduce replication.
=> ci: Use the git mirrors for NSS and NSPR

neqo-server/Cargo.toml
Enable the `unicode-perl` feature flag on `regex` crate dependency in `neqo-server` crate.
The following regex makes use of the feature:
``` rust
Regex::new(r"GET +/(\S+)(?:\r)?\n").unwrap()
```
Without the feature, the QUIC Interop tests panic with:
```
server  | thread 'main' panicked at neqo-server/src/old_https.rs:140:49:
server  | called `Result::unwrap()` on an `Err` value: Syntax(
server  | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server  | regex parse error:
server  |     GET +/(\S+)(?:\r)?\n
server  |            ^^
server  | error: Unicode-aware Perl class not found (make sure the unicode-perl feature is enabled)
server  | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server  | )
```
---
I will prioritize …
=> fix(server): enable `regex` crate `unicode-perl` feature

.github/workflows/qns-comment.yml
Rename `Comment on the pull request` to `QUIC Network Simulator Comment`.
Might be a bit more intuitive, when seeing it next to the other workflows:
=> refactor(.github): rename comment workflow

.github/workflows/qns-comment.yml
Once the QUIC Network Simulator workflow finished, the QUIC Network Simulator Comment workflow adds the test results as a comment to the corresponding pull request.
This commit makes two changes:
- Only add a comment on test failure.
- In case a comment already exists, update it in place.
---
Parts of https://github.com/mozilla/neqo/issues/1716.
Note I have not been able to test this yet. Happy to port this over to my test-setup https://github.com/mxinden/quic-interop-runner-action/ though that will take me a bit more time. Your call.
=> fix(github): qns comment on failure only and update existing

neqo-client/Cargo.toml, neqo-server/Cargo.toml
When default features are disabled, clap does not e.g. generate logic for `--help` or `--version` handling. Instead it errors with the opaque error on anything other than correct command line flags.
```
$ neqo-client --version
error: unexpected argument found
```
Instead of removing `default-features = false`, enable them individually.
See https://docs.rs/clap/latest/clap/_features/index.html for details.
=> fix(client,server): re-enable clap default features

.rustfmt.toml, Cargo.toml
Emacs' most popular Rust plugin [Rustic](https://github.com/brotzeit/rustic) uses `rustfmt` to format code. `rustfmt` only picks up the Rust edition from `Cargo.toml` when executed through `cargo fmt` (see [1] and [2]).
This commit duplicates the Rust edition in the `.rustfmt.toml` file. Thus all users of `rustfmt` (whether through `cargo fmt` or plain `rustfmt`) will get formatting according to their Rust edition, e.g. helpful when interacting with `async` code.
[1]: https://github.com/brotzeit/rustic?tab=readme-ov-file#edition-2018
[2]: https://github.com/rust-lang/rustfmt?tab=readme-ov-file#rusts-editions
There might be other editors using `rustfmt` directly.
---
Feel free to close in case you think this is too editor specific.
@jesup this might safe you some debugging time as a fellow …
=> fix(.rustfmt.toml): specify Rust edition 2021

.github/actions/rust/action.yml, .github/workflows/check.yml
The caching seems to not lead to measurable decreases in CI times.
=> ci: Disable Rust cache

.github/actions/pr-comment-data-export/action.yml, .github/actions/pr-comment/action.yml, .github/actions/quic-interop-runner/action.yml, .github/workflows/bench-comment.yml, .github/workflows/bench.yml, .github/workflows/check.yml, .github/workflows/qns-comment.yml
This generalizes and refactors what the QNS workflow did.
=> ci: Safe commenting on PRs

neqo-http3/src/connection.rs, neqo-http3/tests/priority.rs
Instead of setting the priority headers in neqo, the headers should be provided by the application.
See related https://phabricator.services.mozilla.com/D201265
=> Priority headers should be set by the application

.github/workflows/bench.yml, neqo-bin/Cargo.toml, neqo-common/Cargo.toml, neqo-crypto/Cargo.toml, neqo-http3/Cargo.toml, neqo-qpack/Cargo.toml, neqo-transport/Cargo.toml, test-fixture/Cargo.toml
Because we pin the benchmark runs to single cores, and criterion hence runs the report generation also on those cores, and based on `top` output it appears as this is parallelized and hence may interfere with the benchmark runs.
=> fix: Disable generation of criterion HTML graphs

.github/workflows/actionlint.yml, .github/workflows/qns.yml
So that a failure stops all CI for a PR.
=> ci: Add `concurrency` to top-level workflows

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/migration.rs
For issue #1697 
This is just a workaround for stop crashing.
The root cause of this crash is still not clear. Maybe necko does something wrong.
Note that the [crash signature](https://crash-stats.mozilla.org/report/index/42c84380-18ac-4d7a-b425-8947f0240224) seems wrong. The frame 9 is `neqo_transport::path::Path::local_cid()`, but the provided [link](https://hg.mozilla.org/releases/mozilla-beta/file/f52b92d785d0346848c447a502d5d50bebd2ea53/third_party/rust/neqo-transport/src/path.rs#l679) to the code indicates the function is `neqo_transport::path::Path::remote_cid()`.
=> Return an error if the path is not permanent

.github/actions/rust/action.yml, .github/workflows/mutants.yml
See https://mutants.rs/, esp. https://mutants.rs/pr-diff.html
=> ci: Run `cargo mutants` on changed code

.github/actions/quic-interop-runner/action.yml
1. Provide `--markdown` flag to QUIC Interop Runner to get markdown formatted table.
2. Ignore all log output, but table.
---
Previous work: https://github.com/quic-interop/quic-interop-runner/pull/372
=> feat(.github/interop): use markdown table

.gitignore
Add some things, remove some things...
=> chore: Update `.gitignore`

neqo-bin/src/udp.rs
`Socket::send` returns the number of `Datagram`s sent. Given that it only accepts a single `Datagram` to be send, this return value is at best useless and in the worst case confusing. It is ignored at all call sites.
---
Introduced in https://github.com/mozilla/neqo/pull/1604/. My bad. Sorry for the noise.
=> refactor(udp): remove useless Socket::send return value

neqo-transport/src/connection/tests/stream.rs
Complaint by clippy nightly, see e.g. https://github.com/mozilla/neqo/actions/runs/8299484684/job/22715270281?pr=1741.
=> refactor(transport/tests): remove unused IdEntry

Cargo.toml
Because that's what Firefox does:
https://searchfox.org/mozilla-central/source/config/makefiles/rust.mk#95
=> build: Enable "fat" LTO for release builds

.codecov.yml
Should have been part of #1724
=> ci: Ignore coverage in `neqo-bin`

neqo-bin/src/bin/client/http09.rs, neqo-bin/src/bin/client/http3.rs, neqo-bin/src/bin/client/main.rs
`neqo-client` has the option to write a response to file.
With this commit, `File` is wrapped in a `64KB` `BufWriter` to increase I/O batch size and thus improve performance.
Replaces https://github.com/mozilla/neqo/pull/1752 (see https://github.com/mozilla/neqo/pull/1752#issuecomment-2002599047).
=> feat(bin/client): use BufWriter when writing to file

.github/workflows/check.yml
Windows CI oftentimes fails with:
```
0s  0ms INFO H3 Client connecting: [::]:65093 -> [::1]:4433
Error: IoError(Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." })
0s  0ms INFO Server waiting for connection on: [::1]:4433
0s  0ms INFO Server waiting for connection on: 127.0.0.1:4433
```
https://github.com/mozilla/neqo/actions/runs/8374577016/job/22930136500?pr=1692
This suggests that the client connects to the server before the server is ready to accept connections.
This commit adds a sleep, thus giving the server time to start up.
---
Tracked in https://github.com/mozilla/neqo/issues/1759.
Sleep was previously introduced in https://github.com/mozilla/neqo/pull/1713 but later removed in …
=> ci(check.yml): re-add sleep

neqo-transport/src/connection/dump.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/frame.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/qlog.rs
This is preparation of qlog supporting the logging of runs of padding frames via `payload_length`, instead of each one individually.
Needs https://github.com/cloudflare/quiche/pull/1745 (eventually).
=> feat: Extend `Frame::Padding` with length

neqo-bin/Cargo.toml, neqo-bin/src/bin/client/http09.rs, neqo-bin/src/bin/client/http3.rs, neqo-bin/src/bin/client/main.rs, neqo-bin/src/bin/server/main.rs, neqo-bin/src/bin/server/old_https.rs, neqo-common/src/log.rs, neqo-crypto/src/agent.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs, neqo-http3/src/recv_message.rs, neqo-http3/src/send_message.rs, neqo-http3/src/server_events.rs, neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs, neqo-transport/src/lib.rs, neqo-transport/src/path.rs, neqo-transport/src/stats.rs, test/upload_test.sh
- In `neqo-client` and `neqo-server` use `neqo_common::log` instead of `println!`   and `eprintln!`.
- Add `-q`, `-v`, `-vv`, `-vvv`, `-vvvv` log level flags via   `clap_verbosity_flag`.
- Set default log level to INFO. Demote many `qinfo!` to `qdebug!`.
---
Fixes https://github.com/mozilla/neqo/issues/685.
=> feat(client,server): rework logging

neqo-bin/src/bin/client/http09.rs, neqo-bin/src/bin/client/http3.rs, neqo-bin/src/bin/client/main.rs, neqo-transport/src/stats.rs
This commit introduces the `--stats` flag to `neqo-client`. It will print the `neqo_transport::Stats` of the `Connection` after close.
```
$ cargo run --bin neqo-client -- --stats http://127.0.0.1:12345/10000000
stats for Client ...
rx: 7728 drop 1 dup 0 saved 1
tx: 819 lost 12 lateack 0 ptoack 4
resumed: false
frames rx:
crypto 3 done 1 token 1 close 0
ack 40 (max 805) ping 0 padding 0
stream 7704 reset 0 stop 0
max: stream 0 data 0 stream_data 0
blocked: stream 0 data 0 stream_data 19
datagram 0
ncid 7 rcid 0 pchallenge 0 presponse 0
ack_frequency 4
frames tx:
crypto 2 done 0 token 0 close 0
ack 783 (max 7769) ping 5 padding 0
stream 5 reset 0 stop 0
max: stream 0 data 0 stream_data 30
blocked: stream 0 data 0 stream_data 0
datagram 0
ncid 0 rcid 0 pchallenge 0 presponse 0
ack_frequency …
```
=> feat(bin/client): add --stats flag printing connection statistics

neqo-transport/benches/transfer.rs
The default Criterion noise threshold is 0.01, i.e.
``` rust
/// Changes the noise threshold for benchmarks in this group. The noise threshold
/// is used to filter out small changes in performance from one run to the next, even if they
/// are statistically significant. Sometimes benchmarking the same code twice will result in
/// small but statistically significant differences solely because of noise. This provides a way
/// to filter out some of these false positives at the cost of making it harder to detect small
/// changes to the true performance of the benchmark.
///
/// The default is 0.01, meaning that changes smaller than 1% will be ignored.
///
/// # Panics
///
/// Panics if the threshold is set to a negative value
pub fn noise_threshold(&mut self, threshold: f64) -> &mut Self …
```
=> fix(transport/bench): increase transfer bench noise threshold

.github/workflows/bench.yml
The docker and python caches put quite a bit of stress on the GHA cache, causing it - for example - to time out the benchmark results too soon. See https://github.com/mozilla/neqo/actions/caches
This makes sure we should have a fresh baseline benchmark in the cache for comparison.
Simpler than #1769
=> ci: Run a daily baseline benchmark of `main` for the cache

.github/workflows/check.yml, neqo-crypto/src/aead_fuzzing.rs, neqo-crypto/src/lib.rs, neqo-transport/benches/range_tracker.rs, neqo-transport/benches/rx_stream_orderer.rs, neqo-transport/benches/transfer.rs, neqo-transport/src/connection/tests/fuzzing.rs, neqo-transport/src/connection/tests/handshake.rs
Because it didn't get to have opinions about benches and various other code before that was hidden behind features. Avoids bitrot, too.
=> ci: Run `clippy` for all features except `gecko`

.github/actions/quic-interop-runner/action.yml
Follow-up to https://github.com/mozilla/neqo/pull/1743#discussion_r1525498120.
=> refactor(github/interop): use grep instead of awk

neqo-bin/src/bin/server/main.rs
Previously `neqo-server` would respond to a request by repeatedly sending a static 440 byte message (Major-General's Song). Instead of sending 440 bytes, increase the batch size to 4096 bytes. This also matches the `neqo-client` receive buffer size.
https://github.com/mozilla/neqo/blob/76630a5ebb6c6b94de6a40cf3f439b9a846f6ab7/neqo-bin/src/bin/client/http3.rs#L165
Previously `ResponseData::repeat` would convert the provided `buf: &[u8]` to ` Vec<u8>`, i.e. re-allocate the buf. Instead keep a reference to the original buf, thus removing the allocation.
---
Preliminary benchmark comparison:
`main`:
```
1-conn/1-100mb-resp (aka. Download)/client
time:   [768.10 ms 1.0894 s 1.5517 s]
thrpt:  [64.443 MiB/s 91.794 MiB/s 130.19 MiB/s]
```
this pull request:
```
1-conn/1-100mb-resp (aka. …
```
=> perf(bin/server): increase msg size and don't allocate msg per resp

neqo-transport/src/frame.rs, neqo-transport/src/packet/mod.rs
PR #1764 exports `frame` and `packet` if feature `fuzzing` is enabled. This apparently turns on a bunch of clippy checks that are not on by default? This PR fixes them.
One side effect is that this returns a bunch of `panic!`s into returning errors.
Made this separate from #1764 to reduce that PR's size.
=> fix: Address more clippy warnings

.github/workflows/scorecard.yml
Let's see what [this](https://github.com/ossf/scorecard) will report on our code...
=> ci: Enable the `ossf/scorecard` action

neqo-transport/src/connection/mod.rs, neqo-transport/src/packet/mod.rs, neqo-transport/tests/common/mod.rs, neqo-transport/tests/connection.rs
=> fix: Exit with `ProtocolViolation` if a packet has no frames

neqo-transport/src/connection/state.rs
CI paniced in `StateSignaling::handshake_done` called from `Connection::handle_lost_packets`. Unable to reproduce locally. To ease debugging future CI failures, print the current state on panic.
```
thread 'idle_timeout_crazy_rtt' panicked at neqo-transport\src\connection\state.rs:212:13:
StateSignaling must be in Idle state.
stack backtrace:
0: std::panicking::begin_panic_handler
at /rustc/8df7e723ea729a7f917501cc2d91d640b7021373/library\std\src\panicking.rs:646
1: core::panicking::panic_fmt
at /rustc/8df7e723ea729a7f917501cc2d91d640b7021373/library\core\src\panicking.rs:72
2: enum2$<neqo_transport::connection::state::StateSignaling>::handshake_done
at .\src\connection\state.rs:212
3: neqo_transport::connection::Connection::handle_lost_packets
at .\src\connection\mod.rs:2847
4: …
```
=> refactor: print current `StateSignaling` variant in `debug_assert`

.github/actions/quic-interop-runner/action.yml
In https://github.com/mozilla/neqo/pull/1785 the QUIC Network Simulator workflow failed.
https://github.com/mozilla/neqo/actions/runs/8523273988/job/23345192160?pr=1785
This triggers the QUIC Network Simulator Comment workflow.
https://github.com/mozilla/neqo/actions/runs/8524906268
Though currently, the former does not upload the _comment_ artifact on failure, which is to be consumed by the latter.
This commit makes the former always upload the comment data, such that the latter can consume it on failure.
=> ci(interop/action): always upload comment data

neqo-http3/src/connection_client.rs, neqo-transport/src/connection/mod.rs
The `Connection::process_input` and `Connection::process_multiple_input` functions are identical, except that the latter handles multiple `Datagram`s.
To avoid any changes to one without updating the other, have `process_input` simply delegate to `process_multiple_input`.
Commit also does the equivalent change to `neqo_http3::Http3Client`.
---
I would be surprised if `std::iter::once` adds a performance hit. Let's see what the benchmarks say.
=> refactor: have process_input delegate to process_multiple_input

neqo-bin/benches/main.rs, neqo-bin/src/client/mod.rs
The "100-seq-conn/1-1b-resp (aka. HPS)" benchmark supposedly measures the time for 100 uniform handshakes. Though `neqo-client` by default uses a resumption token for zero RTT if available. Thus the first is a normal and all following 99 handshakes are a zero RTT handshake.
To simplify the benchmark and to measure the same handshake type, establish a single connection within the benchmark function and have criterion do all the iterating.
---
Benchmark introduced in https://github.com/mozilla/neqo/pull/1758.
=> fix(bin): benchmark HPS without zero RTT

neqo-bin/benches/main.rs
The benchmark is using the default concurrency factor. By default `neqo-client` runs up to `100` requests in parallel.
https://github.com/mozilla/neqo/blob/5dfe106669ccb695187511305c21b8e8a8775e91/neqo-bin/src/client/mod.rs#L151-L153
Thus the benchmark name is wrong, i.e. the requests are run in parallel and not sequentially.
---
Sorry for the all noise for such a minor change.
=> fix(bin/bench): rename 1-conn/10_000-1b-seq-resp to parallel

neqo-crypto/src/time.rs, neqo-qpack/src/table.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet/mod.rs
`u64::max_value()` -> `u64::MAX`
=> chore: Fix clippy `usage of a legacy numeric method`

neqo-http3/src/connection.rs, neqo-http3/src/connection_server.rs
`<SendMessage as Sendstream>::send_data` attempts to send a slice of data down into the QUIC layer, more specifically `neqo_transport::Connection::stream_send_atomic`.
While it attempts to send any existing buffered data at the http3 layer first, it does not itself fill the http3 layer buffer, but instead only sends data, if the lower QUIC layer has capacity, i.e. only if it can send the data down to the QUIC layer right away.
https://github.com/mozilla/neqo/blob/5dfe106669ccb695187511305c21b8e8a8775e91/neqo-http3/src/send_message.rs#L168-L221
`<SendMessage as Sendstream>::send_data` is called via `Http3ServerHandler::send_data`. The wrapper first marks the stream as `stream_has_pending_data`, marks itself as `needs_processing` and then calls down into `<SendMessage as …
=> fix(http3): only add to stream_has_pending_data on has_data_to_send

neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs, neqo-http3/src/connection_client.rs, neqo-transport/src/connection/mod.rs
`neqo_transport::Connection` offers 4 process methods:
- `process`
- `process_output`
- `process_input`
- `process_multiple_input`
Where `process` is a wrapper around `process_input` and `process_output` calling both in sequence.
https://github.com/mozilla/neqo/blob/5dfe106669ccb695187511305c21b8e8a8775e91/neqo-transport/src/connection/mod.rs#L1099-L1107
Where `process_input` delegates to `process_multiple_input`.
https://github.com/mozilla/neqo/blob/5dfe106669ccb695187511305c21b8e8a8775e91/neqo-transport/src/connection/mod.rs#L979-L1000
Previously `neqo-client` would use `process` only. Thus continuously interleaving output and input. Say `neqo-client` would have multiple datagrams buffered through a GRO read, it could potentially have to do a write in between each `process` calls, as …
=> refactor(client): use process_output and process_multiple_input

neqo-common/Cargo.toml, neqo-common/benches/timer.rs, neqo-common/src/lib.rs, neqo-common/src/timer.rs, neqo-transport/src/server.rs
It appears that PR #1784 caused some [test failures](https://treeherder.mozilla.org/jobs?repo=try&revision=a0f4127144add8869a3297beb2562a5b8069abbc) (failed tests on windows). After reverting it, all http3 tests are [passed](https://treeherder.mozilla.org/jobs?repo=try&revision=c20146ce755c3926174142aeb0071290931d3818).
Given that we are reaching the end of this cycle, I think it's probably better to revert PR #1784 first and do a proper fix later.
=> Revert "perf(transport): remove Server::timers (#1784)"

neqo-transport/src/connection/mod.rs
And as a side effect, remove `output_close()`.
=> fix: Correctly track sent `CONNECTION_CLOSE` frames

.github/actions/pr-comment/action.yml, .github/actions/quic-interop-runner/action.yml, .github/workflows/bench-comment.yml, .github/workflows/qns-comment.yml
~~Because we only add one when there is a failure, and when things then later get fixed we don't update it again (because we skip the update on success). So the outdated, failed state keeps being shown.~~
Because if we only update on failure, we keep showing the last-failed state after success.
=> ci: Delete QNS PR comment on successful run

neqo-bin/src/server/mod.rs, neqo-bin/src/server/old_https.rs
As part of the QUIC Interop testcases, a server needs to be able to respond to a request with the content of a local file.
Previously, when failing to read a file, the server would simply reply with the predefined `SELF::MESSAGE`.
Now the server logs the error and moves on.
=> fix(server): log error when failing to read file

.github/workflows/qns.yml, neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs
The QUIC Interop Runner `keyupdate` testcase has a client establish a connection to the server and then trigger a key update.
https://github.com/quic-interop/quic-interop-runner/blob/2a2534a1284d50d99ff92884d4f1ecf98fb41e4c/testcases.py#L889
This testcase always uses the `http09` client and server implementation.
This commit simplifies the testcase implementation:
- Given that it is only used with `http09`, move it to `http09.rs`.
- Reduce the `KeyUpdateState` `struct` to a single `bool`.
- Mark the `--key-update` command line argument as hidden, given that it is only set indirectly through the `-t keyupdate` flag.
- Try to run `client.initiate_key_update` on events only, not on every new received datagram.
In addition it enables the `keyupdate` test on the Neqo `qns.yml` CI workflow.
=> refactor(client): simplify keyupdate testcase implementation

neqo-transport/src/cc/classic_cc.rs
=> fix: Correctly manage `bytes_in_flight` during a rebinding event

Cargo.toml
=> neqo v0.7.5

neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs, neqo-bin/src/server/mod.rs, neqo-bin/src/server/old_https.rs, neqo-transport/src/server.rs, neqo-transport/tests/server.rs
A call to `process_*` can emit events as a side effect, e.g. a `ConnectionEvent::StateChange(State::Connected)`. These are not returned from the function call, but instead internally enqueued to be later on consumed through the various `Provider::next_event` implementations.
https://github.com/mozilla/neqo/blob/166b84c5a3307d678f38d9994af9b56b68c6b695/neqo-common/src/event.rs#L9-L15
In the case of `neqo-client` the events are consumed through `self.handler.handle` which internally calls `Provider::next_event`.
A client or server should not go to sleep, waiting for either a UDP datagram to arrive or a timeout to fire, when there are events available.
This commit ensures `ready().await` is only called when no events are available.
---
Extracted from …
=> fix(bin): don't sleep when events available

neqo-transport/src/send_stream.rs
`SendStream::send_internal` starts off with a check to `buf.is_empty`.
https://github.com/mozilla/neqo/blob/cf0009842dade14a52416180f94a2dc507cd867a/neqo-transport/src/send_stream.rs#L1252-L1256
Thus the following `buf.is_empty` check isn't necessary.
https://github.com/mozilla/neqo/blob/cf0009842dade14a52416180f94a2dc507cd867a/neqo-transport/src/send_stream.rs#L1272
=> refactor(SendStream): remove duplicate buf.is_empty check

neqo-bin/benches/main.rs
The `neqo-bin` benchmarks spin up a `neqo-server` and then run various different client scenarios against it. Once done, they send the `neqo-server` a signal to terminate.
In case the server terminates early (e.g. due to an error), surface it to the user.
=> bench(bin): panic when server terminates

neqo-transport/src/send_stream.rs
With recent Rust versions, the Rust borrow-checker has become more capable, especially when it comes to borrowing subsets of `self`.
This commit removes the no longer necessary borrow-checker work-around.
---
Sorry for the many tiny pull requests today. Let me know if you don't think they are worth the noise.
=> refactor(SendStream): remove borrow-checker work-around

.github/actions/quic-interop-runner/action.yml
=> fix: Rework QNS tables

.github/actions/pr-comment-data-export/action.yml, .github/actions/pr-comment/action.yml
=> ci: Handle empty `log-url` when commenting on PRs

.github/workflows/qns.yml, neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs
https://github.com/mozilla/neqo/pull/1676 ensured for the client to wait for a resumption token from the server if one is needed, that is when running the `resumption` QUIC Interop testcase. #1676 accidentally removed the fallback using a session ticked if no resumption token was available.
https://github.com/mozilla/neqo/pull/1676/files#diff-64d071700a607884926de1b2caaf1588558fceda6d3a0e899cfb3c3b7e5ae41fL1353-L1359
This commit re-introduces the fallback and enables the `resumption` QUIC Interop testcase on CI.
Along the way, it simplifies `Runner::run` and reserves the `resume` command line argument for the QUIC Interop testcases only. Let me know if this adds too much noise to the actual fix. Happy to extract it into a separate pull request.
---
Test failure reported in …
=> fix(qns): fallback if server is not sending NEW_TOKEN

neqo-bin/src/client/mod.rs, neqo-bin/src/lib.rs, neqo-bin/src/server/mod.rs
There are two ways to specify the maximum log level of `neqo-server` and `neqo-client`. Via the `RUST_LOG` environment variable and since https://github.com/mozilla/neqo/pull/1692 via the verbosity flags (e.g. `-v`).
Previously, if no verbosity flag was provided, `INFO` was set as the maximum log level, the `RUST_LOG` environment variable was simply ignored.
With this commit, if no flag is set, the `RUST_LOG` environment variable is considered, and only then the `env_logger` crate default value (`ERROR`) is used.
In other words, the precedence order now is:
1. command line flags (e.g. `-v`)
2. `RUST_LOG` environment variable
3. default `ERROR` level
---
Among other places, ensures the `RUST_LOG=debug` in the QUIC Interop tests isn't ignored. …
=> fix(bin): consider env when no verbosity flag is set

test/test.sh
Might have been changed by #1848
=> test: Make `test.sh` more verbose again

neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs, neqo-transport/src/lib.rs
The `bin/src/client/mod.rs` `Runner::run` function continuously checks whether there is more work. In case there is none, it initiates closing of the connection (`self.client.close`) and then `continue`s to the top of the loop in order to send out a closing frame.
https://github.com/mozilla/neqo/blob/14cafbaa7fa88434def2c1d19e932c08e00173f8/neqo-bin/src/client/mod.rs#L376-L409
There is a potential busy loop when closing an already closing connection. `Runner::run` will call `self.client.close` and then continously `continue` to the top of the loop.
This commit differentiates a connection state in `NotClosing`, `Closing` and `Closed`. It only attempts to close a `NotClosing` connection and only then `continue`s to the top of the loop.
---
Fixes https://github.com/mozilla/neqo/issues/1864.
=> fix(bin/client): don't close closing connection

neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs, neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/features/extended_connect/tests/webtransport/negotiation.rs, neqo-http3/src/server.rs, neqo-http3/tests/httpconn.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/state.rs, neqo-transport/src/connection/tests/close.rs, neqo-transport/src/connection/tests/datagram.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/keys.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/connection/tests/vn.rs, neqo-transport/src/events.rs, neqo-transport/src/frame.rs, neqo-transport/src/lib.rs, neqo-transport/tests/connection.rs, neqo-transport/tests/network.rs, neqo-transport/tests/retry.rs, neqo-transport/tests/server.rs
The `neqo_transport::ConnectionError` enum contains the two non-error variants `Error::NoError` and `CloseReason::Application(0)`. In other words, `ConnectionError` contains variants that are not errors.
This commit renames `ConnectionError` to the more descriptive name `CloseReason`.
See suggestion in https://github.com/mozilla/neqo/pull/1866#issuecomment-2091654649.
To ease the upgrade for downstream users, this commit adds a deprecated `ConnectionError`, guiding users to rename to `CloseReason` via a deprecation warning.
``` rust
#[deprecated(note = "use `CloseReason` instead")]
pub type ConnectionError = CloseReason;
```
=> refactor: rename ConnectionError to CloseReason

neqo-http3/src/buffered_send_stream.rs, neqo-http3/src/send_message.rs
`neqo_http3::SendMessage` calls `qlog::h3_data_moved_down()` whenever it moves data down to the QUIC layer. `SendMessage` moves data down to the QUIC layer either directly via `self.stream.send_atomic` or indirectly buffered through `self.stream.send_buffer`.
Previously only one of the 3 calls to `self.stream.send_buffer` would thereafter call `qlog::h3_data_moved_down()`.
Calls missing the follow-up qlog call:
- https://github.com/mozilla/neqo/blob/ed19eb229d0d80fdbd0e1581488abd9cd1a73be7/neqo-http3/src/send_message.rs#L173
- https://github.com/mozilla/neqo/blob/ed19eb229d0d80fdbd0e1581488abd9cd1a73be7/neqo-http3/src/send_message.rs#L303
This commit moves the `h3_data_moved_down` call into `self.stream.send_buffer`, thus ensuring the function is always called when data is moved. In …
=> fix(http3): always qlog on send_buffer()

.github/workflows/qns.yml
It's too complex, and we should instead just fix the interop issues.
=> ci: Remove CI code to show differential QNS results

neqo-http3/src/send_message.rs, neqo-http3/src/server_events.rs, neqo-http3/tests/httpconn.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/fc.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/streams.rs
Previously `SendMessage::send_data` could stall, if less than the minimum message size is available to be sent. See
https://github.com/mozilla/neqo/issues/1819 for details.
This commit implements solution (3) proposed in
https://github.com/mozilla/neqo/issues/1819.
This commit introduces `SendStream::set_writable_event_low_watermark` which is then used in `SendMessage::send_data` to signal to `SendStream` the minimum required send space (low watermark) for the next send. Once reached, `SendStream` emits a `SendStreamWritable` event, eventually triggering another `SendMessage::send_data`.
Alternative to https://github.com/mozilla/neqo/pull/1835. Compared to https://github.com/mozilla/neqo/pull/1835, this fix does not utilize the `SendMessage` buffer, thus does not introduce an indirection …
=> fix(SendMessage): use SendStream::set_writable_event_low_watermark

fuzz/build.rs, neqo-common/Cargo.toml, neqo-crypto/Cargo.toml, neqo-crypto/build.rs, neqo-http3/src/server.rs, neqo-http3/tests/httpconn.rs, neqo-transport/build.rs
This should fix the CI errors that have started to appear as of today.
=> chore: Fix new clippy lints in cargo 1.80.0-nightly

neqo-bin/src/server/http09.rs, neqo-bin/src/server/http3.rs, neqo-bin/src/server/mod.rs
The QUIC Interop Runner requires an http3 and http09 implementation for both client and server. The client code is already structured into an http3 and an http09 implementation since https://github.com/mozilla/neqo/pull/1727.
This commit does the same for the server side, i.e. splits the http3 and http09 implementation into separate Rust modules.
=> refactor(bin): introduce server/http3.rs and server/http09.rs

.github/workflows/firefox.yml
And not when landing a PR in `main`. Can manually make it build for main via `workflow_dispatch`.
=> ci: Only build Fx for PRs

.github/workflows/bench.yml
By default. Makes the perf PR comment a bit more concise. [See below.](https://github.com/mozilla/neqo/pull/1906#issuecomment-2114951843)
=> ci: Only show performance improvements and regressions details

.github/workflows/bench.yml
Because I've also limited the loopback MTU to 1500 as part of the machine config.
=> ci: Reduce bench transfer size to 32MB

.github/workflows/check.yml
So that logging-related code is being included in the coverage check.
=> ci: Set `RUST_LOG` during coverage tests

neqo-bin/src/server/http09.rs
=> fix: Don't initialize regex on each call to `stream_readable`

.github/actions/rust/action.yml
Since latter just bumped its MSRV way beyond what is reasonable for us.
=> ci: Use cargo-quickinstall instead of cargo-binstall

.github/actions/rust/action.yml
Since binstall is having issues on macOS it seems.
=> ci: Only use cargo-quickinstall

fuzz/fuzz_targets/client_initial.rs, fuzz/fuzz_targets/server_initial.rs, neqo-bin/src/udp.rs, neqo-common/src/datagram.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/path.rs, neqo-transport/src/server.rs, neqo-transport/tests/connection.rs, neqo-transport/tests/retry.rs, neqo-transport/tests/server.rs, test-fixture/src/lib.rs
https://github.com/mozilla/neqo/pull/1568 introduced TTL information to datagrams. On the input path it would take the ttl information, but not act on it. On the output path it would set only "the default TTL on many OSes".
https://github.com/mozilla/neqo/blob/66504908e5fa070a8a5fa67d8b5a201d2c9a5cc5/neqo-transport/src/path.rs#L576
This commit removes the ttl information from `Datagram`, thus reverting a subset of https://github.com/mozilla/neqo/pull/1568.
This is partially motivated by https://github.com/mozilla/neqo/pull/1920, introducing `quinn-udp` as the IO library of choice, which does not support reading and writing TTL.
See also discussion in https://github.com/mozilla/neqo/pull/1920#discussion_r1644113749.
=> revert: remove ttl information from datagram

neqo-crypto/tests/init.rs
They seem to have a race condition that makes them crash.
Fixes #1839.
I wasn't able to figure out why they crash, this seems to happen inside NSS:
```
Process 47677 stopped
* thread #2, name = 'init_twice_withdb', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
frame #0: 0x000000019b4994f8 libsystem_pthread.dylib`pthread_mutex_lock + 12
libsystem_pthread.dylib`pthread_mutex_lock:
->  0x19b4994f8 <+12>: ldr    x8, [x0]
0x19b4994fc <+16>: mov    w9, #0x545a ; =21594
0x19b499500 <+20>: movk   w9, #0x4d55, lsl #16
0x19b499504 <+24>: cmp    x8, x9
(lldb) up
frame #1: 0x0000000100802f58 libnspr4.dylib`PR_Lock + 20
libnspr4.dylib`PR_Lock:
->  0x100802f58 <+20>: bl     0x10080c0c0    ; symbol stub for: pthread_self
0x100802f5c <+24>: str    x0, [x19, #0xb8]
0x100802f60 <+28>: mov    w8, #0x1 …
```
=> fix: Remove the "init NSS twice" tests

neqo-transport/tests/server.rs
This commit adds a basic test, passing a short header packet to a fresh server, expecting the server to drop the packet for the unknown connection.
More specifically, it tests this code path:
https://github.com/mozilla/neqo/blob/c9ff46e2e57730bcc626aacfb00d1c462a35f631/neqo-transport/src/server.rs#L564-L568
=> test(server): drop short header packet for unknown connection

.github/workflows/bench.yml
So the `<details>` stuff works properly. Hopefully.
=> ci: Fix bench comment formatting regex

neqo-transport/src/path.rs, neqo-transport/src/server.rs
See corresponding lints:
- https://rust-lang.github.io/rust-clippy/master/index.html#/mutable_key_type
- https://rust-lang.github.io/rust-clippy/master/index.html#/manual_inspect
See recent CI failure:
https://github.com/mozilla/neqo/actions/runs/9759065486/job/26934981259
```
error:
--> neqo-transport/src/path.rs:214:62
|
214 |         let old_path = self.primary.replace(Rc::clone(path)).map(|old| {
|                                                              ^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_inspect
= note: `-D clippy::manual-inspect` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::manual_inspect)]`
help: try
|
214 ~         let old_path = …
```
=> chore: address nightly clippy lints

neqo-udp/Cargo.toml
Set `bench = false`. By default cargo will use `libtest` for benchmarking. Executing a `cargo bench` with criterion specific command line flags at the workspace level will thus trigger an error when executing the `neqo-udp` benchmarks.
Follow-up to https://github.com/mozilla/neqo/pull/1920.
=> chore(udp): disable bench

.pre-commit-config.yaml
Not needed, and install fails on macOS for me.
=> fix: Disable pylint pre-commit check

.github/workflows/dependency-review.yml
So the `merge_group` trigger works.
=> ci: Bump action versions for dependency-review

Cargo.toml
=> neqo 0.8.0

.github/actions/rust/action.yml, .github/workflows/check.yml, fuzz/fuzz_targets/client_initial.rs, fuzz/fuzz_targets/server_initial.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/connection_server.rs
And check them during CI, so they keep building.
=> ci: Fix the fuzz targets

.github/actions/rust/action.yml, .github/workflows/check.yml, neqo-bin/Cargo.toml, neqo-common/Cargo.toml, neqo-http3/Cargo.toml, neqo-qpack/Cargo.toml, neqo-udp/Cargo.toml, test-fixture/Cargo.toml
=> ci: Use cargo-machete to check for unused dependencies

.github/workflows/bench.yml, .github/workflows/check.yml, .github/workflows/firefox.yml, .github/workflows/mutants.yml, .github/workflows/pr-comment.yml, .github/workflows/qns.yml
=> ci: Trigger secondary checks off `check.yml`

.github/actions/quic-interop-runner/action.yml
So we get an indication of which test might be hanging/slow. `tee` is otherwise not printing anything until the very end.
=> ci: Run QNS with unbuffered output

neqo-bin/src/server/http09.rs, neqo-http3/src/server.rs, neqo-http3/src/server_events.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/server.rs, neqo-transport/tests/common/mod.rs, neqo-transport/tests/retry.rs, neqo-transport/tests/server.rs, test-fixture/src/header_protection.rs
A `neqo_transport::Server` manages multiple `neqo_transport::Connection`s. A `Server` keeps a `HashMap` of all `Connection`s, indexed by `ConnectionId`.
Indexing by `ConnectionId` is difficult as:
- The `ConnectionId` is not known before constructing the connection.
- The `ConnectionId` might change throughout the lifetime of a connection.
Previously the index was kept up-to-date through a wrapper around the `ConnectionIdGenerator` provided to a `Connection` by a `Server`. This wrapper would be provided a shared reference to the `Server`s `HashMap` of `Connection`s. Whenever the `Server` would `process` a `Connection` and that `Connection` would generate a new `ConnectionId` via `ConnectionIdGenerator::generate_cid`, the wrapped `ConnectionIdGenerator` would also insert the `Connection` …
=> refactor(server): remove ServerConnectionIdGenerator

neqo-bin/Cargo.toml, neqo-bin/src/client/mod.rs, neqo-bin/src/lib.rs, neqo-bin/src/server/mod.rs, neqo-bin/src/udp.rs, neqo-udp/Cargo.toml, neqo-udp/src/lib.rs
`neqo-udp` is used in Firefox. Firefox uses `cargo vet` to audit its dependencies. `tokio`, the dependency of `neqo-udp`, is not audited as `safe-to-deploy`. `cargo vet` will require `safe-to-deploy` for `tokio` even when behind a feature flag.
To work around this limitation in `cargo vet`, drop `tokio` dependency in `neqo-udp`, moving `tokio` specific logic into `neqo-bin`.
See details in:
- https://github.com/mozilla/cargo-vet/issues/626
- https://bugzilla.mozilla.org/show_bug.cgi?id=1907810
- https://phabricator.services.mozilla.com/D212959#inline-1194604
=> chore(neqo-udp): drop tokio dependency

neqo-udp/src/lib.rs
`quinn_udp::UdpSocketState` sets the the OS socket to non-blocking in order to be used by poll based runtimes like `tokio`.
For basic unit tests, this might result in race conditions, e.g. where one socket tries to receive before the other is done sending, thus returning `WouldBlock`.
This commit sets the OS sockets back to blocking on `neqo-udp` unit tests.
---
Fixes https://github.com/mozilla/neqo/issues/2001.
Taken from [`quinn-udp`](https://github.com/quinn-rs/quinn/blob/ff91ffe8154e2ff1137ff8d29cd7ca5fd1030452/quinn-udp/tests/tests.rs#L187-L188).
=> fix(udp): test blocking Socket

Cargo.toml, neqo-bin/Cargo.toml, neqo-udp/Cargo.toml
This pull request contains 3 commits, where the first two build up to the second:
- deps(quinn-udp): move to workspace dependency
- deps(quinn-udp): bump to latest version
- deps(quinn-udp): enable direct-log feature
https://github.com/quinn-rs/quinn/pull/1923 made the `tracing` dependency optional. In addition, when `direct-log` is enabled, it allows using `log` instead of `tracing` for logging.
=> deps(quinn-udp): enable `direct-log` feature to log via `log`

.github/workflows/bench.yml, neqo-transport/benches/transfer.rs
Might help debug https://github.com/mozilla/neqo/pull/1998.
Does reproduce regression described in https://github.com/mozilla/neqo/pull/1998.
=> bench(transfer): run with and without pacing

neqo-bin/benches/main.rs
Have criterion determine the sample size based on warum-up run time instead.
---
Testing whether this will yield more dependable results.
Related to https://github.com/mozilla/neqo/pull/2008.
=> bench(bin): remove sample-size override

.github/workflows/bench.yml
In the following regex there are 6 capture groups.
```
perl -p -0777 -e 's/(.*?)\n(.*?)(((No change|Change within|Performance has).*?)(\nFound .*?)?)?\n\n/<details><summary>$1: $4<\/summary><pre>\n$2$4$6<\/pre><\/details>\n/gs' |\
```
Capture group 5 is nested within capture group 4:
```
((No change|Change within|Performance has).*?)
```
Instead of printing capture group 5, print capture group 4. As an example instead of printing
```
Performance has
```
Print
```
Performance has improved.
````
=> bench(.github): don't print capture group $4 twice 

neqo-transport/benches/transfer.rs
The `neqo-transport/benches/transfer.rs` benchmarks use the `test-fixture/src/sim` simulator. The simulator can travel in time, i.e. it simulates time.
The _wall-clock time_ of a single benchmark run is not the amount of time it took to transfer `TRANSFER_AMOUNT`. The _simulated time_ is the amount of time it took to transfer `TRANSFER_AMOUNT`.
`criterion` will use the _wall-clock time_, not the _simulated time_ to calculate the throughput based on `TRANSFER_AMOUNT`. The resulting throughput number is not meaningful.
This commit removes the call to `group.throughput`, thus removing the misleading `criterion` throughput reporting.
---
Related to https://github.com/mozilla/neqo/pull/1998.
=> fix(benches/transfer): remove throughput

.github/actions/nss/action.yml, neqo-transport/benches/transfer.rs
Because the script runs without `sudo` permissions. Deps must be installed by admin.
=> ci: Skip `sudo` runner steps on self-hosted runner

neqo-http3/src/connection_client.rs, neqo-http3/src/frames/tests/hframe.rs, neqo-http3/src/frames/tests/reader.rs, neqo-http3/src/frames/tests/wtframe.rs, neqo-http3/src/server.rs, neqo-http3/tests/httpconn.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/decoder_instructions.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/encoder_instructions.rs, neqo-qpack/src/header_block.rs, neqo-qpack/src/huffman.rs, neqo-qpack/src/qpack_send_buf.rs, neqo-transport/src/cc/tests/cubic.rs, neqo-transport/src/frame.rs, neqo-transport/src/send_stream.rs, neqo-transport/tests/connection.rs
To make @martinthomson happy :-)
=> chore: Remove `test_` from test names

neqo-transport/src/connection/tests/migration.rs
In the `path_forwarding_attack` unit test
``` rust
/// This simulates an attack where a valid packet is forwarded on
/// a different path.  This shows how both paths are probed and the
/// server eventually returns to the original path.
fn path_forwarding_attack() {
```
data is send on two paths, a IPv6 path (aka. "old") and an IPv4 path (aka. "new").
Towards the end of the test it asserts one path, but mentions the other in the doc comment.
This commit fixes the mix-up in the doc comment.
---
`new` and `old` is never quoted, but in the last two conflicting lines. Am I missing a special meaning of `old` vs. `"old"`?
Found while debugging https://github.com/mozilla/neqo/pull/2035.
=> docs(transport): fix old/new mixup

.github/workflows/qns.yml
`null` happens when a client or server is deemed "not compliant" by QNS
=> ci: Treat a QNS `null` result as a failure

neqo-bin/src/udp.rs, neqo-udp/src/lib.rs
When receiving an emtpy datagram `meta.len` and `meta.stride` would be `0`. Chunking the receive buffer via `.chunks(0)` would panic with:
```
chunk size must be non-zero
```
See also panic docs on `slice::chunks`:
https://doc.rust-lang.org/std/primitive.slice.html#method.chunks
With this commit `recv_inner` ignores the empty datagram.
In addition, under the assumption that an empty datagram is not a faulty event, `recv_inner` attempts another receive call on the socket. This ensures that the socket eventually returns `WouldBlock` and is thus registered for the next wake-up with the corresponding event loop (e.g. tokio).
---
Addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1911658.
Instead of ignoring empty datagrams, should they be passed to `neqo_transport`, e.g. in order to be …
=> fix(udp): ignore empty datagram

neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/pace.rs
Neqo assumes a timer granularity of 1ms:
https://github.com/mozilla/neqo/blob/0eb9174d7a67b250607f0c3ea056fe056bcf91f5/neqo-transport/src/rtt.rs#L25-L27
but `neqo_transport::Pacer::next()` might return values `< GRANULARITY`.
https://github.com/mozilla/neqo/blob/0eb9174d7a67b250607f0c3ea056fe056bcf91f5/neqo-transport/src/pace.rs#L71-L90
Under the assumption that a timer implementation rounds small values up to its granularity (e.g. 1ms), packets can be delayed significantly more than intended by `Pacer`.
With this commit `Pacer` does not delay packets that would previously be delayed by less than `GRANULARITY`. The downside is loss in pacing granularity.
See also:
- google/quiche
- https://github.com/google/quiche/blob/60aec87316d24392b2ea37c391ecf406ef183074/quiche/quic/core/congestion_co …
=> fix(transport): don't pace below timer granularity

Cargo.toml
Fixes https://github.com/mozilla/neqo/issues/2040.
Depends on https://github.com/mozilla/neqo/pull/2044.
=> chore: prepare v0.8.2 release

neqo-common/src/qlog.rs
Previously, on a `neqo-server` -> `neqo-client` transfer with qlog enabled, `neqo-client` would spend the majority of time writing to the qlog file.
Using a `BufWriter` `qlog` writing takes less than 3% of CPU time.
---
Depends on https://github.com/mozilla/neqo/pull/2031.
=> fix(common/qlog): use BufWriter

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/datagram.rs, neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/fc.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/pmtud.rs, neqo-transport/src/qlog.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tracking.rs
Avoid `unwrap` calls when accessing connection IDs.
Fixes #1429
=> fix: Check whether CIDs are empty

neqo-transport/src/recovery/mod.rs, neqo-transport/src/tracking.rs
Hopefully addresses @martinthomson's `TODO` about this.
=> feat: Use `EnumMap` for `AckTracker`

neqo-transport/src/connection/mod.rs, neqo-transport/src/tracking.rs
The crash signatures don't really give much of an indication of where exactly the issue is. Am kinda guessing it's this `unwrap` of the packet number space which was based on unverified network input (via `PacketNumberSpace::from`).
Possible fix for #1363.
=> fix: Check for error when looking up packet number space

neqo-common/src/qlog.rs
https://datatracker.ietf.org/doc/html/draft-ietf-quic-qlog-main-schema#section-7.1
=> fix: qlog `reference_time` should be in msec

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/state.rs
The current code doesn't seem to cause any packets to go out when closing, but is a bit wasteful (and also confused me when I saw timers fire in the logs...)
=> fix: Don't process timers during Closing or Draining

neqo-common/src/qlog.rs, neqo-crypto/src/lib.rs, neqo-transport/src/connection/tests/zerortt.rs
This currently fails, because we have a bug where the server does not accept retransmitted 0-RTT packets when it should.
=> test: Add a test case for 0-RTT loss

neqo-common/Cargo.toml, neqo-common/src/qlog.rs
Follow-up to https://github.com/mozilla/neqo/pull/2053.
=> refactor: drop time crate in favor of std::time::SystemTime

neqo-bin/src/client/mod.rs
PMTUD probes inflate what we sent in 1-RTT, causing QNS to fail the test.
See https://github.com/ptrd/kwik/issues/46#issuecomment-2299061674
=> fix: Turn off PMTUD during QNS `zerortt` test

neqo-bin/src/client/http09.rs
s2n-quic doesn't send a resumption token for the second connection in the QNS `resumption` test, and this caused us to fail.
=> fix: Don't stop handler if there is no resumption token

.github/actions/quic-interop-runner/action.yml
Because these artifacts are huge and those logs are not useful for debugging.
=> ci: Empty all QNS logs >5MB before artifact upload

neqo-transport/src/connection/tests/ecn.rs, neqo-transport/src/connection/tests/mod.rs
Add test coverage for validation failing on `Ect1`.
https://github.com/mozilla/neqo/blob/15cae9be1529e327e575fb7c799acc7521691337/neqo-transport/src/ecn.rs#L244-L246
See missing coverage reported in https://github.com/mozilla/neqo/pull/2072.
=> test(transport/ecn): cover disable on remark

neqo-common/Cargo.toml, neqo-common/src/hrtime.rs
The `winapi` crate isn't being updated anymore, and the `windows` crate is a more modern alternative maintained by Microsoft.
=> chore: Switch to the `windows` crate

neqo-transport/src/connection/tests/mod.rs
Previously `send_something_paced_with_modifier` would only apply the `modifier` if `sender.process_output` returned a `Output::Datagram` right away, but not when `sender.process_ouput` returned a datagram after returning a `Output::Callback`.
With this commit, `modifier` is always applied.
---
I am assuming this was the original intention of the function. Am I missing something?
=> test(transport/connection): apply modifier after Output::Callback

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/ecn.rs, neqo-transport/src/ecn.rs, neqo-transport/src/path.rs, neqo-transport/src/stats.rs
Adding 4 ECN metrics to `neqo-transport` `Stats`:
``` rust
/// Number of paths known to be ECN capable.
pub ecn_paths_capable: usize,
/// Number of paths known to be ECN incapable.
pub ecn_paths_not_capable: usize,
/// ECN counts for outgoing UDP datagrams, returned by remote through QUIC ACKs.
pub ecn_tx: EcnCount,
/// ECN counts for incoming UDP datagrams, read from IP TOS header.
pub ecn_rx: EcnCount,
```
---
Fixes https://github.com/mozilla/neqo/issues/2068.
Corresponding Phabricator Differential: https://phabricator.services.mozilla.com/D220062
=> feat(transport): add ecn metrics to Stats

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/ecn.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/ecn.rs, neqo-transport/src/path.rs
This will send `MAX_PATH_PROBES` probes with ECN and then another `MAX_PATH_PROBES` probes without ECN, so with `MAX_PATH_PROBES = 3`, a total of 6 for a non-functional path. Is that OK?
=> fix: Handle migrating to a path that is an ECN blackhole

Cargo.toml
I would like to bring https://github.com/mozilla/neqo/pull/2072/ to mozilla-central to be used in [phabricator#D220062](https://phabricator.services.mozilla.com/D220062) to enable [Fast UDP for Firefox - milestone 2 - ECN support](https://bugzilla.mozilla.org/show_bug.cgi?id=1902065).
~~Let's wait for https://github.com/mozilla/neqo/pull/2081 to merge first though.~~
Anything else? Any objections?
As always, given that cutting a Neqo release and landing it in mozilla-central is easy, I suggest blocking Neqo releases on bug fixes only.
=> chore: prepare v0.9.0 release

qns/Dockerfile
Via https://github.com/LukeMathWalker/cargo-chef
=> ci: Try and speed up QNS docker build

.github/workflows/firefox.yml
See https://bugzilla.mozilla.org/show_bug.cgi?id=1917407
=> ci: Use stable Rust to build Firefox

.github/actions/nss/action.yml
The MLKEM patches make the NSS build on Windows hang indefinitely. Until we fix that, pin NSS to the last working revision before MLKEM landed.
(Also switch to using `actions/checkout` and hence don't install mercurial anymore.)
CC @jschanck
=> ci: Pin NSS to prevent build hang on Windows

neqo-transport/src/connection/params.rs, neqo-transport/src/connection/tests/mod.rs
There was some plumbing missing. CC @mxinden
=> fix: Allow turning off greasing and connection migration

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/connection/tests/zerortt.rs, neqo-transport/src/path.rs, neqo-transport/src/pmtud.rs, neqo-transport/src/stats.rs
And just compute it on the fly. It wasn't consistently updated anyway and is only used in tests.
=> feat: Remove `FrameStats::all`

neqo-transport/src/connection/tests/handshake.rs
Follow-up to https://github.com/mozilla/neqo/pull/2100.
Test succeeds when run on top of https://github.com/mozilla/neqo/pull/2100.
@larseggert feel free to cherry-pick in case you find this useful.
=> test(transport): check local and remote GREASE_QUIC_BIT TP

neqo-bin/src/client/mod.rs
If we pace, we might get the initial server flight before sending sufficient 0-RTT data to pass the QNS check.
=> fix: Don't pace during QNS `zerortt` test

neqo-transport/src/recovery/mod.rs
Funtion is only used internally.
=> fix: Remove unnecessary `space` function

.github/actions/nss/action.yml, .github/actions/rust/action.yml
Without this, the second installation of the action in the same workflow - on WIndows only - fails with:
```
Error: Error: File was unable to be removed Error: EBUSY: resource busy or locked, rmdir 'C:\hostedtoolcache\windows\sccache\0.8.1\x64'
Error: File was unable to be removed Error: EBUSY: resource busy or locked, rmdir 'C:\hostedtoolcache\windows\sccache\0.8.1\x64'
```
=> ci: Only install sccache action once per workflow

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/resumption.rs, neqo-transport/src/path.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/rtt.rs
Because under lossy conditions (e.g., QNS `handshakeloss` test), the guess can be multiple times the actual RTT, which when encoded in the resumption ticket will cause an extremely slow second handshake, often causing the test to time out.
Fixes #2088
=> fix: Don't encode large RTT guesses in tickets

neqo-transport/src/connection/mod.rs
We don't track which packets are coalesced with others, so when we detect a loss in one packet number space, we cannot resend any coalesced packets in other packet number space. This PR tries to approximate this behavior by scheduling un-ACKed Handshake and 0-RTT packets for RTX when packets are lost in the Initial space.
=> fix: RTX more data during handshake

neqo-http3/src/features/extended_connect/webtransport_session.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/datagram.rs, neqo-transport/src/quic_datagrams.rs
`add_datagram` takes a Quic datagram and adds it to the queue of datagrams to be sent out. Previously it would take a reference (i.e. `&[u8]`) and would allocate it into a new `Vec<u8>` before enqueuing. At the call-site the original allocation (referenced by the `&[u8]`) would go out-of-scope and thus be de-allocated. This is a wasted allocation for each Quic datagram to be send.
This commit has the call-site pass the owned `Vec<u8>` down right away.
=> perf(transport): have add_datagram take Vec<u8>

test-fixture/src/lib.rs
This caused some test failures, and @martinthomson discovered this as the reason at the IETF 120 hackathon.
=> fix: Make anti-replay window 1s for tests

.github/workflows/check.yml, .github/workflows/clippy.yml, .github/workflows/firefox.yml
So that we get issues for platform-specific code.
Also change `macos-14` -> `macos-latest` everywhere.
=> ci: Run `clippy` on all platforms

neqo-transport/src/connection/mod.rs
`Connection::add_packet_number -> PacketBuilder::pn -> Encoder::encode_uint` panics when `pn_len` is `0`. These panics are seen in Firefox crash reports.
To be able to find the root cause of the panic, add additional metadata.
See https://github.com/mozilla/neqo/issues/2132 for details.
=> Extend panic when pn_len is 0 with metadata

.github/actions/nss/action.yml
When the system NSS version is sufficient:
https://github.com/mozilla/neqo/blob/55e3a9363c28632dfb29ce91c7712cab1f6a58da/.github/actions/nss/action.yml#L31
Then one must not set the environment variables pointing to a local copy:
https://github.com/mozilla/neqo/blob/55e3a9363c28632dfb29ce91c7712cab1f6a58da/.github/actions/nss/action.yml#L177-L190
Fixes https://github.com/mozilla/neqo/issues/2141.
=> ci(nss): handle system-, cached-, and to-be-build-NSS

neqo-transport/src/connection/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/rtt.rs
Rather than having the caller determine for which space a PTO should be calculated for.
Also arm PTOs in the application packet number space before the handshake is complete, so 0-RTT gets RTX'ed.
=> fix: Add `confirmed` parameter to PTO calculation

neqo-transport/src/recv_stream.rs
This is simpler code overall.  It might even be faster.  It certainly avoids an allocation.
=> Use retain to clear out old streams

neqo-http3/src/connection_client.rs, neqo-transport/src/connection/idle.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/idle.rs
=> make process_output be able to return keep_alive timeout

neqo-transport/src/lib.rs
As per the comment:
https://github.com/mozilla/neqo/blob/1708886bc9750677b1c43f4d8fc4b89367736198/neqo-transport/src/lib.rs#L102
=> chore: keep neqo_transport::Error internal errors sorted

neqo-transport/src/recovery/sent.rs
Test written while debugging https://bugzilla.mozilla.org/show_bug.cgi?id=1919678.
=> test(SentPackets): ignore unknown packet

.github/workflows/mutants.yml
And simplify the per-step conditions accordingly.
=> ci: Only run mutants workflow under certain conditions

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/datagram.rs, neqo-transport/src/connection/tests/migration.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/connection/tests/recovery.rs
This reduces boilerplate and encapsulates a good pattern of usage. I wasn't able to make `test_frame_writer` private, but this is close enough.
=> wrappers for common usage of test_frame_writer

Cargo.toml
I suggest we cut a new release once https://github.com/mozilla/neqo/pull/2150/ is merged.
https://github.com/mozilla/neqo/pull/2150/ will likely fix [bugzilla#1919678](https://bugzilla.mozilla.org/show_bug.cgi?id=1919678) which is currently "# 2 topcrash in Nightly 133".
=> chore: prepare v0.9.2 release

.github/workflows/actionlint.yml, .github/workflows/firefox.yml, qns/Dockerfile
To get our OSSF score up a bit.
=> ci: Try to pin more deps

.github/workflows/qns.yml
Also don't run it on a schedule anymore.
=> ci: Don't run QNS when a PR is merged

.github/workflows/check.yml, .github/workflows/sanitize.yml, Cargo.toml
This speeds up the matrix.
Also grab MSRV from `Cargo.toml` instead of hardcoding it.
=> ci: Run the sanitizers in parallel

.github/workflows/check.yml, .github/workflows/qns.yml, .github/workflows/sanitize.yml, test-fixture/src/sim/mod.rs, test-fixture/src/sim/rng.rs
Into the directory given in the `DUMP_SIMULATION_SEEDS` environment variable. Also, export them as artifacts from the CI runs.
Fixes #1645
=> test: Dump simulator RNG seeds

neqo-bin/src/client/mod.rs, neqo-bin/src/server/mod.rs
And a small bit of cleanup to avoid repetition.
=> feat: Plumbing to begin supporting QNS migration tests

qns/Dockerfile
So panic stack traces are useful.
=> fix: Build QNS docker image with debug symbols

neqo-bin/src/client/mod.rs, neqo-bin/src/server/mod.rs, neqo-bin/src/udp.rs, neqo-udp/src/lib.rs
`SocketAddr` implements `Copy`.
https://doc.rust-lang.org/std/net/enum.SocketAddr.html#impl-Copy-for-SocketAddr
Thus there is no need to pass by reference instead of by value.
Broken out of https://github.com/mozilla/neqo/pull/2093.
=> refactor(udp): pass SocketAddr instead of &SocketAddr

neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs, neqo-bin/src/server/mod.rs, neqo-bin/src/udp.rs
_Final pull request [stacked](https://github.com/marketplace/stacked-pull-requests) on top of https://github.com/mozilla/neqo/pull/2188 which is stacked on top of #2187 which is stacked on top of #2184._
Pass a long lived receive buffer to `neqo_udp::recv_inner`, receiving an iterator of `Datagram<&[u8]>`s pointing into that buffer, thus no longer allocating in UDP receive path.
---
Extracted out of #2093.
Part of #1693.
[Pull request stack](https://github.com/marketplace/stacked-pull-requests):
1. https://github.com/mozilla/neqo/pull/2184
2. https://github.com/mozilla/neqo/pull/2187
3. https://github.com/mozilla/neqo/pull/2188
4. (this one) https://github.com/mozilla/neqo/pull/2189
=> feat(bin): don't allocate in UDP recv path

.config/nextest.toml, .github/workflows/check.yml, .github/workflows/sanitize.yml
Terminating it ourselves means that later CI steps run (like exporting the simulator seeds), which doesn't happen when GitHub terminates the entire runner.
Also make simulation seed exporting work on Windows, while I'm here.
=> ci: Terminate `nextest` after a test runs for three minutes

neqo-bin/src/client/http09.rs, neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs, neqo-bin/src/server/mod.rs, neqo-bin/src/udp.rs, neqo-udp/src/lib.rs
_[Stacked](https://github.com/marketplace/stacked-pull-requests) on top of https://github.com/mozilla/neqo/pull/2187 which is stacked on top of https://github.com/mozilla/neqo/pull/2184._
Previously `recv_inner` would return `Datagram<Vec<u8>>`. In other words, it would allocate a new `Vec<u8>` for each UDP datagram payload.
Now `recv_inner` reads into a provided buffer and returns `Datagram<&[u8]>`, i.e. it returns a view into the provided buffer without allocating.
---
Extracted out of https://github.com/mozilla/neqo/pull/2093.
Part of https://github.com/mozilla/neqo/issues/1693.
[Pull request stack](https://github.com/marketplace/stacked-pull-requests):
1. https://github.com/mozilla/neqo/pull/2184
2. https://github.com/mozilla/neqo/pull/2187
3. (this one) …
=> feat(udp): return borrowed Datagram on receive

Cargo.toml
I would like to get https://github.com/mozilla/neqo/pull/2184 into Firefox.
Early integration looks promising.
While previously we would spend significant CPU time in allocating and de-allocating received `Datagram`s:
https://share.firefox.dev/40bq7Ka
None of this is present with `v0.10.0`:
https://share.firefox.dev/3NCMBfv
=> chore: prepare v0.10.0 release

README.md
Adds `neqo-bin` and `neqo-udp` to the `Trying in-development Neqo code in Gecko` section.
Also sorts the entries.
=> docs(README): add neqo-{bin,udp} to Cargo.toml patch section

neqo-bin/Cargo.toml, neqo-transport/Cargo.toml
Previously `neqo-bin`, `neqo-transport` and `test-fixtures` would each define a `bench` feature. But enabling e.g. `bench` in `neqo-transport` would not enable `bench` in `test-fixtures`. Thus a benchmark in e.g. `neqo-transport` with `--features bench` would still be serializing qlog traces.
This commit makes `neqo-bin` and `neqo-transport` forward their `bench` feature to `test-fixtures`.
=> fix: forward bench feature to test-fixtures crate

.github/workflows/dependency-review.yml
See https://github.com/mozilla/neqo/pull/2209#issuecomment-2449356165 for rational.
=> ci: update actions/dependency-review-action to v4.4.0

neqo-bin/src/client/http3.rs, neqo-bin/src/lib.rs, neqo-bin/src/send_data.rs, neqo-bin/src/server/http09.rs, neqo-bin/src/server/http3.rs, neqo-bin/src/server/mod.rs
When POSTing a large request to a server, don't allocate the entire request upfront, but instead, as is done in `neqo-bin/src/server/mod.rs`, iterate over a static buffer.
Reuses the same logic from `neqo-bin/src/server/mod.rs`, i.e. `SendData`.
See previous similar change on server side https://github.com/mozilla/neqo/pull/2008.
=> bench(bin/client): don't allocate upload payload upfront

Cargo.toml
Currently we use `quinn-udp` `v0.5.4`.
`quinn-udp` `v0.5.5` fixes [`recvmmsg` calls on Android x86](https://github.com/quinn-rs/quinn/pull/1966).
`quinn-udp` `v0.5.6` adds [experimental multi-message support on Apple platforms](https://github.com/quinn-rs/quinn/pull/1993) and [fixes an unnecessary `windows-sys` version restriction](https://github.com/quinn-rs/quinn/pull/2021).
While not strictly necessary, given that our current version specification (i.e. `version = "0.5.4"`) already allows users to use Neqo with `quinn-udp` `v0.5.6`, this commit updates to `quinn-udp` `v0.5.6` anyways, thus making sure CI tests with latest version.
In case https://github.com/mozilla/neqo/pull/2208 lands, future compatible version updates would touch the `Cargo.lock` file, not `Cargo.toml`.
=> chore: update to quinn-udp v0.5.6

neqo-bin/Cargo.toml, neqo-http3/Cargo.toml
`url` `v0.5.3` and `idna` `v1.0.3` added no-std support: https://github.com/servo/rust-url/pull/831
Since Neqo sets `default-features = false`, the above would break Neqo.
Related: https://github.com/servo/rust-url/pull/831
Sample CI failure: https://github.com/mozilla/neqo/actions/runs/11683021003/job/32531372545
=> deps: enable std feature of url crate

Cargo.toml, neqo-bin/Cargo.toml, neqo-http3/Cargo.toml
Follow-up to https://github.com/mozilla/neqo/pull/2219.
=> chore: make url crate a workspace dependency

.github/workflows/firefox.yml
Building Firefox in CI for every push is very slow and often fails when the glue hasn't been updated yet for a pending change.
=> ci: Only build Firefox on manual trigger

neqo-bin/src/server/http09.rs, neqo-bin/src/server/http3.rs, neqo-bin/src/server/mod.rs
Previously the `neqo-bin` server would read a set of datagrams from the socket and allocate them:
``` rust
let dgrams: Vec<Datagram> = dgrams.map(|d| d.to_owned()).collect();
```
This was done out of convenience, as handling `Datagram<&[u8]>`s, each borrowing from `self.recv_buf`, is hard to get right across multiple `&mut self` functions, that is here `self.run`, `self.process` and `self.find_socket`.
This commit combines `self.process` and `self.find_socket` and passes a socket index, instead of the read `Datagram`s from `self.run` to `self.process`, thus making the Rust borrow checker happy to handle borrowing `Datagram<&[u8]>`s
instead of owning `Datagram`s.
---
Follow-up to https://github.com/mozilla/neqo/pull/2184.
Fixes https://github.com/mozilla/neqo/issues/2190.
Hopefully speeds …
=> feat(bin): don't allocate in server UDP recv path

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/migration.rs
=> fix: Don't allow migration if the peer doesn't allow it

neqo-transport/src/streams.rs
Stuff like this is not needed when your borrow checker gets upgraded.
=> No need to borrow with a smarter borrow checker

neqo-udp/src/lib.rs
=> Use try_send, so the caller can handle the IO error

Cargo.toml
mozilla-central depends on `url` `v2.5.1`:
https://searchfox.org/mozilla-central/rev/6050bf4eca89956c9d91bfd89fa59294ae32a689/Cargo.lock#6715-6725
The latest version of `url` is `v2.5.3`, which cargo automatically updates to, given that `Cargo.lock` is not checked in.
`url` v0.2.5.3` introduced the `std` feature which breaks CI. https://github.com/mozilla/neqo/pull/2219 enabled the feature, unbreaking CI, but breaking mozilla-central, given that mozilla-central still uses `url` `v2.5.1` which does not have the the `std` feature.
This commit pins `url` to `v2.5.1` instead and removes the `std` feature.
---
Follow-up to https://github.com/mozilla/neqo/pull/2239#issuecomment-2485078742.
=> deps: pin url to v2.5.1

neqo-transport/benches/range_tracker.rs
Given that there is a `black_box` function in `criterion`, I assume this doc comment is a leftover commented out import.
https://docs.rs/criterion/latest/criterion/fn.black_box.html
=> chore(transport/bench): remove commented out import

neqo-transport/Cargo.toml, neqo-transport/benches/sent_packets.rs, neqo-transport/src/lib.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/recovery/sent.rs
This pull request extracts the benchmark from https://github.com/mozilla/neqo/pull/2245.
I suggest we merge here first. We can then compare https://github.com/mozilla/neqo/pull/2245 against its baseline on `main`.
Note the second separate commit, addressing clippy lints only (82ef97e24c5af3d5098f5b73bcd23c72a7b365b3).
=> bench(transport/recovery): benchmark `SentPackets::take_ranges`

.gitignore, Cargo.lock, neqo-common/Cargo.toml, neqo-common/benches/decoder.rs
This adds a fairly simple varint decoding benchmark to neqo-common.  The next patch will include some improvements to the decoder.
=> Add a benchmark for the decoder

.github/workflows/qns.yml
Because otherwise the `mv` command will fail.
=> ci: Delete `results-main` before `mv`

test-fixture/src/sim/mod.rs
A `Node` (e.g. a `Client`, `Server` or `TailDrop` router) can be in 3 states:
``` rust
enum NodeState {
/// The node just produced a datagram.  It should be activated again as soon as possible.
Active,
/// The node is waiting.
Waiting(Instant),
/// The node became idle.
Idle,
}
```
`NodeHolder::ready()` determines whether a `Node` is ready to be processed again. When `NodeState::Waiting`, it should only be ready when `t <= now`, i.e. the waiting time has passed, not `t >= now`.
``` rust
impl NodeHolder {
fn ready(&self, now: Instant) -> bool {
match self.state {
Active => true,
Waiting(t) => t <= now, // not >=
Idle => false,
}
}
}
```
The previous behavior lead to wastefull non-ready `Node`s being processed and thus a large test runtime when e.g. simulating a gbit connection …
=> fix(sim): correct `Waiting` state comparison in `NodeHolder::ready()`

neqo-transport/src/connection/tests/ecn.rs, neqo-transport/src/ecn.rs, neqo-transport/src/path.rs, neqo-transport/src/stats.rs
Expose the ECN path validation outcome via `neqo_transport::Stats`.
Closes https://github.com/mozilla/neqo/issues/2256.
=> feat(ecn): expose ECN path validation outcome in Stats

.github/workflows/check.yml
https://en.wikipedia.org/wiki/Code_coverage#Modified_condition/decision_coverage
The point of the PR is to make it easier to spot lines with partial coverage, which AFAICT currently show up as green.
MC/DC is finding some partially covered lines, so coverage drops. This is expected.
=> ci: Enable MC/DC coverage

Cargo.lock
Upstream release:
https://github.com/quinn-rs/quinn/releases/tag/quinn-udp-0.5.8
Downstream patch updating mozilla-central:
https://bugzilla.mozilla.org/show_bug.cgi?id=1935954
=> deps(Cargo.lock): update to quinn-udp v0.5.8

neqo-transport/src/server.rs, neqo-transport/tests/retry.rs, test-fixture/src/assertions.rs
Rather than using the TOS value from the incoming packet, which might have gotten ECN marked on the way in.
Also create a debug log entry for those packets that resembles that created by `dump_packet`.
=> fix: Send Retry and VN packets with default TOS

.github/workflows/check.yml
Documentation isn't super clear, but the JSON may contain more detailed info vs. the LCOV format.
=> ci: Use Codecov JSON format and include FFI

neqo-bin/src/client/mod.rs, neqo-common/src/qlog.rs, neqo-transport/src/server.rs, test-fixture/src/lib.rs
Hey Hey! 👋 
First time neqo contributor here!
I'm Oskar, working student on the necko team, for those that don't already know me 😄 
@mxinden was showing me qvis the other day and we noticed that description and title were just showing something the likes of `Example qlog [...]`. With this change they now show `Neqo [client|server] qlog`. 
I also added a `server-` prefix to the filename of the server qlogs as I found it hard to understand which was which at first glance, but happy to take that out again if it's not wanted.
I hope these small change are somewhat useful and would appreciate a review and maybe a pointer as to what I could work on next. I'm definitely very interested to work more on neqo! 🙂 
Cheers
Oskar
=> chore(qlog): Add meaningful qlog titles and descriptions.

.github/actions/rust/action.yml
Because newer versions have an MSRV > 1.76.
=> ci: Pin `cargo-quickinstall` to 0.3.5

neqo-bin/src/client/mod.rs, neqo-bin/src/lib.rs, neqo-bin/src/server/mod.rs, test/test.sh
It's redundant with `--alpn`.
Fixes #698
=> chore: Remove `--use-old-http` command line parameter

.github/workflows/sanitize.yml
See for example CI failure:
https://github.com/mozilla/neqo/actions/runs/12463815686/job/34786831894?pr=2300
=> ci(sanitize): ignore leak in std::rt::lang_start_internal

Cargo.lock
Corresponding mozilla-central patch: https://phabricator.services.mozilla.com/D232475
=> deps: update quinn-udp to v0.5.9

neqo-transport/src/recv_stream.rs
Doc comment describes return value, but function doesn't return anything.
=> docs(transport): remove obsolete comment

neqo-qpack/src/encoder.rs, neqo-qpack/src/table.rs
Previously we had `evict_to` and `can_evict_to`, where the former would actually evict values, whereas the latter would only check how much could be evicted. Both would delegate to `evict_to_internal`.
In the case of `evict_to`, `evict_to_internal` would look at the last entry, and evict it if possible, then repeat.
In the case of `can_evict_to`, `evict_to_internal` would look at the last value as well, and then repeat, but not actualy evict, thus continuously looking at the last entry, instead of all evictable entries.
This commit fixes `can_evict_to` by making it look at all evictable entries.
---
Partially fix https://github.com/mozilla/neqo/issues/2306.
=> fix(qpack): make `can_evict_to` iter all evictable entries 

Cargo.toml, neqo-bin/src/server/mod.rs, neqo-transport/src/recv_stream.rs
=> chore: Enable clippy `get_unwrap` lint

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/ecn.rs, neqo-transport/src/crypto.rs, neqo-transport/src/ecn.rs, neqo-transport/src/frame.rs, neqo-transport/src/lib.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/qlog.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/rtt.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/stats.rs, neqo-transport/src/tracking.rs, neqo-transport/src/version.rs
This pull-request does two things:
1. It removes `module_name_repetitions` in `neqo-transport/src/ecn.rs`
2. It prepares the rest of the `neqo-transport` crate for refactoring by removing the crate-wide 
`#![allow(clippy::module_name_repetitions)]` and adding them on a module-level where necessary
One thing I'd like some feedback on is that because we are explicitly only importing the things we need from a module (e.g. `use ecn::Info;`) it's not always as clear where things come from as it was described in https://github.com/mozilla/neqo/issues/2284#issuecomment-2571313915. See for example in `neqo-transport/src/path.rs` line 203:
```rust
let baseline = self.primary().map_or_else(
//            || EcnInfo::default().baseline(), <-- before refactor
|| Info::default().baseline(), // <-- …
```
=> chore(transport): Remove `module_name_repetitions`

Cargo.toml, neqo-bin/src/lib.rs
=> chore: Enable clippy `pathbuf_init_then_push` lint

.github/actions/rust/action.yml, .github/workflows/check.yml
Due to https://github.com/rust-lang/rust/issues/135235
=> ci: Pin nightly

Cargo.toml, neqo-transport/src/crypto.rs, neqo-transport/src/ecn.rs, neqo-transport/src/fc.rs, neqo-transport/src/tracking.rs, test-fixture/src/sim/connection.rs
=> chore: Enable the `renamed_function_params` lint

Cargo.lock, Cargo.toml, neqo-bin/src/client/mod.rs, neqo-bin/src/server/mod.rs, neqo-bin/src/udp.rs, neqo-udp/Cargo.toml, neqo-udp/build.rs, neqo-udp/src/lib.rs
Do multi-message receive via https://github.com/quinn-rs/quinn/pull/1993 on apple platforms.
---
Localhost benchmark (_Download_) with PMTUD disabled shows ~11% performance improvement.
```
$ critcmp main mmsg                                              
group                                         main                                   mmsg
-----                                         ----                                   ----
1-conn/1-100mb-resp (aka. Download)/client    1.11   790.5±12.51ms   126.5 MB/sec    1.00   711.5±31.65ms   140.5 MB/sec
```
Fixes https://github.com/mozilla/neqo/issues/2279.
=> perf(udp): multi-message receive on apple

Cargo.toml, neqo-crypto/src/agent.rs, neqo-http3/src/connection.rs, neqo-http3/src/recv_message.rs, neqo-transport/src/addr_valid.rs, neqo-transport/src/connection/mod.rs
And fix all the warnings that it generates.
=> chore: Enable the `ref_patterns` clippy lint

Cargo.toml, neqo-http3/src/frames/tests/mod.rs, neqo-transport/src/cc/tests/cubic.rs, neqo-transport/src/connection/tests/handshake.rs
And fix all the warnings it generates.
=> chore: Enable the `redundant_type_annotations` lint

Cargo.toml, neqo-http3/tests/priority.rs
And fix the lint errors in the codebase.
=> chore: Enable the `unneeded_field_pattern` lint

.github/actions/rust/action.yml
https://github.com/rust-lang/rust/issues/135235 is fixed
=> ci: Unpin nightly

neqo-udp/src/lib.rs
The `handle_empty_datagram` unit tests sends and receives an empty datagram. To prevent a race condition where the receiver tries to receive the datagram before it is available (error `WouldBlock`), use a blocking socket via `socket()` instead.
---
See e.g. CI failure in https://github.com/mozilla/neqo/actions/runs/12704862858/job/35414911552?pr=2133#step:5:3588.
=> tests(udp): use blocking socket to receive empty datagram

.github/workflows/bench.yml, .github/workflows/check.yml, .github/workflows/clippy.yml, .github/workflows/fuzz-bench.yml, .github/workflows/machete.yml, .github/workflows/rustfmt.yml, .github/workflows/sanitize.yml
1. `CARGO_TERM_COLOR: always` is always set by `dtolnay/rust-toolchain`
2. `RUST_BACKTRACE` is better set where needed, rather than everywhere.
=> ci: Remove some things from `env`

.github/workflows/check.yml
I keep finding that I need to flip a PR from "draft" to "ready for review" prematurely, just to get the CI to run benchmarks.
=> ci: Run benchmarks on draft PRs

neqo-transport/src/cc/classic_cc.rs
There is no single-packet version of `on_packets_acked`.
=> docs(transport/cc): remove obsolete comment

.deny.toml, .github/workflows/deny.yml
Oh wow, an action that is actually already allowlisted :-)
=> ci: Run `cargo-deny` during ci

neqo-transport/src/cc/cubic.rs
Improves documentation in general and adds references to the relevant sections of RFC 8312.
Once we update to RFC 9438 (https://github.com/mozilla/neqo/issues/1912), we should reference RFC 9438 instead.
=> docs(transport/cubic): add references to RFC 8312

neqo-common/src/qlog.rs
It fails if the runtime exceeds 10 seconds, which happens sometimes in CI, e.g., https://github.com/mozilla/neqo/actions/runs/12772087190/job/35600809738?pr=2295#step:7:231
=> ci: Fix the `add_event_with_instant` test

.github/actions/quic-interop-runner/action.yml, .github/workflows/qns.yml
It seems that the `TIMEOUT` env variable applies to all steps?
=> ci: Revamp the QNS CI action timeout

neqo-transport/src/connection/tests/stream.rs, neqo-transport/src/streams.rs
https://github.com/mozilla/neqo/pull/2269 made a "stream control or data frame for a stream that is ours to initiate but we haven't yet" illegal.
https://github.com/mozilla/neqo/blob/7bbf900874eb02171dd893810d6895e14ed516e3/neqo-transport/src/streams.rs#L409-L424
Given a remote initiated stream that has been closed and forgotten since. Say that the local node receives an out-of-order frame on said forgotten stream. In such scenario:
- `stream_id.is_remote_initiated` is `true`
- thus `existed` is `false`
- `ss.is_none()` and `rs.is_none()` is `true`
- `ss.is_none() && rs.is_none() && !existed` is `true`
- thus `obtain_stream` falsely returns `Err(Error::StreamStateError);`
This commit fixes the above issue, only returning `Err(Error::StreamStateError);` on locally initiated streams.
=> fix(transport): handle out-of-order frame on remote init stream

.github/workflows/sanitize.yml
This reverts commit c3ecaa666ffe27eb022044d4a452eb09f006f604.
---
With https://github.com/rust-lang/rust/pull/135484 merged, we should soon be able to revert here.
=> Revert "ci(sanitize): downgrade to ubuntu v22.04 (#2353)"

Cargo.lock, Cargo.toml
I would like to get the following pull requests into Firefox:
- https://github.com/mozilla/neqo/pull/2307
- https://github.com/mozilla/neqo/pull/2270
- https://github.com/mozilla/neqo/pull/2269
- https://github.com/mozilla/neqo/pull/2259
- https://github.com/mozilla/neqo/pull/2228
=> chore: prepare v0.12.0

Cargo.lock, Cargo.toml, neqo-common/Cargo.toml, neqo-common/src/log.rs
https://github.com/mozilla/neqo/pull/2291 added additional formatting to our log output via `env_logger`'s `auto-color` feature. The `auto-color` feature adds the `is-terminal` crate dependency. `is-terminal` depends on `hermit-abi` `v0.4`.
Pulling latest Neqo `v0.12.0` into mozilla-central adds `is-terminal` and `hermit-abi` `v0.4.0` to the Firefox dependency tree.
In order to keep our dependency footprint low, I suggest not enabling the two `env-logger` features.
@larseggert thoughts? Alternatively I can also audit the two dependencies and then introduce them into Firefox. That said, is it worth it?
=> deps(common/log): drop env_logger's auto-color and regex features

.github/workflows/check-vm.yml
Until we address the `FIXME`s.
=> ci: Disable failing VM actions in CI

neqo-bin/src/client/mod.rs, neqo-bin/src/lib.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/params.rs, neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/crypto.rs
Wireshark can't reassemble sliced CRYPTO frames, which causes QNS tests to fail bcause it then can't parse all packets.
This PR adds an option to disable SNI slicing, and we do so by default when running in QNS.
=> feat: Option to turn off SNI slicing

neqo-transport/src/connection/tests/vn.rs
`compatible_upgrade_large_initial` tests whether Neqo can handle an ACK using QUIC version Y on a connection that ends up using QUIC version X.
https://github.com/mozilla/neqo/pull/2228 changed the test, asserting that the server will drop 2 instead of 1 packet. This spuriosly fails on CI:
https://github.com/mozilla/neqo/actions/runs/12796212878/job/35675377711?pr=2295
This commit allows both 1 and 2 packets dropped by the server.
---
@larseggert based on your changes in https://github.com/mozilla/neqo/pull/2228/, is this a valid assumption to make?
=> test(transport/vn): allow dropped_rx of 1

Cargo.lock, Cargo.toml, neqo-transport/src/ecn.rs, neqo-transport/src/lib.rs, neqo-transport/tests/stats.rs
https://github.com/mozilla/neqo/pull/2270 added ECN path validation failure reasons to `neqo_transport::Stats`. I forgot to expose the `ValidationOutcome` and `ValidationError` `enum`s beyond the `neqo-transport` crate boundaries though. This is needed in order for `neqo_glue` in mozilla-central to convert them into Glean metrics.
This commit exposes the `neqo_transport::ecn` module and makes those types `pub(crate)` which are not needed outside of `neqo_transport`.
=> chore(transport): export ecn module

.github/workflows/check.yml
Because otherwise we can't diagnose failed tests.
=> ci: Always run `test-results-action` upload

.github/actions/rust/action.yml, .github/workflows/bench.yml, .github/workflows/check-vm.yml, .github/workflows/check.yml, .github/workflows/sanitize.yml, qns/Dockerfile, test/test.sh
Now that we have `Cargo.lock` in the repository, we can re-enable the `Swatinem/rust-cache` action. This should speed up the CI process.
Also apply some other suggestions from https://corrode.dev/blog/tips-for-faster-ci-builds/
=> ci: Re-enable `Swatinem/rust-cache`

.github/actions/rust/action.yml
Should unbreak CI.
See https://github.com/Swatinem/rust-cache/issues/204
=> ci: Use `--force` with `quickinstall` to work around caching issue

.github/actions/nss/action.yml, .github/actions/rust/action.yml, .github/workflows/bench.yml, .github/workflows/sanitize.yml
Let's see if this speeds things up more.
=> ci: Use`mold` linker on Linux, `lld` on Windows

neqo-transport/src/connection/mod.rs
Bug in #2294 spotted by @martinthomson in https://github.com/larseggert/neqo/commit/0eb7c5e89bf22a9e99350eb924523798f574da1f#r152054928
=> fix: `map_or` -> `map_err`

.github/workflows/qns.yml
Because `gcc` on `arm64` segfaults. Yay.
Also don't run QNS on push to `main` to save some cycles.
=> ci: Disable `arm64` docker image build

.github/workflows/actionlint.yml
It needs `security-events: write` to integrate with CodeQL.
=> ci: Give `zizmor` more permissions

.github/actions/rust/action.yml
=> ci: Check for `mold` before trying to install install

.github/actions/quic-interop-runner/action.yml, .github/workflows/qns.yml
OK, fixed. I managed to accidentally remove a backslash, which caused everything to explode. Put it back.
Also did a little bonus maintenance while I was here, by adding `tquic` and `openssl` to the interop matrix, and by using the correct highlighting for lines normally hidden under "All results".
I still hate GitHub CI.
=> ci: Fix QNS log failure

.github/workflows/bench.yml
Bash conditionals for return codes are inverted.
=> fix: Fix checking the Welch t-test

.github/workflows/check-vm.yml, .github/workflows/check.yml, .github/workflows/qns.yml, .github/workflows/sanitize.yml
Because they run a long time and aren't really necessary for PRs that only update dependencies.
=> ci: Disable some workflows for `dependabot` PRs

.github/workflows/bench.yml
Thanks you GitHub for wiping our cache so we could debug this issue.
=> ci: Don't fail the bench job if the cache is missing

.github/workflows/bench.yml
Otherwise the highlight for a significant change will stay in effect for following non-significant changes.
=> fix: Reset bench table highlights after each test

Cargo.lock, Cargo.toml, neqo-common/Cargo.toml, neqo-common/src/tos.rs, neqo-crypto/Cargo.toml, neqo-crypto/src/auth.rs, neqo-crypto/src/constants.rs, neqo-crypto/src/secrets.rs, neqo-crypto/src/ssl.rs, neqo-transport/Cargo.toml, neqo-transport/src/connection/mod.rs, neqo-transport/src/frame.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/tparams.rs, neqo-transport/src/tracking.rs
And remove some boilerplate code.
Fixes #2439
=> chore: Use `strum` macros

Cargo.lock, Cargo.toml, neqo-http3/Cargo.toml, neqo-transport/Cargo.toml, neqo-transport/src/recovery/mod.rs, neqo-transport/src/tracking.rs
For `PacketNumberSpaceSet`. May be faster?
=> chore: Use `EnumSet` instead of a Boolean `EnumMap`

Cargo.lock, Cargo.toml, neqo-http3/Cargo.toml, neqo-http3/benches/streams.rs, neqo-http3/tests/httpconn.rs, test-fixture/src/lib.rs
To see if the hasher changes in #2342 make sense.
Also remove some related redundancies in `test-fixture` while I'm here.
=> test: Add a bench for H3 streams

neqo-common/src/codec.rs, neqo-common/src/datagram.rs, neqo-common/src/header.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/agentio.rs, neqo-crypto/src/auth.rs, neqo-crypto/src/err.rs, neqo-crypto/src/p11.rs, neqo-crypto/src/secrets.rs, neqo-crypto/src/time.rs, neqo-http3/src/connection.rs, neqo-http3/src/features/extended_connect/webtransport_session.rs, neqo-http3/src/server_events.rs, neqo-qpack/src/table.rs, neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cid.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/crypto.rs, neqo-transport/src/packet/metadata.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/quic_datagrams.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/recovery/sent.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/tparams.rs, neqo-transport/src/version.rs
Ans suppress some false positives, see https://github.com/rust-lang/rust-clippy/issues/14091
=> chore: Fix clippy warnings

.github/workflows/bench.yml
They have been isolated per https://manuel.bernhardt.io/posts/2023-11-16-core-pinning/.
=> ci: Use CPUs 2 and 3 for benchmarking

README.md
In order to connect to a neqo-server with a self-signed certificate, one needs to set `network.http.http3.disable_when_third_party_roots_found` to `false`.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1925014 for details.
//CC @justus237
=> docs(README): mention `disable_when_third_party_roots_found` pref

README.md
Use `realpath` in order to export `LD_LIBRARY_PATH` with an absolute path to `libssl3.so` instead of a relative path.
---
I assume `realpath` is available on MacOS.
=> docs(README): export LD_LIBRARY_PATH with absolute not relative path

.github/workflows/actionlint.yml, .github/workflows/check-vm.yml, .github/workflows/check.yml, .github/workflows/clippy.yml, .github/workflows/deny.yml, .github/workflows/dependency-review.yml, .github/workflows/firefox.yml, .github/workflows/fuzz-bench.yml, .github/workflows/machete.yml, .github/workflows/mutants.yml, .github/workflows/pr-comment.yml, .github/workflows/qns.yml, .github/workflows/rustfmt.yml, .github/workflows/sanitize.yml
Fixes https://github.com/mozilla/neqo/issues/2480.
See [GitHub docs for latest runner versions](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for--private-repositories).
=> ci: pin GitHub-hosted runners OS versions

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/params.rs, neqo-transport/src/connection/tests/mod.rs, neqo-transport/src/path.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/sender.rs
See https://bugzilla.mozilla.org/show_bug.cgi?id=1952304
Since we'd now need to pass multiple `bool`s from the `ConnectionParameters` around, just pass the entire `struct`.
=> fix: Skip interface MTU query on OpenBSD

neqo-common/src/codec.rs
By disabling a test that panics on 64-bit platforms, but causes a compile error on 32-bit ones.
Fixes #2497
=> fix: Fix compile on 32-bit targets

neqo-bin/src/client/mod.rs, neqo-bin/src/server/mod.rs
Previously `neqo-bin` would poll a UDP socket to be writable before attempting to send a datagram. This results in 2 syscalls per send.
Instead, optimistically attempt to send the datagram first, on failure `WouldBlock`, await and then try again. Under the assumption that the majority of sends work on the first try, this reduces the number of syscalls.
Follow-up to https://phabricator.services.mozilla.com/D239162#8315719.
=> perf(bin): optimistically send datagram, only await on failure

Cargo.lock, Cargo.toml, neqo-transport/src/qlog.rs
And use the newly derived `default`s to shorten some initializations in our code.
Upstreaming this will take some `cargo vet` work in Firefox.
=> chore: Update `qlog` to 0.15.1

neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/handshake.rs
We count packets as received when they enter `input_path`. Then we may save them, since we can't decrypt them yet. When we re-process them, they again enter `input_path` and are counted as received. Fix that double-counting by only counting them when they are actually processed.
=> fix: Don't count saved packets as received twice

neqo-transport/src/recovery/mod.rs
Simple change to improve debug level log message:
``` diff
- 0.002 DEBUG [LossRecovery] PTO timer fired for in
+ 0.006 DEBUG [LossRecovery] PTO timer fired for Initial
```
---
Previously it was not obvious to me that "in" meant "Initial" packet number space.
=> refactor(transport/recovery): use PacketNumberSpace Debug in qdebug

neqo-transport/src/ecn.rs
Only used within the same module.
=> refactor(transport/ecn): make validate_ack_ecn_and_update private

.github/actions/quic-interop-runner/action.yml, .github/workflows/qns.yml
This gets rid of the :x: on all commits to `main` just because one or two QNS runs timed out.
=> ci: Don't fail QNS CI if a test times out

neqo-transport/src/connection/mod.rs, neqo-transport/src/streams.rs
The old code would try and call `write_maintenance_frames` at priorities other than `TransmissionPriority::Important`, which was useless. Just call it directly once.
=> fix: Don't try `write_maintenance_frames` at all priorities

neqo-transport/benches/sent_packets.rs, neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cc/tests/cubic.rs, neqo-transport/src/cc/tests/new_reno.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/ecn.rs, neqo-transport/src/packet/metadata.rs, neqo-transport/src/path.rs, neqo-transport/src/pmtud.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/recovery/sent.rs, neqo-transport/src/recovery/token.rs
Previously we would only call `neqo_transport::ecn::Info::on_packets_lost` when an ECN ECT0 marked packet was considered lost due to the [time-threshold]. It would *not* be called when a packet was considered lost due to a PTO.
With https://github.com/mozilla/neqo/pull/2492 one no longer considers a packet lost based on the time-threshold before the first ACK, entirely depending on the PTO until then.
Thus with https://github.com/mozilla/neqo/pull/2492 the ECN path validation mechanism would no longer detect an ECN blackhole, dropping all initial packets.
With this commit the ECN path validation state machine (i.e. `neqo_transport::ecn::Info`) is notified on PTO and can thus react to an ECN blackhole, disabling ECN markings after `TEST_COUNT_INITIAL_PHASE`.
`neqo_transport` already …
=> fix(transport/ecn): handle ECN loss on PTO

.github/actions/rust/action.yml, .github/workflows/mutants.yml
Only saving to the Rust cache on CI on `main` caused cache misses.
The `mutants` workflow needs `cargo-nextest`.
=> ci: Fix Rust caching and `mutants`

.github/workflows/bench.yml
Because the `transfer` bench creates two threads, and forcing both onto a single (isolated) CPU is hurting performance. As one might have expected.
=> ci: Schedule benches on CPUs 2 and 3

.github/workflows/qns.yml
Our CI cache is under too much pressure.
=> ci: Don't cache various QNS docker things

neqo-bin/benches/main.rs
Raised in https://github.com/mozilla/neqo/issues/2538.
=> refactor(bin/bench): fix typo %s/resp/req

neqo-crypto/build.rs
The build script doesn't get the same `cfg` info as the code, so work off environment variables.
=> fix: Fix condition in #2548

Cargo.lock, Cargo.toml, neqo-bin/src/udp.rs
We need to do the same for `neqo-glue`.
Fixes #1962
=> fix: Use 1MB socket RX buffers

.clippy.toml
I keep forgetting to remove all `dbg!` statements before marking a pull request as ready for review. Latest occurrence:
https://github.com/mozilla/neqo/pull/2492#discussion_r2026230723
Have CI fail on all `dbg!` statements.
```
➜  neqo git:(main) ✗ cargo +nightly clippy  --tests && cargo +nightly fmt
warning: the `dbg!` macro is intended as a debugging tool
--> neqo-transport/src/connection/mod.rs:118:40
|
118 |             Self::Datagram(dg) => Some(dbg!(dg)),
|                                        ^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#dbg_macro
= note: requested on the command line with `-W clippy::dbg-macro`
help: remove the invocation before committing it to a version control system
|
118 | …
```
=> chore(clippy): add dbg! to clippy.toml disallowed-macros

.gitignore
#2031 changed the `.qlog` file suffix to be `.sqlog`.
=> chore: adding `*.sqlog` and removing `*.qlog` from gitignore

.github/workflows/fuzz-bench.yml
Because just building them can hide errors.
=> ci: Actually briefly run fuzzer and benches

Cargo.lock, Cargo.toml
Bugfixes I would like to wait for:
- https://github.com/mozilla/neqo/pull/2492
Any objections? Anything else to include?
=> chore: prepare v0.13.0

Cargo.toml, neqo-bin/src/server/mod.rs, neqo-common/src/qlog.rs, neqo-common/src/tos.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/hp.rs, neqo-http3/src/frames/reader.rs, neqo-qpack/src/decoder.rs, neqo-qpack/src/encoder.rs, neqo-qpack/src/huffman.rs, neqo-qpack/src/huffman_table.rs, neqo-qpack/src/reader.rs, neqo-transport/src/packet/mod.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/version.rs, test-fixture/src/header_protection.rs, test-fixture/src/sim/connection.rs
See <https://github.com/mozilla/neqo/issues/2284#issuecomment-2782711813>.
Related: #2284
=> chore: re-enabling `module_name_repetitions` lint

Cargo.lock
`qlog` `v0.15.1` introduced various unnecessary dependencies. See `Cargo.lock` changes in https://github.com/mozilla/neqo/pull/2512/ and full analysis in https://github.com/cloudflare/quiche/pull/2005.
This commit updates Neqo `Cargo.lock` to use `qlog` `v0.15.2`, effectively removing all the unnecessary dependencies.
Given that Neqo builds with `qlog` `v0.15.1` just fine, this commit updates the `Cargo.lock` only. Also note that this commit is not required for `qlog` `v0.15.2` to land in mozilla-central.
```
➜  neqo git:(main) cargo update -p qlog --precise 0.15.2
Updating crates.io index
Removing android-tzdata v0.1.1
Removing android_system_properties v0.1.5
Removing base64 v0.22.1
Removing bumpalo v3.17.0
Removing chrono v0.4.40
Removing core-foundation-sys v0.8.7
Removing deranged …
```
=> chore(Cargo.lock): update to qlog v0.15.2

neqo-transport/src/connection/tests/vn.rs
Equivalent of #2363 for `assert_dhcp`.
=> fix: Fix the `compatible_upgrade_large_initial` test

Cargo.lock, Cargo.toml, neqo-transport/src/ecn.rs
And hopefully `haproxy`.
The old code caused ACK-ECN frames to be sent that had all-zero counts, which I don't think is a violation of the RFC, but we still shouldn't do.
Fixes #2566.
=> fix: Fix QNS test errors with `nginx`

.github/workflows/bench.yml
Should fix the CI failures of the bencher.
=> ci: Pin `google-quiche` until `main` compiles again

.github/workflows/check.yml
This reverts https://github.com/mozilla/neqo/pull/2280.
Suggestion by @larseggert in https://github.com/mozilla/neqo/pull/2570#issuecomment-2787360495. Attempt to fix unrelated code coverage changes.
Additional benefit: Previously we would only do code coverage checking on Rust Nightly. While the Nightly jobs themselves are not marked as `required`, the codecov report is. Thus two non-`required` Nightly failures (4 total, minimum is [3](https://github.com/mozilla/neqo/blob/c1679d89b5c3192429ff1bc56ed21e10dc699eef/.codecov.yml#L33)) would block the `required` code coverage step, thus blocking a merge. With this change, we are back to code coverage recording on stable.
=> Revert "ci: Enable MC/DC coverage"

neqo-transport/src/connection/mod.rs, neqo-transport/src/ecn.rs, neqo-transport/src/path.rs
Alternative to https://github.com/mozilla/neqo/pull/2588.
**Problem**
(Same as https://github.com/mozilla/neqo/pull/2588.)
During ECN path testing, in case `TEST_COUNT_INITIAL_PHASE` ECN probes get lost, ECN is disabled.
https://github.com/mozilla/neqo/blob/a62c14068ad603f878f13a354f9ce0eddf97231b/neqo-transport/src/ecn.rs#L21-L25
Though only if `*probes_sent == *probes_lost`.
https://github.com/mozilla/neqo/blob/a62c14068ad603f878f13a354f9ce0eddf97231b/neqo-transport/src/ecn.rs#L241-L246
Say that a Neqo client has sent 2 ECN marked packets, i.e. probes, each of them eventually declared lost. Next the client sends two more packets, each again marked.
When the first of the two is declared lost, `probes_sent` is `4` and `probes_lost` is `3`, thus ECN is not disabled.
When the second of the …
=> fix(transport/ecn): track ACK of marked packets

neqo-crypto/src/secrets.rs
On MinGW (https://en.wikipedia.org/wiki/MinGW) NSS's `SSLSecretDirection` is a `u32`. Given that we asign the `neqo-crypto` type `SecretDirection` to a `SSLSecretDirection`, the former (`neqo-crypto`) has to be same type like the latter (NSS).
See https://bugzilla.mozilla.org/show_bug.cgi?id=1960482 for details.
Follow-up to https://github.com/mozilla/neqo/pull/2440/files#r2048451993.
See the following failure without this patch failing to compile neqo-crypto:
https://treeherder.mozilla.org/jobs?repo=try&revision=2c7f5e2a0877b9ab897340a556f4a6f7c8a35c5c^Z
See the following failure with this patch, succeeding to compile neqo-crypto, failing for a different reason :)
https://treeherder.mozilla.org/jobs?repo=try&revision=59ff8632950ebea827d86c3f601d21207141ecb8&selectedTaskRun=ESNDUhdIQLm3huh …
=> fix(neqo-crypto): use u32 for SecretDirection enum on mingw

Cargo.lock, Cargo.toml
I would like to get https://github.com/mozilla/neqo/pull/2597/ into mozilla-central.
```
git log --oneline v0.13.1..
bc8b9038 (HEAD -> prepare-v0.13.2) chore: prepare v0.13.2
f066a16c (mozilla/main, main) fix(neqo-crypto): use u32 for SecretDirection enum on mingw (#2597)
53144a56 build(deps): bump lukemathwalker/cargo-chef in /qns (#2596)
a316236b build(deps): bump astral-sh/setup-uv from 5.4.1 to 5.4.2 (#2595)
6ffa21b6 build(deps): bump codecov/codecov-action from 5.4.0 to 5.4.2 (#2594)
dcdee555 fix(transport/ecn): track ACK of marked packets (#2589)
a62c1406 ci(bench): fail on regression (#2580)
3e03ab02 bench(h3/streams): reduce variants and increase sample size (#2587)
a9735408 build(deps): bump lukemathwalker/cargo-chef in /qns (#2586)
7a0bf0f5 build(deps): bump …
```
=> chore: prepare v0.13.2

neqo-transport/src/connection/mod.rs
https://github.com/mozilla/neqo/pull/2396 consolidated packet logging and logging to qlog.  On a log level < `Debug`, it would return early, i.e. not log the packet and not send it to qlog.
None of our other qlogs are bound to the current log level.
With this commit, all packets are sent to qlog, no matter the log level.
---
@KershawChang this resolves the qlog issue you saw in https://github.com/quic-go/quic-go/issues/5001#issuecomment-2812440458.
=> fix(transport/qlog): call qlog::packet_io even without log::Level::Debug

neqo-http3/src/buffered_send_stream.rs
That called `format!` even when the result was never logged.
CC @jrmuizel @mstange
=> fix: Eliminate expensive log call

.github/workflows/bench.yml
- Export client and server binaries as artifacts for @jrmuizel
- Up sampling rate to 4999
- Unpin google-quiche version
- Set `-f-no-omit-frame-pointer` for C compiles
=> ci: Misc. bench changes

.github/workflows/check-vm.yml, .github/workflows/check.yml, neqo-common/src/hrtime.rs, neqo-transport/src/connection/tests/vn.rs, qns/Dockerfile
- Disable the OpenBSD VM run, it's broken (no `libfuzzer-sys`)
- Add workaround for recent CodeCov breakage on Windows
- Disable flaky test on Linux/ARM
- Broaden success criteria for `compatible_upgrade_large_initial` test
- Use older version of QNS to work around recent random failures
=> ci: Misc. fixes

Cargo.toml, neqo-bin/Cargo.toml, neqo-udp/Cargo.toml, neqo-udp/src/lib.rs
The `quinn-udp` `fast-apple-datapath` Cargo feature allows Neqo to use the private MacOS multi-message IO functions `sendmsg_x` and `recvmsg_x`.
We have seen issues with `fast-apple-datapath`:
- https://github.com/quinn-rs/quinn/issues/2214
- https://github.com/quinn-rs/quinn/pull/2154
To reduce the risk of the upcoming larger roll out of the [Fast UDP for Firefox project](https://bugzilla.mozilla.org/show_bug.cgi?id=1901292) to Firefox Release, disable `fast-apple-datapath` for now.  Enabling it can then be a separate project afterwards.
---
Objections? I know it is a step backwards from a performance perspective. That said, I would like to prioritize getting the larger _Fast UDP for Firefox_ project onto Firefox Release.
=> feat: make fast-apple-datapath optional, off by default

Cargo.lock, Cargo.toml
With the recent performance improvements, I suggest we cut another patch release.
I would like to include https://github.com/mozilla/neqo/pull/2638, and thus unblock the roll out of the _Fast UDP for Firefox_ project on Firefox Release.
Once released, I will land this in Firefox Nightly and request an uplift to Firefox Beta.
---
```
git log --oneline v0.13.2..
548c051c fix: `clippy::iter_over_hash_type` (#2632)
aca21497 fix: `clippy::return_and_then` (#2631)
cb6d430a feat: `clippy::field_scoped_visibility_modifiers` (#2628)
3ecdfa1c fix: `clippy::partial_pub_fields` and `map_with_unused_argument_over_ranges` (#2630)
80bddc30 fix: Move allocations outside of loops (#2620)
d284171c chore: Bump `mtu` to 0.2.8 (#2614)
8e107a36 chore: Bump some deps to what Firefox is now using (#2615) …
```
=> chore: prepare Neqo v0.13.3

neqo-common/src/hrtime.rs
As the timers get tighter, give them more chances, but make the test pass two times for every failure.
Plus better pretty printing.
For #2422, but not claiming to fix it.
=> Make hrtime tests more robust

neqo-bin/Cargo.toml, neqo-bin/benches/main.rs, neqo-common/Cargo.toml, neqo-common/benches/decoder.rs, neqo-http3/Cargo.toml, neqo-http3/benches/streams.rs, neqo-transport/Cargo.toml, neqo-transport/benches/range_tracker.rs, neqo-transport/benches/rx_stream_orderer.rs, neqo-transport/benches/sent_packets.rs, neqo-transport/benches/transfer.rs
No idea if this will make things more stable, but shouldn't hurt.
Also add the `cargo_bench_support` feature to `criterion`. Surprised that lacking that wasn't breaking anything.
=> fix: Set bench run length, and use `std::hint::black_box`

Cargo.lock, Cargo.toml, neqo-common/src/hrtime.rs, neqo-crypto/src/aead.rs, neqo-crypto/src/agent.rs, neqo-crypto/src/cert.rs, neqo-crypto/src/ech.rs, neqo-crypto/src/hkdf.rs, neqo-crypto/src/hp.rs, neqo-crypto/src/lib.rs, neqo-crypto/src/p11.rs, neqo-crypto/src/replay.rs
This reverts the use of `raw` in commit 1ffe46c9bc923a9ac67bc5fd247a2cd2483f0759.
Rational:
- Firefox's [minimal Rust version is `1.82.0`](https://searchfox.org/mozilla-central/source/python/mozboot/mozboot/util.py#16).
- Rust `1.82.0` [stabilized `&raw const` and `&raw mut` operators (RFC 2582)](https://doc.rust-lang.org/beta/releases.html#version-1820-2024-10-17).
- Neqo - [uses these new operators in Neqo `0.13.3`](https://github.com/mozilla/neqo/pull/2605).
- Updating https://github.com/mozilla-firefox/firefox to Neqo `0.13.3` fails in `build-linux64-asan/opt` and `build-linux64-tsan/opt` job with the following error message:
```
error[E0658]: raw address of syntax is experimental
```
https://treeherder.mozilla.org/jobs?repo=try&revision=b7905ac4e2900df6c5c493011be71dd7342865a1&selecte …
=> Revert use of `raw` in "chore: Fix new nightly `clippy` warnings"

.github/actions/rust/action.yml
The issue in https://github.com/mozilla/mtu/pull/129 seems to be that a cache generated on an `ubuntu-24.04` runner is being restored onto an `ubuntu-22.04` runner.
=> ci: Key the Rust cache by the OS version

.github/actions/rust/action.yml
Previously we would use https://github.com/cargo-bins/cargo-quickinstall to install various Rust based command line tools, e.g. `nextest`.
`quickinstall` does not respect our `Cargo.lock`, nor does it have the option to enable it, e.g. via `--locked`.
The problem with not respecting our `Cargo.lock`:
- The `quickinstall` `nexttest` version uses `backtrace@0.3.75`.
- `backtrace@0.3.75` MSRV is `1.82.0` (https://crates.io/crates/backtrace/0.3.75)
- Our `Cargo.lock` specifies `backtrace@0.3.74`, which `quickinstall` ignores.
- https://github.com/mozilla/neqo/pull/2661/ tries to lower our MSRV to 1.81.0.
- The `check (ubuntu-24.04, 1.81.0, debug)` fails as it is using rustc `1.81.0`, but `backtrace@0.3.75` requires rustc `1.82.0`. https://github.com/mozilla/neqo/actions/runs/15275053671/job/42 …
=> ci(.github/rust): replace `quickinstall` with `cargo install` with `--locked`

.github/workflows/check.yml
NSS build fails on Windows with Rust 1.81.0. Firefox does not use Rust 1.81.0 (except for testing, see
https://bugzilla.mozilla.org/show_bug.cgi?id=1968057#c1). Firefox uses Rust 1.82.0. Thus this is not worth fixing. Let's explicitly use Rust 1.82.0 here for now.
=> ci(check): use Rust 1.82 instead of 1.81 on Windows

.github/workflows/bench.yml
Probably redundant with #2673.
=> ci: Inexact bench cache hits are OK

.github/workflows/bench.yml, .github/workflows/bencher-archive.yml, .github/workflows/bencher-upload.yml, .github/workflows/check.yml
Feed our benchmark data into bencher.dev, to be shown over time at https://bencher.dev/console/projects/neqo.
=> ci: Use bencher.dev

.github/workflows/bench.yml
`$BENCHES` contains the benchmark binaries of the PR builds. Sample:
```
➜  neqo git:(main) ✗ cargo bench --profile=dev --locked --workspace --features bench --no-run 2>&1  | tee benches.txt
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
Executable benches/main.rs (target/debug/deps/main-d713735815617f13)
Executable benches/decoder.rs (target/debug/deps/decoder-15595b2a50ff4039)
Executable benches/streams.rs (target/debug/deps/streams-696b71404547e60c)
Executable benches/min_bandwidth.rs (target/debug/deps/min_bandwidth-fd86000de3dceeb9)
Executable benches/range_tracker.rs (target/debug/deps/range_tracker-a78947e7c536dd73)
Executable benches/rx_stream_orderer.rs (target/debug/deps/rx_stream_orderer-06f95e3d033c1cdd)
Executable benches/sent_packets.rs …
```
=> ci(bench): introduce BENCHES_MAIN binary list

.github/actions/pr-comment-data-export/action.yml, .github/actions/pr-comment/action.yml, .github/workflows/bench.yml
Since we're now exporting samply data and binaries, the exported artifact has become very large and slow to download. Split out the samply data into its own artifact, so that the remainder is downloadable more quickly.
(Also change things so both are mentioned in the added PR message.)
=> ci: Split exported benchmark artifacts

.github/workflows/bench.yml, .github/workflows/check.yml
Our criterion benchmarks report a difference between `main` and non-Rust PRs. That is unexpected. On each run we checkout Neqo twice, once for `main`, once for the corresponding PR. I assume the deviation is due to Criterion not being able to compare across checkouts.
Instead of using two Neqo checkouts, this pull request uses a single checkout, switching between `main` and PR branch.
Fixes https://github.com/mozilla/neqo/issues/2657.
See https://github.com/mozilla/neqo/pull/2673#issuecomment-2930071659.
=> ci(bench): use single Neqo Git checkout

neqo-common/src/hrtime.rs
=> fix: Disable some `hrtime` tests on `aarch64`

.github/workflows/bench.yml
Since @martinduke asked whether it compiles again.
=> ci: Unpin `google/quiche` during bench

neqo-common/src/codec.rs, neqo-common/src/lib.rs, neqo-http3/src/buffered_send_stream.rs, neqo-http3/src/control_stream_local.rs, neqo-http3/src/frames/hframe.rs, neqo-http3/src/send_message.rs, neqo-http3/src/settings.rs, neqo-qpack/src/qpack_send_buf.rs, neqo-transport/src/tparams.rs
This allows users of `Encoder` to encode into existing buffers, thus reducing memory allocations and copying.
Example
Previously:
``` rust
let some_existing_buffer = vec![];
// ...
let mut encoder = Encoder::new(); // allocating a new temporary Vec
encoder.encode_varint(42); // writing into the temporary Vec
some_existing_buffer.extend_from_slice(&encoder); // copying latter into former.
```
Now:
``` rust
let some_existing_buffer = vec![];
// ...
let mut encoder = Encoder::new_borrowed_vec(&mut some_existing_buffer);
encoder.encode_varint(42); // writing directly into some_existing_buffer
```
---
Fixes https://github.com/mozilla/neqo/issues/2054.
Discussed in https://github.com/mozilla/neqo/issues/2670.
Simplifies https://github.com/mozilla/neqo/pull/2593.
=> perf(common): make Encoder generic over borrowed or owned buffer

.github/workflows/bench.yml
Previously `bench.yml` would:
1. Build main branch benchmark binaries.
2. Build PR branch benchmark binaries.
3. Execute main branch benchmark binaries.
4. Execute PR branch benchmark binaries.
While benchmark binary names are suffixed with a hash (see samples below), that hash is not unique across branches, instead it is unique across build-config changes (e.g. changes to Cargo.toml).
In other words, (2) overrides the binaries of (1) and thus (3) executes the same binaries as (4).
This fixes the issue by building the binaries just in time, interleaving building and executing.
Sample build output, note that executable names are the same across main and PR builds:
```
Previous HEAD position was d9cdd59 Merge b875854bedd3070aad7a870e44107a36fc40b6c7 into …
```
=> ci(bench): do not override main branch bench binaries

README.md
Running that command took 140s for me without `--profile=dev` and 387s with it (with `cargo clean` before each). So it seems like the compilation time saved isn't really relevant in comparison to the extra execution time.
Removing it from the README for that reason.
Also some changes from running `cargo +nightly fmt` on the file.
=> chore: removed `dev` profile from command in README

fuzz/fuzz_targets/client_initial.rs, fuzz/fuzz_targets/packet.rs, fuzz/fuzz_targets/server_initial.rs
See test failure in e.g. https://github.com/mozilla/neqo/actions/runs/15845790074/job/44667546909?pr=2755
Follow-up to https://github.com/mozilla/neqo/pull/2753
=> fix(fuzz): fix renamed header_protection::*

.cirun.yml, .github/workflows/bench.yml, .github/workflows/perfcompare.yml
Label needs to start with `cirun-`, see https://docs.cirun.io/reference/yaml#labels-labels.
=> ci: Fix cirun.io integration

.github/workflows/bench.yml, .github/workflows/perfcompare.yml
So it doesn't always trigger a GCP run.
=> ci: Fix Cirun trigger

neqo-transport/benches/sent_packets.rs, neqo-transport/src/ackrate.rs, neqo-transport/src/addr_valid.rs, neqo-transport/src/cc/classic_cc.rs, neqo-transport/src/cc/tests/cubic.rs, neqo-transport/src/cc/tests/new_reno.rs, neqo-transport/src/cid.rs, neqo-transport/src/connection/idle.rs, neqo-transport/src/connection/mod.rs, neqo-transport/src/connection/tests/idle.rs, neqo-transport/src/crypto.rs, neqo-transport/src/fc.rs, neqo-transport/src/path.rs, neqo-transport/src/pmtud.rs, neqo-transport/src/quic_datagrams.rs, neqo-transport/src/recovery/mod.rs, neqo-transport/src/recovery/sent.rs, neqo-transport/src/recovery/token.rs, neqo-transport/src/recv_stream.rs, neqo-transport/src/rtt.rs, neqo-transport/src/send_stream.rs, neqo-transport/src/streams.rs, neqo-transport/src/tracking.rs
~~For some reason, I wasn't allowed to push a rebase straight to #1657. So this is a new PR. Wanted to check if all the perf work we did in the meantime changes things here, and to get perf traces.~~
This PR now just introduces the `recovery::Tokens` type, which is still based on a `Vec`.
=> Introduce a `recovery::Tokens` type

neqo-crypto/src/agent.rs, neqo-transport/src/connection/tests/handshake.rs
Previously `enable_ech` would first call `SSL_CallExtensionWriterOnEchInner`, i.e. enable the transport parameter
filtering on the outer client hello and then `ech::SSL_SetClientEchConfigs`. Given an invalid ECH config, the first
would succeed and the second fail, resulting in a non-ECH client hello with filtered transport parameters. One such transport parameter is `InitialMaxStreamsBidi`, thus preventing the serverl to open streams to
the client after the handshake.
This commit reverses the order, thus no longer filtering transport parameters after an invalid ECH config.
---
Bug now surfacing with https://github.com/mozilla/neqo/pull/2666. Note that https://github.com/mozilla/neqo/pull/2666/ did not introduce the bug.
Discovered through [mozilla-central Neqo v0.14.0 …
=>  fix(crypto): do not filter transport parameters on invalid ECH conf 

Cargo.lock, Cargo.toml
Includes:
- https://github.com/mozilla/neqo/pull/2789
- https://github.com/mozilla/neqo/pull/2787
=> chore(Cargo.toml): prepare v0.14.1 release

neqo-http3/tests/webtransport.rs
Related: https://github.com/mozilla/neqo/issues/2798
=> test(http3): assert WebTransport NewStream before DataReadable

neqo-common/src/lib.rs
The specification for max() and min() when the arguments are equal has min() take the first argument and max() take the second.  Our code does the opposite.  Flip them.
This has no effect, other than to avoid propagating a logical error.
=> Flip equality for const_min/const_max

neqo-common/src/codec.rs, neqo-transport/src/frame.rs
Previously `neqo-transport` would use a `u16` to count the number of padding frames, i.e. `0`s. If an attacker sends more than `u16::MAX` `0`s, the counter would overflow.
This commit returns a `Error::TooMuchData` instead.
Note that the maximum UDP size is `u16::MAX`, thus in the real world, an attacker can not send more than `u16::MAX` padding frames.
---
Fixes https://github.com/mozilla/neqo/issues/2838.
=> fix(transport/frame): prevent potential overflow in padding decode

neqo-transport/src/quic_datagrams.rs
`fn` doesn't return a `bool` (`-> Res<()>`).
=> docs(transport/datagrams): remove outdated fn return docs

neqo-transport/src/connection/mod.rs
This was news to me. Thus documenting it.
=> docs(transport): extend preprocess_packet docs on State::Closing

.github/workflows/bench.yml, .github/workflows/perfcompare.yml
Instead of hardcoding it, which breaks on GCP w/cirun.io.
=> ci: Use implicit `$HOME` home directory

neqo-http3/benches/streams.rs, neqo-http3/tests/httpconn.rs, neqo-http3/tests/priority.rs, neqo-http3/tests/send_message.rs, neqo-http3/tests/webtransport.rs, test-fixture/src/lib.rs
This commit unifies various `exchange_packets` implementations across the codebase.
=> refactor: unify most exchange_packets impls

neqo-transport/src/connection/tests/handshake.rs, neqo-transport/src/connection/tests/recovery.rs, neqo-transport/src/recovery/mod.rs
This tweaks the change that @larseggert made to reduce the number of pointless handshake packets (Initial and Handshake both).  Rather than cap the number of probes we send on a PTO, this keeps the limit of two packets, but disables the probing we do with PING frames once we have sent a packet of the indicated type.
This merges the spaces that we probe when a PTO occurs.  So we don't
just probe the last space that fired the PTO timer.   Because we time
out Initial and Handshake packets at the same time often, that results
in only probing the Handshake space.  That's probably OK in most cases,
but it can mean stalling Handshake if there is stuff to send at that
level at a server.
Because this allows more than one packet to be sent in Initial and Handshake packet number spaces, there are …
=> PTO across packet number spaces better

neqo-http3/src/server_events.rs
At least I understand from the docs that is not needed: https://doc.rust-lang.org/std/hash/trait.Hash.html#implementing-hash
=> fix: Don't call `finish` in `std::hash::Hash` implementations

neqo-http3/src/lib.rs
Used in https://github.com/mozilla-firefox/firefox/blob/2560b9e4645c84c00c70e997cee1b13a6500f994/netwerk/test/http3server/src/main.rs#L666
=> fix(http3): resurrect Http3StreamInfo::is_http

test-fixture/src/sim/delay.rs, test-fixture/src/sim/mod.rs
This should be faster as the structure is less complex, but we'll need to test against the changes that are coming to test wall-clock time for the simulation runs.
=> Simplify the fixed delay node

.github/workflows/bench.yml, neqo-transport/benches/transfer.rs
Got reverted in https://github.com/mozilla/neqo/pull/2908 due to https://github.com/mozilla/neqo/pull/2885#issuecomment-3223885666.
This pull request adds a fix in the second commit:
```
fix(transport/bench): use new group for each benchmark
We parse the criterion benchmark output, alter it, then post it as a
GitHub comment.
https://github.com/mozilla/neqo/blob/8ce7f9bcdef89fa5a1eb37db6a2375db9a4531ea/.github/workflows/bench.yml#L163-L187
We want to split by benchmark. The easiest way to do so is through a
newline. Criterion only inserts a newline for each benchmark group. Thus
split the existing group into two, one per benchmark function (i.e.
wallclock-time and simulated-time).
Issue raised in https://github.com/mozilla/neqo/pull/2885#issuecomment-3223885666
```
=> Reapply "bench(transport/transfer): measure both wallclock and simulated time"

Cargo.lock
Recent Rust Nightly is failing with:
```
error[E0597]: `path_entries` does not live long enough
--> /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cc-1.0.89/src/lib.rs:3869:22
|
3868 |     let path_entries = path_entries.or(env::var_os("PATH"))?;
|         ------------ binding `path_entries` declared here
3869 |     env::split_paths(&path_entries).find_map(|path_entry| {
|     -----------------^^^^^^^^^^^^^-
|     |                |
|     |                borrowed value does not live long enough
|     a temporary with access to the borrow is created here ...
```
https://github.com/mozilla/neqo/actions/runs/17359314980/job/49277074440?pr=2919
This commit updates `cc` to a newer version. The same version that Firefox uses.
=> deps(Cargo.lock): update cc

neqo-bin/src/client/http3.rs, neqo-bin/src/client/mod.rs, neqo-bin/src/lib.rs
Previousy `Args` would not implement `Clone`, thus requiring lifetime parameters for `Args` references in various places in `neqo-bin`.
This commit derives `Clone` for `Args`, thus simplifying the code.
Needed in and pulled out of https://github.com/mozilla/neqo/pull/2796/.
=> refactor(bin): derive Clone for Args

.github/actions/pr-comment/action.yml
Switch from `upsert`. This _should_ make updated bench and other comments appear at the current place in the comment timeline, so no more scrolling. Downside is that one can't diff against earlier runs for the same PR.
=> ci: `recreate` PR comments

.github/actions/rust/action.yml
We killed `mold` in #2857.
Also make our cache key a bit prettier while I'm here.
=> ci: Remove last traces of `mold`

.github/actions/rust/action.yml, .github/workflows/bench.yml, .github/workflows/perfcompare.yml
https://github.com/mozilla/neqo/pull/2939/ removed the custom linker args leftover from when we used `mold`.
I believe now the argument order is relevant. Thus moving both to the respective usage points.
---
Follow-up to https://github.com/mozilla/neqo/pull/2939/.
Alternative to https://github.com/mozilla/neqo/pull/2942.
=> fix(.github/rust): remove custom linker args

.github/workflows/bench.yml
`cargo bench` sometimes fails on CI in criterions GNU plotting logic.
https://github.com/mozilla/neqo/issues/2933
We don't make use of the GNU plots. Thus disable the plotting all together.
=> fix(.github/bench): add criterion --noplot flag

neqo-http3/src/connection.rs, neqo-http3/src/connection_client.rs, neqo-http3/src/features/extended_connect/tests/webtransport/mod.rs, neqo-http3/src/features/extended_connect/tests/webtransport/sessions.rs, neqo-http3/src/request_target.rs, neqo-http3/tests/httpconn.rs, neqo-http3/tests/priority.rs, neqo-http3/tests/send_message.rs, neqo-http3/tests/webtransport.rs, test-fixture/src/sim/http3_connection.rs
Previously to specify a request target we used the following types:
- trait `RequestTarget` for gettters
- struct `RefRequestTarget` as base representation of `RequestTarget`
- trait `AsRequestTarget` to convert other types into something that implements `RequestTarget`
- struct `UrlRequestTarget` implementing `RequestTarget` to convert a `str` potentially fallible
This commit reduces the mechanism to a single trait, i.e. `RequestTarget`.
Only downside is that one can no longer directly pass a `&str` to functions like `fetch`. That said, we did this in a single place only, `neqo-bin`. Now, it requires a single conversion step to a `Url` before. Additional upside is that the caller handles the error on invalid request targets.
---
Follow-up to …
=> refactor(http3): simplify RequestTarget

neqo-common/src/datagram.rs
Otherwise e.g. the below would not result in a warning:
``` rust
dgram.len();
```
=> refactor(common): add #[must_use] to Datagram functions

neqo-http3/src/features/extended_connect/mod.rs, neqo-http3/src/features/extended_connect/session.rs
Minor follow-up to Lars' comment in https://github.com/mozilla/neqo/pull/2796#discussion_r2325101347.
=> refactor(http3): replace (Vec<Header>, bool, bool) with named struct

neqo-http3/src/features/extended_connect/connect_udp_session.rs, neqo-http3/src/features/extended_connect/session.rs
MASQUE connect-udp prefixes each proxied UDP datagram payload with a context ID. A context ID is a varint.
> Context IDs are 62-bit integers (0 to 262-1). Context IDs are encoded as variable-length integers; see Section 16 of [QUIC].
https://www.rfc-editor.org/rfc/rfc9298.html#section-4
Previously the code would parse the first byte only, checking whether it is 0x00. But 0x00 is not the only varint encoding of 0. Another e.g. is 0x40 0x00.
This commit properly parses the context ID as a varint.
---
Fixes https://github.com/mozilla/neqo/issues/3017
=> fix(http3/connect-udp): parse context id as varint
