- .circleci/config.yml
- neqo-crypto/build.rs
- neqo-crypto/src/lib.rs
I'm not going to land this because it depends on https://phabricator.services.mozilla.com/D30853 landing in NSS and there are a few hacky bits left in here that I started using to debug our flaky CI, but in case anyone feels crazy, this compiles and runs.
> Build and run on windows

- neqo-transport/src/connection.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/send_stream.rs
Add method on Connection to get bytes currently allowed to be sent.
> Do not queue bytes that flow control would prevent from being sent

- .mergify.yml
https://doc.mergify.io/examples.html#deleting-merged-branch
> mergify: delete branches in mozilla/neqo once merged

- neqo-client/src/main.rs
- neqo-common/src/lib.rs
- neqo-http3-server/src/main.rs
- neqo-interop/src/main.rs
- neqo-server/src/main.rs
> Use Instant::now() rather than ::neqo_common::now()

- neqo-transport/src/recovery.rs
@ddragana please take a look.
I couldn't really make sense of the recovery tests because they tested a lot of things in series.  I split them up.  I notice that there are some parts of the code that still aren't tested fully, but I think that this covers more.
The omission regarding PTO is something I was tempted to fix, but then I remembered that Ian is planning to consolidate the crypto timeout and PTO, so I think that we should wait for that change to land in the spec.
> Recovery tests

- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
Just moving more stuff out of connection.rs.
> transport: move impl CryptoCtx for CryptoDxState to crypto.rs

- neqo-transport/src/connection.rs
- neqo-transport/src/flow_mgr.rs
> transport: send flow control frames in 1-RTT packet number space

- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/flow_mgr.rs
- neqo-transport/src/frame.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/send_stream.rs
- neqo-transport/src/tracking.rs
instead, query frame sources explicitly, depending on
connection state.
fixes #37
> remove generators

- neqo-transport/src/connection.rs
- neqo-transport/src/recovery.rs
Instead, set the PTO timer if there are in flight
ack eliciting packets, or state is not Connected.
Actually doing something when the PTO timer expires is
still TBD.
fixes #96
> remove crypto timer

- neqo-transport/src/recovery.rs
This will change, depending on the decisions made in #43
> Add an rtt accessor.

- neqo-common/src/datagram.rs
- neqo-http3-server/src/main.rs
- neqo-interop/src/main.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/server.rs
No sense in having this mutable.  We don't use the capability anyway.
> Make Datagram immutable

- neqo-transport/src/connection.rs
There were cases when testing retry where a connection would go from
Closed to Closing.  That isn't good, so let's safeguard against that.
> Ensure that states don't regress

- neqo-common/src/log.rs
- neqo-common/tests/log.rs
@o0Ignition0o, this seems to work.  I don't know what you were doing differently.
Closes #91, #120.
> optional comma after the bracketed item in qlog!()

- neqo-client/src/main.rs
- neqo-crypto/src/agent.rs
- neqo-http3/src/connection.rs
- neqo-interop/src/main.rs
- neqo-server/src/main.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/events.rs
- neqo-transport/src/flow_mgr.rs
- neqo-transport/src/frame.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/recv_stream.rs
- neqo-transport/src/send_stream.rs
- neqo-transport/src/stream_id.rs
> Small stuff

- neqo-crypto/src/err.rs
- neqo-http3/src/connection.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/events.rs
- neqo-transport/src/lib.rs
lets make Connected, Closing and Close events. In current http3 code we need to check whether state has change every time we call process_*
> ConnectionEvents for the connection state changes.

- neqo-client/src/main.rs
- neqo-crypto/bindings/bindings.toml
- neqo-crypto/src/agent.rs
- neqo-crypto/src/cert.rs
- neqo-crypto/src/constants.rs
- neqo-crypto/src/lib.rs
- neqo-crypto/tests/agent.rs
- neqo-crypto/tests/ext.rs
- neqo-crypto/tests/handshake.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/hframe.rs
- neqo-http3/tests/httpconn.rs
- neqo-interop/src/main.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/events.rs
- test-fixture/src/lib.rs
I am not really familiar with the certificate verification in psm. This works. Please give me any suggestion if there is a better way.
I will discuss the changes to gecko/psm code with Dana.
> Expose the info needed for an external certificate verification.

- neqo-http3-server/src/main.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/transaction_client.rs
- neqo-http3/src/transaction_server.rs
- neqo-http3/tests/httpconn.rs
This is the same as PR #135. For some reason that one did not got merged.
> Rename request_stream_client/server into transaction_client/server

- neqo-crypto/build.rs
Building on Windows wasn't working again.  And I wasn't getting good
results from --release either.
I will open an issue to investigate enabling --release and windows
builds on CI.  Circle supports windows now, but that might take a little
while to get working.
> Fixes for different build variants

- neqo-transport/src/connection.rs
- neqo-transport/src/send_stream.rs
I think this is not completely correct, but I need some help.
@agrover
>  Send fin if we close the send side of a remote bidi stream. 

- neqo-crypto/build.rs
- neqo-crypto/src/time.rs
(Based on #146 because for some reason I can't build without that fix now.)
> Time travel fix

- neqo-client/src/main.rs
- neqo-http3-server/src/main.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/transaction_client.rs
- neqo-http3/src/transaction_server.rs
- neqo-http3/tests/httpconn.rs
- neqo-interop/src/main.rs
- neqo-qpack/src/decoder.rs
- neqo-qpack/src/encoder.rs
- neqo-qpack/src/lib.rs
> Move header type to neqo-qpack, reexport it through neqo-http3.

- neqo-crypto/src/lib.rs
- neqo-crypto/src/time.rs
These files all include internals, but they were, for various reasons
exposed to the outside world.
> Make more of neqo-crypto private

- docker/Dockerfile
Once this merges, we should push to the `docker` branch.  But we shouldn't do that until we can verify that the image builds.
> Upgrade rustup

- neqo-http3/src/hframe.rs
> Fix hframe.

- neqo-transport/src/connection.rs
> Split part of input() into separate functions.

- neqo-http3/src/connection.rs
- neqo-http3/src/hframe.rs
- neqo-http3/src/transaction_client.rs
- neqo-http3/src/transaction_server.rs
We'll probably need to add something back eventually, but no point
carrying dead code until then.
> Remove priorities

- neqo-client/src/main.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/transaction_client.rs
- neqo-interop/src/main.rs
> Revert "Refactor receiving part of the transaction_client:"

- neqo-common/src/codec.rs
This factors out some of the code.
It also tweaks the `encode_vvec_with` function so that it avoids rotating
buffers in common cases.  Most of the time we don't encode more than 63
bytes of content, so reserving a byte for the length is fine.  It's a
shade more complicated, but not unbearably so.
> Refactor the codec code some

- neqo-crypto/src/agent.rs
This makes it a little cleaner.
> Use split_first in set_alpn

- test-fixture/src/lib.rs
> Fix earlier test

- .circleci/config.yml
- neqo-crypto/Cargo.toml
- neqo-crypto/build.rs
> Option to build neqo-crypto with the nss built by Firefox.

- neqo-crypto/src/aead.rs
- neqo-crypto/src/err.rs
- neqo-crypto/src/lib.rs
> Use c_char instead of u8

- neqo-crypto/src/auth.rs
mozilla-central is complaining about this.
> Fix error: enum variants on type aliases are experimental.

- neqo-http3/src/connection.rs
> Remove assertions that connection is in an active state.

- neqo-crypto/bindings/bindings.toml
- neqo-crypto/src/hkdf.rs
- neqo-crypto/src/p11.rs
- neqo-transport/src/crypto.rs
Also, cleanup the API a little
This builds on #216, so you can see those changes here.  This is one reason I want Phabricator for this, because I find that I'm building stacks of patches.
>  Add keygen to hkdf

- neqo-crypto/bindings/bindings.toml
- neqo-crypto/src/p11.rs
This one uses NSS.  We should probably migrate to it for some things, but that can come later.
> Add a secure random generator

- neqo-crypto/src/aead.rs
More docs, minor additions to API
> Streamline AEAD a little

- neqo-common/src/codec.rs
> Make Encoder cloneable

- neqo-http3/src/connection.rs
This change also use connect_and_send_request more often.
> Clean up http3 tests.

- neqo-crypto/build.rs
So we need this changes to make firefox compile.
The current version does not use  extra-bindgen-flags, but I found out that such a file is the newest way and encouraged approach we are doing this.
Also we need mozilla-config.h.
@martinthomson : should we add this change to this repository or strip all gecko build parts and add them in m.-c. by applying a patch on each update?
Probably I will need to update this patch once again when I figure out how to make a http3 test server be built by gecko. Note: the server builds with this patch on all platforms except windows and asan builds are broken as well.
> Fix gecko build

- neqo-transport/src/send_stream.rs
I think we want to use try_from() so unexpected things don't fail silently
but realistically this will never happen so use an expect() in one case.
In another case, everything seems to already be a usize, so I don't believe
the check is needed at all.
> Clean up some fixmes in send_streams.rs

- neqo-crypto/src/agent.rs
- neqo-crypto/src/agentio.rs
This code was written before I knew about pub(crate).  This isn't a tool
I like to use much, but these a public objects and I really want to
associate these methods with them.
> Use pub(crate) for agentio methods

- neqo-transport/src/connection.rs
This could be useful for testing purposes. @ddragana this seems pretty simple, but does this allow what we need for testing purposes?
> Add a method to set a local tparam

- neqo-transport/src/connection.rs
It can vary based on ipv4 or ipv6, or if we ever implement PMTUD (#243).
fixes #199
> Make Connection::pmtu a method

- neqo-transport/src/send_stream.rs
Revert previous changes that handled safely converting between u64 and
usize. Instead, use unwrap() since we are not expecting these to happen.
> fix clippy

- neqo-transport/src/connection.rs
Yes there will be multiple in the future, and when that happens the
member variable should be renamed. Calling it "paths" now when it's just
0 or 1 paths is confusing.
> Rename Connection::paths to path

- neqo-crypto/src/time.rs
- neqo-http3/src/connection.rs
I was doing it wrong previously, which meant that time was moving too
fast.
> Slow time to from the 1000x speed-up to normal

- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/lib.rs
I will update error codes in my next patch.
> Draft update, some errors are connection errors not stream errors anymore.

- neqo-transport/Cargo.toml
> Update slice-deque version.

- neqo-client/Cargo.toml
- neqo-common/Cargo.toml
- neqo-crypto/Cargo.toml
- neqo-http3-server/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-interop/Cargo.toml
- neqo-qpack/Cargo.toml
- neqo-server/Cargo.toml
- neqo-transport/Cargo.toml
- test-fixture/Cargo.toml
> Add "license=..." to Cargo.toml

- neqo-http3-server/src/main.rs
- neqo-http3/src/client_events.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/connection_server.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/server_events.rs
- neqo-http3/src/transaction_client.rs
- neqo-http3/src/transaction_server.rs
- neqo-http3/tests/httpconn.rs
- test-fixture/src/lib.rs
> Http3 rework part2

- neqo-client/src/main.rs
- neqo-http3-server/src/main.rs
- neqo-http3/src/client_events.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/connection_server.rs
- neqo-http3/src/server_events.rs
- neqo-http3/tests/httpconn.rs
- neqo-interop/src/main.rs
Change events to use VecDeque and add back the assertions.
> Events use VecDeque

- neqo-crypto/src/agent.rs
Per https://doc.rust-lang.org/beta/std/mem/fn.uninitialized.html,
std::mem::uninitialized is deprecated as of Rust 1.39.0.
Getting ahead of this deprecation with a change does not affect
compilation under stable.
> std::mem::MaybeUninit, not std::mem::uninitialized

- neqo-http3/src/connection.rs
Closing is an acceptable state of the connection when `Http3Connection::handle_connection_closing` is invoked.
Add an `Http3Connection::state_closing` method to support this change.
> Fix Issue #278

- neqo-transport/src/connection.rs
> Remove assert in output_path()

- neqo-crypto/src/agent.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/frame.rs
This turned out to trigger a bug.
> Check that frames are allowed

- neqo-http3/src/connection.rs
A connection can be in Inintial state as well.
> Remove assertion in neqo_http3::connection::close:

- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
* Refactor Connection::handshake a little
* Move buffer_crypto_records() to crypto.rs
> Random refactorings

- neqo-http3/Cargo.toml
- neqo-transport/Cargo.toml
Hopefully we can avoid duplication of smallvec in m-c by doing this.
> Bump smallvec to 1.0.0

- neqo-transport/src/frame.rs
This is a n old bug from fixing clippy.
> Ack parsing bug.

- neqo-crypto/src/agent.rs
- neqo-crypto/src/agentio.rs
- neqo-crypto/src/ext.rs
- neqo-crypto/tests/agent.rs
- neqo-crypto/tests/handshake.rs
This will depend on an update to our docker image, so it will likely fail in CI for a bit.
Closes #282.
> Pin all the boxes

- README.md
> Document NSS_DIR

- neqo-transport/src/connection.rs
Accidentally omitted from #323, I think because tests rely on
test_process_input(), added in #324.
> add tests for PTO and ping

- neqo-interop/src/main.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/packet.rs
> After zero-rtt has been rejected we should discharge zero-rtt keys.

- neqo-common/src/lib.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/frame.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/send_stream.rs
See previous draft PR #348.
Adds congestion control and tests for same.
Fixes random bugs encountered.
> Congestion Control

- neqo-transport/src/recovery.rs
- neqo-transport/src/send_stream.rs
> Fix 364 and 365

- neqo-transport/src/frame.rs
new_stream should only return a frame if at least one byte of actual data
fits in space after frame overhead, or there is no data that fits but
fin is set.
Instead of using saturating math, I found it easier to add to an "overhead"
variable, and then compare that to space. There is also fun times when the
optional length field results in there not being space for any data, or
requiring fin to be unset.
I have more confidence in this now because of the tests.
> Rewrite Frame::new_stream() and add tests

- neqo-crypto/src/hkdf.rs
- neqo-crypto/src/lib.rs
- neqo-crypto/src/p11.rs
- neqo-crypto/src/selfencrypt.rs
- neqo-transport/Cargo.toml
- neqo-transport/src/packet.rs
There are a few places we pulled on the rand crate, but we have a random number generator already, so this reduces dependencies.
> Use the NSS CSPRNG

- neqo-transport/src/cc.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/tracking.rs
> Move congestion control into its own file

- neqo-transport/src/connection.rs
There was also some dead code here that ran the output code a second
time if the state changed.  It turns out that we don't need to worry
about this as we never send a CONNECTION_CLOSE in response to errors in
the sending side of the code.  We only need to absorb the errors though
or error conditions won't ever clear.
> Move path selection out of output_path

- neqo-http3/src/connection_client.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/flow_mgr.rs
- neqo-transport/src/frame.rs
- neqo-transport/src/recovery.rs
- neqo-transport/tests/connection.rs
- neqo-transport/tests/server.rs
- test-fixture/src/lib.rs
This is incomplete in the sense that it doesn't discard handshake state (yet).  @ddragana, do you think that you could use this in combination with your previous code (and tests)?
> HANDSHAKE_DONE

- neqo-qpack/src/decoder.rs
- neqo-qpack/src/table.rs
Per https://tools.ietf.org/html/draft-ietf-quic-qpack-11#section-2.1.4,
it seems that a header acknowledgment obviates the requirement of
sending increment instructions, in certain cases. This patch makes sure
that the decoder does not send increment instructions for only the
potentially-blocking references from the header block which are
implictly acknowledged by the header acknowledgment.
> Fix #354: QPACK: Reset increment count after sending a header acknowledgment

- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/recovery.rs
Move things that output entire buffers to TRACE
Add a few useful little other log messages.
> Tweak log levels

- neqo-http3/src/connection.rs
- neqo-interop/src/main.rs
- neqo-transport/src/connection.rs
> Fix a crash in the h3 runner

- neqo-client/src/main.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/transaction_client.rs
- neqo-interop/src/main.rs
> Fix interop crash

- neqo-transport/src/packet.rs
This likely isn't perfect, but this should reduce the side channels we
have from packet number decryption.
(This came up in the QUIPS workshop, which prompted me to check and fix.)
> Make packet number decryption closer to constant time

- neqo-client/Cargo.toml
- neqo-common/Cargo.toml
- neqo-crypto/Cargo.toml
- neqo-http3-server/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-interop/Cargo.toml
- neqo-qpack/Cargo.toml
- neqo-server/Cargo.toml
- neqo-transport/Cargo.toml
- test-fixture/Cargo.toml
Remove some version deps for other crates in the repo, unneeded since
everything should stay in sync.
> Bump version to 0.2.0

- neqo-client/src/main.rs
Work towards #461, currently incomplete.
> neqo-client improvements for QNS

- neqo-transport/src/tracking.rs
@ddragana Could you, please, review whether I have changed the value in the right place 🙂 
Closes #389
> Change MAX_TRACKED_RANGES value

- README.md
> Fix neqo-client run example in readme.md

- neqo-crypto/Cargo.toml
- neqo-crypto/build.rs
> Update bindgen to 0.53.2

- neqo-client/Cargo.toml
- neqo-crypto/Cargo.toml
- neqo-http3-server/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-interop/Cargo.toml
- neqo-qpack/Cargo.toml
- neqo-server/Cargo.toml
- neqo-transport/Cargo.toml
- test-fixture/Cargo.toml
> Revert "Use consistent spacing in toml files"

- neqo-client/src/main.rs
The network simulator passes the testcase as an environment variable. If
neqo-client is in qns-mode, examine this and alter behavior as needed.
Specifically, if the testcase is unknown or unsupported, exit with a 127
value.
Since qns uses HTTP 0.9 for some tests, upgrade the "old_" code to support
writing fetched documents to a directory.
> neqo-client: Add mode for use with network simulator

- neqo-transport/src/crypto.rs
See https://bugzilla.mozilla.org/show_bug.cgi?id=1624800
Current impl using Index/IndexMut will panic if trying to access a
dropped CryptoStream. This is fine in some uses but others, especially
having to do with lost packet processing, we should not panic. It's
conceivable that we're tracking a packet and then mark it lost after we
have dropped initial crypto streams, for example.
Implement get/get_mut and panic, warn, or do nothing, depending on the
use case.
> crypto: Allow for failure when looking up crypto streams

- neqo-crypto/src/agent.rs
- neqo-crypto/src/ssl.rs
- neqo-crypto/src/time.rs
Removes a couple of TODOs, not that difficult or exciting.
> Refactor the time handling in neqo-crypto

- neqo-client/src/main.rs
- neqo-http3-server/src/main.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/connection_server.rs
- neqo-http3/src/control_stream_local.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/server.rs
- neqo-qpack/Cargo.toml
- neqo-qpack/src/decoder.rs
- neqo-qpack/src/decoder_instructions.rs
- neqo-qpack/src/encoder.rs
- neqo-qpack/src/encoder_instructions.rs
- neqo-qpack/src/header_block.rs
- neqo-qpack/src/huffman.rs
- neqo-qpack/src/huffman_decode_helper.rs
- neqo-qpack/src/lib.rs
- neqo-qpack/src/prefix.rs
- neqo-qpack/src/qpack_send_buf.rs
- neqo-qpack/src/reader.rs
- neqo-qpack/src/table.rs
also receiving wrong MaxTableCapacity settings after 0RTT had a wrone error.
> Turn on clippy:pedantic for neqo-qpack except for huffman*.rs

- neqo-common/src/codec.rs
- neqo-common/src/datagram.rs
- neqo-common/src/lib.rs
- neqo-crypto/src/agentio.rs
- neqo-crypto/src/p11.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/hframe.rs
- neqo-transport/src/cid.rs
- neqo-transport/src/packet.rs
> Remove prepending length from hex function

- neqo-transport/src/connection.rs
- neqo-transport/src/recovery.rs
> Remember smoothed_rtt from previous connection

- neqo-transport/src/recovery.rs
No need for two lots of division
> Simplify RTT update calculation

- neqo-http3-server/src/main.rs
- neqo-http3/src/client_events.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/connection_server.rs
- neqo-http3/src/control_stream_local.rs
- neqo-http3/src/control_stream_remote.rs
- neqo-http3/src/hframe.rs
- neqo-http3/src/hsettings_frame.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/response_stream.rs
- neqo-http3/src/server.rs
- neqo-http3/src/server_connection_events.rs
- neqo-http3/src/server_events.rs
- neqo-http3/src/stream_type_reader.rs
- neqo-http3/src/transaction_client.rs
- neqo-http3/src/transaction_server.rs
- neqo-http3/tests/httpconn.rs
also Remove HttpEarlyResponse error code
> Turn on clippy pedantics for neqo-http3.

- neqo-http3/src/hframe.rs
- neqo-http3/src/transaction_client.rs
- neqo-http3/src/transaction_server.rs
@ddragana, I think these are trivial, except for the 1st and 4th commits. These *do* slightly alter behavior, so please more look closely at them.
> Fix small issues noticed while reading the code

- neqo-client/src/main.rs
- neqo-http3/src/connection_client.rs
- neqo-interop/src/main.rs
- neqo-transport/src/connection.rs
> Merge process_timers and process_output.

- .gitignore
- neqo-transport/src/connection.rs
* Ignore .qlog files
* Make ConnectionClosed event log level info, not error
> Small fixes

- neqo-client/src/main.rs
> Fix neqo-client http/0.9 support

- .gitignore
> Add *.swp to gitignore

- neqo-client/src/main.rs
This patch adds support for handshake and transfer tests.
> Client tests handshake transfer

- neqo-transport/src/connection.rs
- neqo-transport/src/recovery.rs
This removes some of the inconsistencies in the code by throwing out the
loss recovery state/mode stuff.  It means going back to the source of
truth every time, so it might be a tiny bit less efficient, but my
thinking that this is mostly down to having to iterate over packet
number spaces.  We can fix that later by pruning packet number spaces
out (how: TBD).
Closes #574.
Closes #505.
> Simplify loss recovery

- neqo-client/src/main.rs
This lets HTTP 0.9 QUIC connections time out, just like H3 connections.
> neqo-client: Update process_loop_old to call process_output() repeatedly

- neqo-qpack/src/decoder.rs
- neqo-qpack/src/encoder.rs
- neqo-qpack/src/header_block.rs
- neqo-qpack/src/lib.rs
- neqo-qpack/src/table.rs
- define more descriptive errors,
- remove QPackSide,
-  do not use acked_inserts_cnt on the decoder side,
-  add comments,
-  define some struct pub(crate),
-  and some other small improvements.
> Improve table.rs

- neqo-qpack/src/encoder.rs
If header block consists of 2 headers and the first is encoded as a reference to an entry in the dynamic table and we do not add the reference immediately the following header may delete the entry the first header is referring to
> Add a reference to a qpack dynamic table entry as soon as it is referred in a header block encoding

- neqo-transport/src/connection.rs
- neqo-transport/src/send_stream.rs
Seems slightly better.
fixes #626
> Change stream_avail_send_space() to return usize instead of u64

- neqo-transport/src/connection.rs
We should probably do this more often.
> Add [self] to padding log

- neqo-common/src/codec.rs
- neqo-common/src/incrdecoder.rs
- neqo-common/src/timer.rs
- neqo-crypto/src/aead.rs
- neqo-crypto/src/agent.rs
- neqo-crypto/src/agentio.rs
- neqo-crypto/src/ext.rs
- neqo-crypto/src/hkdf.rs
- neqo-crypto/src/hp.rs
- neqo-crypto/src/once.rs
- neqo-crypto/src/selfencrypt.rs
- neqo-crypto/src/ssl.rs
- neqo-crypto/src/time.rs
- neqo-crypto/tests/aead.rs
- neqo-crypto/tests/agent.rs
- neqo-crypto/tests/ext.rs
- neqo-crypto/tests/handshake.rs
- neqo-crypto/tests/hkdf.rs
- neqo-crypto/tests/hp.rs
- neqo-crypto/tests/init.rs
- neqo-crypto/tests/selfencrypt.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/tracking.rs
- neqo-transport/tests/conn_vectors.rs
The new version of clippy complains about this
> Stop using wildcard imports

- neqo-http3/src/connection_server.rs
> check_connection_events may actually change state of the connection.

- neqo-crypto/src/agent.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/lib.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/lib.rs
Getting 0-RTT working takes more than this, but this is a start.
I included a few tweaks to the debug levels, because this originated in a bunch of other changes and these are sufficiently related.
Fixes #637.
> Inspect 0-RTT state before attempting it

- neqo-http3-server/src/main.rs
- neqo-server/src/main.rs
> Make the commands default to the text-fixture database

- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/recv_stream.rs
> usize and Res simplifications in recv_stream.rs

- neqo-client/src/main.rs
- neqo-http3-server/src/main.rs
- neqo-interop/src/main.rs
> Fix option conflict and change default values

- neqo-client/src/main.rs
resumption and zerortt tests fail at this moment, but they should pass when issue #659 is fixed
> Add retry, resumption and zerortt tests

- neqo-transport/src/connection.rs
> Drop packets with unknow versions

- neqo-transport/src/connection.rs
I could have sworn that I fixed this already.
> Use impl AsRef rather than a generic parameter

- neqo-qpack/src/encoder.rs
- neqo-transport/src/connection.rs
In reviewing #643 I saw some other small things that weren't the subject of that PR but might make sense to change.
> Qpack encoder small refactor

- neqo-client/Cargo.toml
- neqo-common/Cargo.toml
- neqo-crypto/Cargo.toml
- neqo-crypto/build.rs
- neqo-http3-server/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-interop/Cargo.toml
- neqo-qpack/Cargo.toml
- neqo-server/Cargo.toml
- neqo-transport/Cargo.toml
- test-fixture/Cargo.toml
Use 3_53_RTM tag for NSS in-tree build
> Version 0.4.0

- neqo-client/src/main.rs
All URLs are first queued and then we start downloading as many URLs as possible at the same time. If we get StreamLimitError from Connection::stream_create() we pause the download queue until we receive ConnectionEvent::SendStreamCreatable.
> neqo-client: fix multiplexing test

- neqo-transport/src/connection.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/path.rs
- neqo-transport/src/qlog.rs
- neqo-transport/src/tparams.rs
This doesn't do anything to generate them, that's a lot of work, but we
can easily handle them when they arrive.
Closes #57.
> Handle stateless resets

- neqo-common/src/lib.rs
- neqo-crypto/src/agent.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/tparams.rs
- neqo-transport/tests/server.rs
While working on #686 there were some unrelated mostly log-related changes that I thought were worth having. I broke them out into this PR.
> Test and log-related minor changes

- neqo-common/src/codec.rs
- neqo-crypto/src/agent.rs
- neqo-crypto/src/ext.rs
- neqo-crypto/src/time.rs
- neqo-qpack/src/header_block.rs
- neqo-qpack/src/huffman_decode_helper.rs
- neqo-qpack/src/qpack_send_buf.rs
- neqo-transport/src/pace.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/tracking.rs
Some new compiler warnings, and a bunch new Clippy warnings.
> Rust 1.44 fixes

- docs/linux_build.md
[Issue 495](https://github.com/mozilla/neqo/issues/495)
Build process for Linux (Ubuntu 18.04). Contains system details and step by step process to build, run tests and run HTTP/3 server client program.
> Document build process for linux ubuntu # 495

- neqo-transport/tests/conn_vectors.rs
I don't know why I didn't do this before
> Apply the obvious factoring

- neqo-client/src/main.rs
- neqo-common/src/lib.rs
- neqo-crypto/src/agent.rs
- neqo-http3/src/client_events.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/connection_server.rs
- neqo-http3/src/recv_message.rs
- neqo-http3/src/send_message.rs
- neqo-http3/src/server.rs
- neqo-http3/src/server_connection_events.rs
- neqo-http3/tests/httpconn.rs
- neqo-interop/src/main.rs
- neqo-qpack/src/encoder_instructions.rs
- neqo-transport/src/cid.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/events.rs
- neqo-transport/src/frame.rs
- neqo-transport/src/recv_stream.rs
- neqo-transport/src/send_stream.rs
- neqo-transport/src/server.rs
- neqo-transport/src/tparams.rs
- neqo-transport/tests/server.rs
- test-fixture/src/lib.rs
Which was introduced in Rust 1.42
> use std::matches

- neqo-client/src/main.rs
- neqo-crypto/src/agent.rs
- neqo-crypto/tests/agent.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/crypto.rs
Fixes Issue : #683 
Made changes, compiled and ran tests.
> Renamed enable_ciphers() to set_ciphers()

- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/control_stream_remote.rs
> Make sure to read all data from control and qpack streams after decoding them

- neqo-transport/src/recovery.rs
- neqo-transport/tests/server.rs
> Reset PTO on Retry

- neqo-qpack/src/encoder.rs
- neqo-qpack/src/header_block.rs
- neqo-qpack/src/prefix.rs
- neqo-qpack/src/qpack_send_buf.rs
> Write the header block's prefix properly.

- neqo-client/src/main.rs
Start downloading as soon as possible to ensure sending 0-RTT packet if resumption token was set.
> neqo-client: fix zerortt QNS test

- neqo-client/src/main.rs
When a lost stream frame is retransmitted, this can cause a large
amount of data to suddenly be available for reading. There will only be
a single RecvStreamReadable event generated, so the client needs to
keep reading until no more data is available, or stream flow control
updates can stall.
Read from the stream in a loop instead of just once, when processing the
event.
fixes #772
> client: Make H9 code read all available data on RecvStreamReadable

- docker/Dockerfile
lld is better in some ways that GNU ld, so maybe this will fix our
issues with crashes in CI.
I don't really have any means of testing this out other than trying it out, but it can't be much worse than what we're suffering through.  With your permission, I'll try poking at this.
> Try using lld in CI

- neqo-crypto/src/aead.rs
> Move unused_self lint

- neqo-crypto/src/selfencrypt.rs
> Remove similar names lint override

- neqo-http3/src/client_events.rs
- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/push_controller.rs
- neqo-http3/src/push_stream.rs
- neqo-http3/src/recv_message.rs
- neqo-qpack/src/decoder.rs
- neqo-qpack/src/header_block.rs
Fixes #342 
This is base on #677
> Decoder PushPromise headers

- neqo-transport/src/connection.rs
- neqo-transport/src/recovery.rs
Recent changes in the spec defined initial values for RTT values in a different way, avoiding the need for different calculations for PTO depending on circumstances.
The annoying part is that this still requires that the initial estimates not affect the outcome.  So the calculations here are almost exactly the same as those we had previously.  We already set the timeout the way the spec now describes.  So this basically amounts to a refactoring.
However, prior to having an RTT sample, we previously incorrectly calculated the PTO because we had RTTvar set to 0.  Factoring
differently picked that up.  So while the formula was the same, the inputs were different.
Consequently, we'll send our second Initial packet a little slower than we used to (300ms rather than 120ms).  
I think we should …
> Unified RTT calculation from the latest spec

- neqo-http3-server/src/old_https.rs
Replaces PR826 with a better fix for issue 819
> http3-server: Fix transfer test

- neqo-transport/src/tracking.rs
This will help with the immediate pain of #825 but doesn't completely
resolve it.
> tracking: Remove log message in inner loop

- neqo-crypto/Cargo.toml
I got the same error as https://github.com/rust-lang/rust-bindgen/issues/1694 when trying to build this project.
> Fix bindgen features

- neqo-transport/src/send_stream.rs
Currently, we send stream data blocked or data blocked frames if the
amount of data we're trying to send is greater than the flow control
space available. That's not really fair: since we increased the size of our
send buffer, there may be many bytes buffered ahead of what we're trying
to stuff into the buffer, and sending those will likely cause the peer
to send flow control updates so we're not actually blocked right now.
Instead, only send blocked frames when 1) an atomic send fails due to lack
of credits and 2) when we actually mark a byte sent that equals the
amount of credit we've been given.
fixes #863
> Do not report blocked to peer until credits run out

- neqo-transport/src/cc.rs
- neqo-transport/src/recovery.rs
This is the commits from #878 that were reviewed but didn't need either tests added or further discussion. I'm hoping these can be merged sooner.
> Fix easy stuff from 878

- neqo-transport/src/cc.rs
In diagnosing QNS Neqo server DC failures, I found a few bugs to fix.
Please see individual commit logs for details.
> Fix some congestion control bugs and improve cwnd qlogging

- neqo-transport/src/connection.rs
This was:
1. using milliseconds instead of microseconds
2. not applying the exponent
This was likely skewing our RTT estimates no end, causing all sorts of problems with throughput.  I discovered this by writing a test, but I can't land that test yet because it runs afoul of an NSS bug.
> Fix ACK Delay decoding

- .circleci/config.yml
- .mergify.yml
- README.md
- docker/Dockerfile
Also we need to on GitHub:
Navigate to Settings > Branches
Select main as your default branch
Update your branch protection rules
Navigate to Code > Branches and delete master
> Rename master branch to main

- neqo-client/src/main.rs
When we read the results from the Http3Client, we need to make sure we
read everything that's available, instead of being limited by the size of
our buffer.
This fixes intermittent issues on QNS with client=neqo server=mvfst.
> client: Fix client for http3

- neqo-transport/src/cc.rs
- neqo-transport/src/connection.rs
- neqo-transport/src/tracking.rs
Take 2.  See #875 for the original, nearly complete version.
> Accurate byte counting

- neqo-http3/src/connection_client.rs
- neqo-qpack/src/decoder.rs
This will fix [bug 1656870](https://bugzilla.mozilla.org/show_bug.cgi?id=1656870)
> We were entering same stream multiple time into the block tream list.

- neqo-common/src/qlog.rs
This was sitting there in my editor and I couldn't help noticing the
repetition.
> Factor qlog::add_event

- neqo-qns/run_endpoint.sh
> fix endpoint script

- neqo-transport/src/connection.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/src/qlog.rs
- neqo-transport/src/tparams.rs
- test-fixture/src/assertions.rs
This randomizes the value of the spin bit at the same time.
Based on draft-thomson-quic-bit-grease-00, which seems to have attracted quite a bit of attention rather quickly.  Pun intended.
> Grease the QUIC bit

- neqo-transport/src/cc.rs
- neqo-transport/src/tracking.rs
Of course, now I realized that I have unmerged fixes on another
branch that will have to be reconciled with this...
Closes #849.
> Remove shortcuts from persistent congestion

- neqo-http3/src/client_events.rs
- neqo-http3/src/connection_client.rs
Also add a funcion is_zerortt().
> Post an event when a connection changes to ZeroRtt state.

- neqo-common/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-http3/src/hframe.rs
- neqo-qpack/Cargo.toml
And a little code duplication too.
> Remove num-traits dependency

- neqo-transport/src/frame.rs
How this escaped notice for so long is somewhat shocking.
> Drop frame type from application CONNECTION_CLOSE

- neqo-transport/src/connection/tests/cc.rs
- neqo-transport/src/connection/tests/recovery.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/stats.rs
Count single PTO, 2 PTOs in a row, 3 PTOs in a row, etc separately.
> Add stats that show how many PTOs a connection had

- neqo-client/src/main.rs
- neqo-crypto/src/agent.rs
- neqo-http3/src/client_events.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/connection_server.rs
- neqo-http3/src/server.rs
- neqo-interop/src/main.rs
- neqo-transport/src/addr_valid.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/handshake.rs
- neqo-transport/src/connection/tests/mod.rs
- neqo-transport/src/connection/tests/resumption.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/events.rs
- neqo-transport/tests/server.rs
If both resumption a ticket and a token have been received post a ResumptionToken event immediately.
If only a ticket has been received wait for a token for 3 * PTO before posting a ResumptionToken event.
> Post ResumptionToken events

- neqo-transport/src/recv_stream.rs
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1655356
> Do not truncate data_ranges when overlapping frames come in

- neqo-client/src/main.rs
- neqo-common/src/codec.rs
- neqo-http3/src/connection_client.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/keys.rs
- neqo-transport/src/crypto.rs
I haven't been able to get a copy of wireshark that supports the latest version, so I need to test this.
> Add key update for network simulator

- neqo-transport/tests/sim/mod.rs
The time stuff was not very good for tracking changes.  Logging the relative time since the start helped a lot.
> Improve simulator logging a tiny bit

- neqo-transport/src/connection/idle.rs
The "New" state here wasn't really carrying its weight, and updating it meant that functions that should have been `&self` had to be `&mut self` instead.  And we never really hit the "New" state in practice anyway as we move to one of the other states as soon as we send anything.  This is much simpler.
> Remove a state from the IdleTimeout class

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/keys.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/lib.rs
This uses new numbers.
Testing this will be challenging.  I've got to do that though, so this is not done yet.
> Add AEAD limits

- neqo-client/src/main.rs
> Fix QNS failures

- neqo-client/src/main.rs
Added when trying to diagnose #993. (I still don't understand how that helps, by the way.)
> Some minor tweaks to error reporting

- neqo-http3/src/connection_client.rs
- neqo-transport/src/connection/tests/stream.rs
- neqo-transport/src/recv_stream.rs
> Do not post multiple unnecessary  DataReadable events

- neqo-transport/src/frame.rs
This is something I've wanted to do for a while now.  Those macros were
unnecessary.
> Functions >> macros

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/handshake.rs
- neqo-transport/src/connection/tests/idle.rs
- neqo-transport/src/connection/tests/keys.rs
- neqo-transport/src/connection/tests/mod.rs
- neqo-transport/src/connection/tests/recovery.rs
- neqo-transport/tests/connection.rs
- neqo-transport/tests/server.rs
- test-fixture/src/assertions.rs
- test-fixture/src/lib.rs
There is some refactoring here for tests, but it's an easy change.
It's server stuff, but I wanted to validate the proposal and it's
minimally disruptive.
> Pad server Initial if ack-eliciting

- neqo-client/src/main.rs
We routinely fail to get resumption tokens from our own server in the
interop runner.  This should fix that.
> Drain events before closing to get token

- neqo-common/src/codec.rs
- neqo-common/src/incrdecoder.rs
I needed these for my work on migration.
> Encoder additions

- neqo-transport/src/connection/mod.rs
As we use this for logging, it helps to have the value stick around.
It's only used for logging, so the cost is minimal.  I've included some
logging tweaks at the same time.
> Save ODCID on the server too

- neqo-server/src/main.rs
Might as well.  More opportunities to learn this way.
> Support 0-RTT test

- neqo-transport/src/stats.rs
I wanted this for debugging something and thought it worth keeping.
> Print frame stats

- neqo-client/src/main.rs
- neqo-http3/src/connection_client.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/src/packet/retry.rs
> Support drafts -31 and -32

- neqo-http3/src/connection_client.rs
- neqo-transport/src/connection/mod.rs
> truncate reason string

- neqo-qpack/src/encoder.rs
> Remove if stream-cancel instruction has been received.

- neqo-client/Cargo.toml
- neqo-common/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-qpack/Cargo.toml
- neqo-server/Cargo.toml
- neqo-transport/Cargo.toml
In order to solve Issue #607, upgrade to qlog 0.4.0.
> Update qlog to 0.4.0 (#1063)

- neqo-client/src/main.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/server.rs
- neqo-interop/src/main.rs
- neqo-server/src/main.rs
- neqo-server/src/old_https.rs
- neqo-transport/src/cc/mod.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/handshake.rs
- neqo-transport/src/connection/tests/mod.rs
- neqo-transport/src/connection/tests/zerortt.rs
- neqo-transport/src/connection_parameters.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/sender.rs
- neqo-transport/src/server.rs
- neqo-transport/tests/conn_vectors.rs
- neqo-transport/tests/server.rs
- test-fixture/src/lib.rs
Also set the limits to 100 for the QNS Zerortt test.
> Add possibilty to set INITIAL_MAX_STREAMS_BIDI/UNI limits.

- neqo-transport/src/cc/classic_cc.rs
- neqo-transport/src/connection/tests/cc.rs
- neqo-transport/src/connection/tests/mod.rs
The change will only stop cwnd from increasing in case cc is app-limited. The cwnd will not be reduce afoter a long periond of app-limmited state.
> Simple calculation for app-limited state

- neqo-transport/src/addr_valid.rs
- neqo-transport/src/connection/tests/mod.rs
- neqo-transport/src/flow_mgr.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/tests/sim/connection.rs
And some clippy fixups to make it build cleanly
The bug is in flow_mgr.  There is a guard in packet/mod.rs.  The rest is clippy complaining.
> Tweaks to frame writing code

- .circleci/config.yml
> Test command-line utilities in CI

- .circleci/config.yml
The last one was generating an undetected error, which isn't great.  Test this out as a draft.
> Try loopback

- neqo-transport/tests/server.rs
> Test for max streams after 0-RTT rejection

- neqo-client/src/main.rs
- neqo-crypto/src/constants.rs
- neqo-crypto/src/p11.rs
- neqo-crypto/src/time.rs
- neqo-http3/src/recv_message.rs
- neqo-interop/src/main.rs
- neqo-qpack/src/decoder.rs
- neqo-server/src/main.rs
- neqo-transport/src/cc/mod.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/server.rs
- qns/interop.sh
Based on #1091, but it doesn't strictly have to be (I just couldn't validate it without fixing those lints).
> Use Cubic in interop testing

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/handshake.rs
This error
[here](https://interop.seemann.io/logs/2021-03-03T16:03/neqo_quic-go/handshakecorruption/output.txt)
was the result of the server receiving a bad Initial packet and then
trying to check timers.  Because we assume that we have a path when we
are checking timers, bad things happened, because we didn't have a path
yet.
This changes the logic to just return `Output::None` when the server
doesn't have anything to do or send.
> Fix a server crash

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/params.rs
> Create TransportParameters at one place

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/handshake.rs
> Ignore Initial and Handshake packet from a different IP address and port

- neqo-transport/src/recovery.rs
> Avoid crashing while calculating now - loss_delay

- neqo-client/src/main.rs
- neqo-common/src/header.rs
- neqo-common/src/lib.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/recv_message.rs
- neqo-http3/src/server.rs
- neqo-http3/tests/httpconn.rs
- neqo-interop/src/main.rs
- neqo-qpack/src/decoder.rs
- neqo-qpack/src/encoder.rs
- neqo-qpack/src/header_block.rs
- neqo-qpack/src/lib.rs
- neqo-server/src/main.rs
> Do not cancel a stream if disallowed headers are present, just remove them

- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/stream_type_reader.rs
One of these is a false positive that appears new.
> More clippy

- neqo-transport/src/connection/idle.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/idle.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/recv_stream.rs
- neqo-transport/src/streams.rs
No tests, and not enough time to do anything.
Is this a good design?
> Keep-alives

- neqo-transport/src/connection/idle.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/idle.rs
Add tests for:
- multiple keep-alive timeouts
- for PING getting lost
> Fix bug 1724408 and fix keep_alive_outstanding it was never set to false

- neqo-transport/src/fc.rs
- neqo-transport/src/recv_stream.rs
For after #1187 lands.
The thing that I want to get most is the conversion of if statement to match statement.  Using if statements here works, but it isn't a very good practice as the if statement depends on the enum remaining as a two-item enum.  That's almost certainly fine here, but the match is neater.
> Simple factoring of some flow control stuff

- neqo-client/src/main.rs
Fixes #1136 if I understand what needs to be cleaned up correctly
> Remove streams with the FIN bit set in the header

- neqo-transport/src/recovery.rs
> Avoid panicing when substracting Instants

- neqo-qpack/src/header_block.rs
- neqo-qpack/src/qpack_send_buf.rs
This adds some tests and safeguards for that.
> Base calculations in QPACK can over- or under-flow

- neqo-transport/src/connection/mod.rs
This won't change anything, but it is smaller.
> Use saturating_duration_since for next_delay

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/mod.rs
- neqo-transport/src/rtt.rs
- neqo-transport/src/stats.rs
Nothing complicated.  I added some tests too.
Closes #1088.
> Add RTT stats

- neqo-http3/src/buffered_send_stream.rs
- neqo-http3/src/control_stream_local.rs
- neqo-http3/src/lib.rs
BufferedStream may have some data in a buffer and it will always make use to send the buffered data first.
> Create a BufferedStream

- neqo-client/src/main.rs
Improvements to the client made in the process of trying to debug something.
- **Create directory for client's output file**
- **Support connecting only to IPv4 or IPv6**
> Improve client

- neqo-transport/src/dump.rs
> Disable dumping packets if logging is disabled

- neqo-http3/src/connection.rs
- neqo-http3/tests/httpconn.rs
The server side did not know about ZeroRTT state. It was working because the server API was not strict about the state of the connection when writing data into a stream. As the last changes unified the API, the server started to trigger assertion, i.e. the  http3 connection was in the initialized state and in that state it is not possible to write data.
The patch sets ZeroRtt state on the server side as well.
> Make server work with ZeroRtt

- neqo-http3/Cargo.toml
- neqo-http3/src/headers_checks.rs
> Use enumset for the pseudo headers checks

- neqo-http3/src/server.rs
- neqo-server/src/main.rs
- neqo-server/src/old_https.rs
- neqo-transport/src/server.rs
This was still using an old method of configuration, which meant that it
didn't work.
> Update preferred address config for servers

- neqo-http3/src/connection_client.rs
- neqo-http3/src/server.rs
- neqo-transport/src/connection/tests/stream.rs
- neqo-transport/src/streams.rs
> Generate ConnectionEvent::SendStreamCreatable at startup

- neqo-http3/src/connection_client.rs
- neqo-http3/src/headers_checks.rs
> reset stream when receiving 101

- neqo-crypto/Cargo.toml
- neqo-crypto/build.rs
See [bug 1751331](https://bugzilla.mozilla.org/show_bug.cgi?id=1751331).
> Use the mozbuild crate when building in gecko

- neqo-common/Cargo.toml
- neqo-common/src/log.rs
> Use 4-argument version of the log API

- neqo-common/src/hrtime.rs
- neqo-crypto/src/cert.rs
- neqo-crypto/src/ech.rs
- neqo-crypto/src/hp.rs
- neqo-crypto/src/lib.rs
- neqo-crypto/src/p11.rs
- neqo-crypto/src/prio.rs
- neqo-crypto/src/ssl.rs
- neqo-crypto/src/time.rs
- neqo-transport/src/cc/classic_cc.rs
This restores the code to working status after a change in Rust library behaviour.
> Checked duration since

- neqo-server/src/main.rs
- neqo-transport/src/cc/classic_cc.rs
This was a bit more work than I anticipated, but still worth doing right.
I needed to move the implementation of HttpServer to a new type, which wasn't too bad.  I also had to copy the buffer that is sent, but that should be better than doing an allocation of arbitrary size, as we used to do.
Closes #1345.
> Send any amount of data as a server.

- neqo-crypto/src/p11.rs
- neqo-crypto/src/prio.rs
- neqo-crypto/src/ssl.rs
> Remove workaround for bindgen#1651

- neqo-http3/src/connection.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/lib.rs
- neqo-transport/src/connection/mod.rs
> Add  documentation for the  neqo-http3  code

- neqo-http3/tests/httpconn.rs
- neqo-transport/src/connection/idle.rs
- neqo-transport/src/connection/tests/idle.rs
> Do not calculate keepalive's timeout when a keepalive is outstanding.

- neqo-http3/src/connection.rs
- neqo-http3/src/connection_server.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/mod.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/sessions.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/server_events.rs
- neqo-http3/tests/webtransport.rs
This PR is intended to fix #1384
> Support redirects in WebTransport session accept responses

- neqo-http3/src/connection.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/datagrams.rs
> Multiply stream id by 4

- neqo-common/src/hrtime.rs
- neqo-crypto/tests/agent.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/datagrams.rs
- neqo-http3/src/server.rs
- neqo-http3/src/settings.rs
- neqo-qpack/src/decoder.rs
- neqo-transport/src/ackrate.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/resumption.rs
- neqo-transport/src/recovery.rs
These are all pretty good suggestions and in line with our MSRV of 1.57 (some of the changes need 1.54).
> Changes suggested by clippy in rust 1.66.1

- neqo-transport/tests/network.rs
- neqo-transport/tests/sim/connection.rs
The one-way delays here are in the order of years.
Test modified to validate that this was indeed possible.  It is.
> Add a test for a seriously long timeout

- README.md
- neqo-crypto/build.rs
- Update the gecko build docs.
- Update failing build.rs when built with gecko.
> Update gecko build docs

- neqo-common/src/timer.rs
- neqo-http3/src/client_events.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/features/extended_connect/mod.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/mod.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/sessions.rs
- neqo-http3/src/features/extended_connect/webtransport_session.rs
- neqo-http3/src/server.rs
- neqo-http3/src/server_connection_events.rs
- neqo-http3/src/server_events.rs
- neqo-http3/tests/webtransport.rs
- neqo-transport/src/cc/tests/cubic.rs
- neqo-transport/src/cc/tests/new_reno.rs
- neqo-transport/src/connection/tests/idle.rs
- neqo-transport/src/tracking.rs
- Add a headers argument to session_start
- Add an optional headers argument to session_end
Fixes: #1364
> Add headers to session_start and session_end

- neqo-client/Cargo.toml
- neqo-common/Cargo.toml
- neqo-crypto/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-interop/Cargo.toml
- neqo-qpack/Cargo.toml
- neqo-server/Cargo.toml
- neqo-transport/Cargo.toml
- test-fixture/Cargo.toml
> neqo v0.6.4

- README.md
took me a while to find how to get QLOGs, hence a few lines in the readme.
> Add info for using QLOGs

- neqo-crypto/build.rs
> Set target to arm64

- neqo-client/src/main.rs
- neqo-common/src/codec.rs
- neqo-common/src/hrtime.rs
- neqo-common/src/incrdecoder.rs
- neqo-crypto/Cargo.toml
- neqo-crypto/src/result.rs
- neqo-crypto/src/time.rs
- neqo-crypto/tests/hp.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/headers_checks.rs
- neqo-http3/src/server.rs
- neqo-http3/tests/priority.rs
- neqo-qpack/src/decoder.rs
- neqo-server/src/main.rs
- neqo-transport/src/cc/tests/cubic.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/ackrate.rs
- neqo-transport/src/connection/tests/idle.rs
- neqo-transport/src/connection/tests/mod.rs
- neqo-transport/src/connection/tests/priority.rs
- neqo-transport/src/connection/tests/stream.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/fc.rs
- neqo-transport/src/send_stream.rs
- neqo-transport/src/streams.rs
- neqo-transport/src/tparams.rs
- neqo-transport/src/tracking.rs
- neqo-transport/tests/server.rs
- neqo-transport/tests/sim/connection.rs
- test-fixture/src/lib.rs
In addition to fixing lint bindings, we've a few more to add.
> More lints

- neqo-common/src/codec.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/mod.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/streams.rs
- neqo-http3/src/features/extended_connect/webtransport_streams.rs
- neqo-http3/src/lib.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/send_stream.rs
> Expose SendStreamStats

- neqo-crypto/src/agent.rs
- neqo-crypto/tests/agent.rs
- neqo-crypto/tests/ext.rs
- neqo-crypto/tests/handshake.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/params.rs
Replaces PR #1441 (rebased on main)
> Add support for configuring greasing

- neqo-transport/src/recv_stream.rs
This is for `WebTransportReceiveStreamStats`.
Note that there will be another commit for the implementation in `webtransport_stream`.
> Implement RecvStreamStats

- neqo-transport/src/cc/tests/new_reno.rs
https://github.com/mozilla/neqo/pull/1465#discussion_r1364475488
> Capture packet number in closure to simplify congestion control test

- neqo-transport/src/cc/classic_cc.rs
This doesn't change behavior, simplifies after_recovery_start check by removing the ambiguousness when the recovery packet was sent at the same time as some other packet.
Noticed while implementing #1465 that I would prefer using pn instead of time_stamp.
> Use packet number instead of time sent to identify packets sent after recovery event

- neqo-transport/src/cc/classic_cc.rs
Fixes #1475 
Still have to fix test cases. All green dots are ack-ranges that don't count towards cwnd due to app-limit detection.
| before patch | after patch |
| --- | --- |
| ![before_patch](https://github.com/mozilla/neqo/assets/36711370/4e4daa42-ec41-41c4-848c-8eaa81f51d34) | ![after_patch](https://github.com/mozilla/neqo/assets/36711370/71dbeb39-ca8f-43e7-bcde-a8726e7a79ad) |
Notice that with the patch applied during normal operation without packet loss, all ack ranges are not app-limited. The slightly longer drops are due to pacer and disappear with also #1478 applied.
> Count as non-applimited when at least one packet was sent during non-applimited time period

- .github/workflows/check.yml
- neqo-common/src/hrtime.rs
- neqo-crypto/build.rs
> Expand the CI matrix and generate coverage information

- .github/workflows/check.yml
Also ignore changes to some paths/files that don't need to trigger CI.
> Don't run twice on pushes to PRs

- neqo-common/src/hrtime.rs
- neqo-crypto/src/ext.rs
I.e. the ones found via the new expanded CI matrix.
Leaving this as a draft PR until CI is green.
> Fix clippy issues on MacOS and Windows

- .github/workflows/check.yml
To see if this addresses #1521
> Replace nextest with test

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/recv_stream.rs
- neqo-transport/tests/connection.rs
This is a denial of service opportunity, but one that only is available to an authenticated peer or while we are willing to receive Initial packets.  This fits the existing DoS threat model.
> Ensure that too much crypto data is fatal for a connection

- neqo-client/src/main.rs
- neqo-http3/tests/httpconn.rs
- neqo-interop/src/main.rs
- neqo-server/src/main.rs
- neqo-server/src/old_https.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/state.rs
- neqo-transport/src/events.rs
- neqo-transport/src/frame.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/src/qlog.rs
- neqo-transport/src/recv_stream.rs
- neqo-transport/src/send_stream.rs
- neqo-transport/src/server.rs
- neqo-transport/src/streams.rs
- neqo-transport/src/tparams.rs
- neqo-transport/tests/connection.rs
https://rust-lang.github.io/rust-clippy/master/index.html#/semicolon_if_nothing_returned
---
Breaking https://github.com/mozilla/neqo/pull/1532 into smaller pull requests to ease review and reduce merge conflicts.
> refactor: add semicolon if nothing is returned

- neqo-client/src/main.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/params.rs
- neqo-transport/src/pace.rs
- neqo-transport/src/path.rs
- neqo-transport/src/recovery.rs
- neqo-transport/src/sender.rs
This PR enables tests in pacer.rs and also make pacing configurable.
> Make pacing configurable

- .github/workflows/qns.yml
- qns/.dockerignore
- qns/Dockerfile
We don't need this to run so often.
> Add workflow_dispatch for QNS, reduce rate

- update_version
Some time ago I wrote a script to update neqo version. I will just post the PR as a draft, I do not want to add it to repo.
> Script to update neqo version

- .github/workflows/check.yml
> ci: Use lld to link

- .github/workflows/check.yml
- neqo-transport/Cargo.toml
The windows build ignores this attribute, but there is no point in having a warning.
> Don't use lld on windows

- neqo-client/Cargo.toml
- neqo-common/Cargo.toml
- neqo-crypto/Cargo.toml
- neqo-http3/Cargo.toml
- neqo-interop/Cargo.toml
- neqo-qpack/Cargo.toml
- neqo-server/Cargo.toml
- neqo-transport/Cargo.toml
- test-fixture/Cargo.toml
> neqo v0.6.9

- neqo-qpack/src/encoder.rs
- neqo-qpack/src/lib.rs
- neqo-server/src/main.rs
- neqo-transport/src/addr_valid.rs
- neqo-transport/src/cid.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/state.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/lib.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/src/packet/retry.rs
- neqo-transport/src/path.rs
- neqo-transport/src/tracking.rs
I've just removed all of the internal errors as issue  #1086 don't know if we need to remove other code, the issue description was not clear to me. 
If is needed to make any changes I gladly would do it
> chore: Removed InternalErrors added in #1085 

- .github/workflows/check.yml
Remove separate bench build, just run the benchmarks as tests, which works, without the performance hit.
> Test benchmarks

- .github/workflows/check.yml
- neqo-transport/src/cid.rs
And also run release tests during CI (one one platform and Rust toolchain).
> fix: Don't call `write_entry` from inside `debug_assert!`

- Cargo.toml
> neqo v0.7.1

- .github/workflows/check.yml
To see if this magically fixes #1652
Also could be faster...
> ci: Bump MacOS runner to `macos-14`

- .codecov.yml
- .github/workflows/qns.yml
> ci: Give QNS workflow permissions to upload packages

- .github/CODEOWNERS
> chore: Simplify `CODEOWNERS`

- .github/actions/rust/action.yml
- .github/workflows/bench.yml
- .github/workflows/check.yml
If it ends up speeding CI up; testing.
> ci: Use Swatinem/rust-cache

- .github/workflows/bench.yml
- .github/workflows/check.yml
Hopefully addresses spurious "An existing connection was forcibly closed by the remote host" issue on Windows CI.
> ci: Delay client start during transfer test

- .github/workflows/check.yml
And small changes, like not trying to use `lld` anymore on Windows, which never really worked.
> ci: Hopefully fix the spurious Windows transfer test failure

- .github/actions/nss/action.yml
- .github/workflows/check.yml
Because on the bencher, `git` now has issues. You can't win.
> ci: Try `hg` and then try `git` to download NSPR and NSS

- .github/workflows/mutants.yml
> ci: Do full `cargo mutants` run twice a week

- neqo-transport/src/connection/tests/mod.rs
Broken out of #1678 to reduce the size of that PR.
> test: Let packets be modified with a closure during tests

- fuzz/Cargo.toml
- fuzz/fuzz_targets/packet.rs
Review suggestions for https://github.com/mozilla/neqo/pull/1764/.
> #1764 Review suggestions

- .dockerignore
- .github/actions/quic-interop-runner/action.yml
- qns/Dockerfile
- qns/interop.sh
* Record client and server logs during run
* Fix result comment table formatting
* Fix docker image build (on macOS at least)
> chore: Fix various QNS issues

- Cargo.toml
Instead of having to look it up in a table.
> chore: Link to actual MSRV Fx is using

- .github/actions/nss/action.yml
- .github/actions/pr-comment-data-export/action.yml
- .github/actions/quic-interop-runner/action.yml
- .github/workflows/actionlint.yml
- .github/workflows/bench-comment.yml
- .github/workflows/bench.yml
- .github/workflows/check.yml
- .github/workflows/mutants.yml
- .github/workflows/qns-comment.yml
- .github/workflows/qns.yml
- qns/Dockerfile
> ci: Pin deps and limit token permissions

- neqo-transport/Cargo.toml
Resolves <https://github.com/mozilla/neqo/issues/1858>.
> build: upgrade `indexmap` 1.9 → 2.2

- .github/actions/pr-comment/action.yml
- .github/actions/quic-interop-runner/action.yml
- .github/actions/rust/action.yml
- .github/workflows/qns.yml
> ci: Pin more deps

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/state.rs
- neqo-transport/src/connection/tests/close.rs
- neqo-transport/src/tracking.rs
> fix: Include an ACK with a CONNECTION_CLOSE

- .github/workflows/qns.yml
> ci: More fixes to eventually generate a diff for QNS results

- .github/workflows/qns.yml
> ci: Need to run QNS on push to main

- Cargo.toml
> neqo v0.7.7

- qns/Dockerfile
> ci: Pin rustup-init

- Cargo.toml
> neqo_0.7.9

- .taskcluster.yml.disabled
Until someone who understands it can debug.
> ci: Disable taskcluster again

- .github/workflows/dependency-review.yml
> ci: Need to run dependency-review.yml for merge queue

- .github/workflows/dependency-review.yml
See https://github.com/actions/dependency-review-action/issues/456#issuecomment-1537840047
> ci: dependency-review needs refs for merge_queue

- .github/workflows/bench.yml
- .github/workflows/check.yml
- .github/workflows/firefox.yml
- .github/workflows/mutants.yml
- .github/workflows/pr-comment.yml
- .github/workflows/qns.yml
This reverts commit 735be28348cc543bbe751eec7ff89e6722e5ca51.
Maybe  #1985 or  #1986 pan out.
> Revert "ci: Trigger secondary checks off `check.yml` (#1984)"

- .github/actions/nss/action.yml
> ci: Cache NSS build

- .github/actions/rust/action.yml
- .github/workflows/bench.yml
- .github/workflows/check.yml
- .github/workflows/mutants.yml
Should speed up some CI checks.
> ci: Don't install unneeded rust components by default

- .github/CODEOWNERS
Discussed yesterday with @KershawChang. @martinthomson, are you OK with this? @mxinden is pretty actively reviewing, so it might unblock getting PRs merged when both of you are busy. 
(We also need to give @mxinden repo write access if we do this.)
> Add @mxinden to CODEOWNERS

- neqo-crypto/src/lib.rs
Instead, pass an error up.
Fixes #1675 (again, hopefully)
> fix: Don't assert in NSS `version_check`

- neqo-transport/src/cc/classic_cc.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/recovery/mod.rs
- neqo-transport/src/tparams.rs
- neqo-transport/src/tracking.rs
> chore: Lower some log levels

- .github/workflows/firefox.yml
> ci: Only build Firefox for non-draft PRs

- .github/actions/rust/action.yml
Needed for https://github.com/mozilla/mtu/pull/21.
> ci(rust): add `targets` input

- .github/workflows/bench.yml
- .github/workflows/check.yml
Until https://github.com/rust-lang/rustup/issues/4019 is fixed.
CC @mxinden
> ci: Pin nightly to `nightly-2024-09-01`

- .github/actions/nss/action.yml
Verbose, single-threaded build
> ci: Unpin nss

- .github/workflows/check.yml
- .github/workflows/clippy.yml
- .github/workflows/machete.yml
- .github/workflows/mutants.yml
- .github/workflows/rustfmt.yml
* `cargo machete`
* `cargo fmt`
* `cargo clippy`
> ci: Run more things in parallel

- neqo-transport/benches/transfer.rs
Sometimes, you have to tell it to be quiet.
And sometimes, it misses an obvious improvement.
> clippy isn't always right

- neqo-bin/benches/main.rs
- neqo-bin/src/client/http3.rs
- neqo-bin/src/client/mod.rs
- neqo-bin/src/lib.rs
Add 100 MiB upload benchmark to `neqo-bin`.
Might help answer questions like:
- Is Neqo upload as fast as download?
- Comparing Firefox and Chromium h3 upload speed, is Neqo the bottleneck, ...
> bench(bin): add 100MB upload benchmark

- .github/workflows/qns.yml
Copy/paste error when using code from `bench.yml`
> Don't include runner name in QNS cache key

- .github/workflows/qns.yml
It seems like the cache is not resroring; checking why.
> ci: Fix QNS diff to main

- .github/workflows/qns.yml
Include main branch SHA, and use styling that is hopefully more visible. Also fix spacing issues.
(The SHA will start showing up when this is merged to main.)
> ci: Better formatting for QNS diff

- .github/workflows/qns.yml
> ci: Try a different formatting for the qns diff

- neqo-bin/src/server/http3.rs
- neqo-common/src/header.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/mod.rs
- neqo-http3/src/features/extended_connect/tests/webtransport/sessions.rs
- neqo-http3/src/headers_checks.rs
- neqo-http3/src/recv_message.rs
- neqo-http3/tests/webtransport.rs
So this just uses it.
While I'm here, eliminate some code redundancies.
Fixes #1255
> chore: Simplify some webtransport checks

- neqo-http3/src/client_events.rs
- neqo-http3/src/connection_client.rs
- neqo-http3/src/frames/hframe.rs
- neqo-http3/src/frames/tests/hframe.rs
- neqo-http3/src/frames/tests/reader.rs
- neqo-http3/src/lib.rs
- neqo-http3/src/push_controller.rs
- neqo-http3/src/push_id.rs
- neqo-http3/src/recv_message.rs
- neqo-http3/src/stream_type_reader.rs
> feat: Create `PushId` type

- Cargo.toml
- neqo-common/src/incrdecoder.rs
- neqo-crypto/tests/handshake.rs
- neqo-http3/src/connection_client.rs
- neqo-qpack/src/decoder.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/state.rs
- neqo-transport/src/fc.rs
- neqo-transport/src/frame.rs
- neqo-transport/src/path.rs
- neqo-transport/src/qlog.rs
- neqo-transport/src/recovery/mod.rs
- neqo-transport/src/recv_stream.rs
- neqo-transport/src/send_stream.rs
- neqo-transport/src/sender.rs
- test-fixture/src/lib.rs
> chore: Enable clippy `if_then_some_else_none` lint

- Cargo.toml
- neqo-crypto/src/cert.rs
- neqo-http3/src/frames/reader.rs
- neqo-http3/src/push_controller.rs
- neqo-transport/src/connection/idle.rs
> chore: Enable clippy `multiple_inherent_impl` lint

- neqo-qpack/src/decoder.rs
- neqo-transport/src/connection/tests/migration.rs
- neqo-transport/src/tparams.rs
- test-fixture/src/sim/mod.rs
> chore: `cargo clippy --fix`

- .github/actions/rust/action.yml
This reverts commit e18658de44dab3e730c8b5ca0c00fc086fcef9c1.
> Revert "ci: pin nightly (#2370)"

- Cargo.lock
See release on mozilla/mtu:
https://github.com/mozilla/mtu/releases/tag/v0.2.4
> deps: update mtu to v0.2.4

- .github/actions/nss/action.yml
- .github/workflows/check.yml
> ci: Add `ubuntu-24.04-arm` to the `check` matrix

- .codecov.yml
Might make navigating the coverage info easier? Let's see.
> ci: Define components for codecov

- neqo-crypto/build.rs
This builds upon the patches in https://bugzilla.mozilla.org/show_bug.cgi?id=1950258
> Use mozbuild::config items rather than extra-bindgen-flags

- .github/workflows/check-vm.yml
- .github/workflows/check.yml
- .github/workflows/clippy.yml
- .github/workflows/deny.yml
- .github/workflows/dependency-review.yml
- .github/workflows/firefox.yml
- .github/workflows/fuzz-bench.yml
- .github/workflows/machete.yml
- .github/workflows/mutants.yml
- .github/workflows/qns.yml
- .github/workflows/rustfmt.yml
- .github/workflows/sanitize.yml
Let's just run them always.
Fixes #2493
> ci: Remove `paths-ignore` from workflows

- neqo-transport/src/connection/mod.rs
- neqo-transport/src/connection/tests/idle.rs
Given a connection with both PTO and idle timeout firing, do not send two PINGs. Instead, have the idle timeout piggy back on the PTO PING.
---
Broken out of https://github.com/mozilla/neqo/pull/2129 and added unit test.
> fix(transport): make idle timeout PING piggy back on PTO PING 

- neqo-transport/src/recovery/mod.rs
Follow up to:
https://github.com/mozilla/neqo/pull/2129#pullrequestreview-2706256501
> refactor(transport/recovery): use early `continue` to reduce indentation

- .github/actions/nss/action.yml
#2448 broke this by changing `actions/cache` to `actions/cache/restore` :-(
> ci: Fix the NSS cache

- neqo-transport/src/connection/mod.rs
By renaming the field from `connection_ids` to `cids`.
```
warning: field name starts with the struct's name
--> neqo-transport/src/connection/mod.rs:248:5
|
248 |     connection_ids: ConnectionIdStore<[u8; 16]>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#struct_field_names
= note: `-W clippy::struct-field-names` implied by `-W clippy::pedantic`
= help: to override `-W clippy::pedantic` add `#[allow(clippy::struct_field_names)]`
```
> chore: Fix `clippy::struct_field_names`

- .github/workflows/bench.yml
- neqo-bin/Cargo.toml
- neqo-bin/benches/main.rs
- neqo-bin/src/bin/client.rs
- neqo-bin/src/bin/server.rs
This seems to speed up things quite a bit.
Also fix the percentage change calculation in the CI table. I don't know what I was thinking when I did the original formula. Math is hard I guess.
> fix: Switch from `tokio` `multi_thread` to `current_thread`

- neqo-transport/src/recovery/mod.rs
> refactor(transport/recovery): use PacketNumberSpace Debug in qdebug

- .github/actions/rust/action.yml
- .github/workflows/fuzz-bench.yml
- fuzz/Cargo.toml
The fuzzer needs its default features.
(Also run as matrix, and run a full `build and not just `check`.)
Fixes https://github.com/google/oss-fuzz/pull/13114.
> fix: Unbreak the fuzzer

- neqo-bin/src/udp.rs
See https://github.com/mozilla/neqo/pull/2470#discussion_r2025802772
> chore: Fix searchfox URL

- neqo-transport/src/path.rs
> fix: Simplify `Paths::path_response()`

- neqo-http3/src/connection_client.rs
- neqo-http3/src/frames/reader.rs
- neqo-http3/src/stream_type_reader.rs
Let's see if this moves the needle on anything...
> fix: Move allocations outside of loops

- .github/actions/nss/action.yml
- .github/actions/rust/action.yml
- .github/workflows/bench.yml
- .github/workflows/check.yml
@mxinden said that @jrmuizel suggested this, so we can compare against other Rust QUIC stacks.
> ci: Add `cloudflare/quiche` and `aws/s2n-quic` to bench

- neqo-common/src/codec.rs
- neqo-http3/src/frames/hframe.rs
> feat: Implement `Write` for `Encoder`

- neqo-bin/benches/main.rs
- neqo-bin/src/server/http09.rs
- neqo-bin/src/server/http3.rs
- neqo-common/src/header.rs
- neqo-common/src/lib.rs
- neqo-crypto/src/agent.rs
- neqo-crypto/src/p11.rs
- neqo-crypto/tests/handshake.rs
- neqo-crypto/tests/hp.rs
- neqo-http3/src/frames/hframe.rs
- neqo-qpack/src/table.rs
- neqo-transport/src/cid.rs
- neqo-transport/src/connection/mod.rs
- neqo-transport/src/crypto.rs
- neqo-transport/src/packet/metadata.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/src/path.rs
- neqo-transport/src/qlog.rs
- neqo-transport/src/recovery/mod.rs
- neqo-transport/src/recovery/sent.rs
- neqo-transport/src/send_stream.rs
- neqo-transport/src/tparams.rs
- neqo-transport/src/version.rs
Remove a bunch of no-longer-needed clippy nightly bug suppressions, and fix some others.
> chore: New nightly clippy lints & remove unneeded suppressions

- neqo-bin/src/client/http3.rs
- neqo-bin/src/server/http09.rs
- neqo-bin/src/server/http3.rs
- neqo-bin/src/server/mod.rs
- neqo-bin/src/udp.rs
- neqo-transport/src/packet/mod.rs
- neqo-transport/src/server.rs
- neqo-transport/src/tracking.rs
- test-fixture/src/sim/mod.rs
And some functions that did nothing but log.
> fix: Eliminate some variables that are only used for logging

- .config/nextest.toml
- .github/workflows/check.yml
- .github/workflows/mutants.yml
- .github/workflows/sanitize.yml
> ci: Drop `nextest`

- neqo-bin/benches/main.rs
- neqo-common/benches/decoder.rs
- neqo-http3/benches/streams.rs
- neqo-transport/benches/range_tracker.rs
- neqo-transport/benches/rx_stream_orderer.rs
- neqo-transport/benches/sent_packets.rs
- neqo-transport/benches/transfer.rs
> chore: Lower bench times again

- .github/workflows/bench.yml
Sorry for botching the rebase earlier.
> ci: Don't check out twice

- .github/workflows/bencher-upload.yml
> ci: Fix `bencher.dev` upload

- .github/workflows/bench.yml
Fixes issue raised in https://github.com/mozilla/neqo/pull/2688#issuecomment-2944305555.
> ci(bench): fix path to neqo-client and neqo-server main branch binaries

- .github/workflows/bencher-upload.yml
> ci: `github.event.workflow_run.referenced_workflows` is an array

- .github/workflows/bench.yml
- .github/workflows/bencher-upload.yml
It wants the _text_ output from `criterion`, apparently.
> ci: Fixes for bencher.dev upload

- .github/workflows/bencher-upload.yml
> ci: More bencher.dev upload fixes

- .github/workflows/bench.yml
I swear debugging GitHub workflows makes me dumber.
> ci: Fix main SHA exporting

- .github/actions/nss/action.yml
- .github/actions/pr-comment-data-export/action.yml
- .github/actions/rust/action.yml
- .github/workflows/bencher-upload.yml
- .github/workflows/check.yml
- .github/workflows/firefox.yml
- .github/workflows/qns.yml
- .github/workflows/sanitize.yml
These show up when I run locally, but not when we run in CI?
> chore: Fix some `zizmor` lints

- .github/workflows/bencher-archive.yml
- .github/workflows/bencher-upload.yml
- .github/workflows/check.yml
- .github/workflows/clippy.yml
- .github/workflows/firefox.yml
- .github/workflows/fuzz-bench.yml
- .github/workflows/sanitize.yml
And also convert a few remaining `ubuntu-latest` instances to `ubuntu-24.04`.
> chore: Bump macOS runners to `macos-15`

- neqo-common/src/codec.rs
Suggested in https://github.com/mozilla/neqo/pull/2677#discussion_r2114994488 and https://github.com/mozilla/neqo/pull/2677#discussion_r2114994557.
> docs(common): fix panic documentation

- .github/workflows/bench.yml
> ci: Export `samply` data from the bench runs

- Cargo.lock
- Cargo.toml
- neqo-common/Cargo.toml
- neqo-udp/Cargo.toml
- neqo-udp/src/lib.rs
Note the additional handling of EMSGSIZE due to https://github.com/quinn-rs/quinn/pull/2199.
> chore(Cargo.toml): update quinn-udp to v0.5.13

- .cirun.yml
- .github/workflows/bench.yml
- .github/workflows/perfcompare.yml
- test/ansible/install.yml
And adjust the config to use our custom Ansible-created image.
> ci: Fix Ansible playbooks for GCP runner

- neqo-http3/Cargo.toml
Until they can be improved
See #2804
> ci: Disable `stream` benches

- .github/actions/rust/action.yml
- .github/workflows/bench.yml
- .github/workflows/perfcompare.yml
Follow-up to https://github.com/mozilla/neqo/pull/2808#issuecomment-3127665044.
QNS failures will be fixed in https://github.com/mozilla/neqo/pull/2808.
> ci: fix samply unexpected argument '--unstable-presymbolicate'

- .cirun.yml
- test/ansible/install.yml
- test/ansible/shrink.yml
This should fix the CPU pinning issue. Except we're in a VM, so let's see...
> ci: Use 6.11 kernel on GCP

- .github/workflows/perfcompare.yml
> chore: Update other QUIC stacks to latest versions

- .deny.toml
- Cargo.toml
- mtu/Cargo.toml
- neqo-udp/Cargo.toml
> chore: Use workspace deps for `mtu`

- .github/workflows/sanitize.yml
> ci: Fix sanitizer

- .github/workflows/bencher-upload.yml
So that the PR comments don't get overwritten.
See https://github.com/bencherdev/bencher/issues/618#issuecomment-3268632539
> ci: Properly tag bencher uploads

- neqo-common/src/qlog.rs
- neqo-common/tests/log.rs
- neqo-crypto/src/agent.rs
- neqo-crypto/src/time.rs
- neqo-http3/tests/priority.rs
- neqo-transport/src/cc/classic_cc.rs
- neqo-transport/src/fc.rs
- neqo-transport/src/recovery/mod.rs
Instead of `Instant::now`. Might help with #2855.
> fix: Use `test_fixture::now` in tests

- .github/workflows/bench.yml
> ci: Fix bench PR comment formatting

- .github/dependabot.yml
Fixes #2961
I picked some reasonable-seeming periods here; let me know if they should be adjusted.
> ci: Add `cooldown` to Dependabot schedule

- neqo-bin/src/client/http3.rs
Moves Handler::reinit to UrlHandler::reinit.
Ensures URLs are re-enqueued in the same order.
Follow-up to
https://github.com/mozilla/neqo/pull/2926#discussion_r2314615625.
> refactor(bin): move reinit to UrlHandler and maintain URL order

- neqo-http3/tests/webtransport.rs
Test that if a QUIC DATAGRAM is in the same QUIC packet as the WebTransport session 200 Ok, will it be correctly delivered to the application.
Follow-up to https://github.com/mozilla/neqo/issues/1372
> test(webtransport): handle session OK and WT dgram in same UDP dgram

- .github/workflows/bencher-upload.yml
Supported as of 0.5.5, see https://github.com/bencherdev/bencher/issues/618#issuecomment-3289733885
> ci: Upload multiple bencher files in one go

- .github/workflows/actionlint.yml
- .github/workflows/bencher-upload.yml
- .github/workflows/pr-comment.yml
- .github/workflows/qns.yml
- neqo-common/src/codec.rs
(This is me vibing with Claude again.)
> perf(codec): optimize encode functions for modern CPUs
